#!/bin/sh

EAR_FILE_NAME=files.ear
EAR_FILE_PATH=${CI_HOME}/${SRC}/${APPDIR}/build/files.ear/lib/${EAR_FILE_NAME}

ANT_JUNIT_JAR_FILE_NAME=ant-junit.jar
ANT_JUNIT_JAR_FILE_PATH=${CI_HOME}/${SRC}/${APPDIR}/share.test.war/WebContent/WEB-INF/lib/${ANT_JUNIT_JAR_FILE_NAME}

JUNIT_JAR_FILE_NAME=junit.jar
JUNIT_JAR_FILE_PATH=${CI_HOME}/${SRC}/${APPDIR}/share.test.war/WebContent/WEB-INF/lib/${JUNIT_JAR_FILE_NAME}

REST_TEST_JAR_FILE_NAME=lc.rest.test.jar
REST_TEST_JAR_FILE_PATH=${CI_HOME}/${SRC}/${APPDIR}/build/lc.rest.test/lib/${REST_TEST_JAR_FILE_NAME}

SHARE_PLATFORM_TEST_JAR_FILE_NAME=share.platform.test.jar
SHARE_PLATFORM_TEST_JAR_FILE_PATH=${CI_HOME}/${SRC}/${APPDIR}/build/share.platform.test/lib/${SHARE_PLATFORM_TEST_JAR_FILE_NAME}

SHARE_SERVICES_TEST_JAR_FILE_NAME=share.services.test.jar
SHARE_SERVICES_TEST_JAR_FILE_PATH=${CI_HOME}/${SRC}/${APPDIR}/build/share.services.test/lib/${SHARE_SERVICES_TEST_JAR_FILE_NAME}

SHARE_SERVICES_TEST_FVT_JAR_FILE_NAME=share.services.test.fvt.jar
SHARE_SERVICES_TEST_FVT_JAR_FILE_PATH=${CI_HOME}/${SRC}/${APPDIR}/build/share.services.test.fvt/lib/${SHARE_SERVICES_TEST_FVT_JAR_FILE_NAME}

FILES_WEB_TEST_JAR_FILE_NAME=files.web.test.jar
FILES_WEB_TEST_JAR_FILE_PATH=${CI_HOME}/${SRC}/${APPDIR}/build/files.web.test/lib/${FILES_WEB_TEST_JAR_FILE_NAME}

WIKIS_WEB_TEST_JAR_FILE_NAME=wikis.web.test.jar
WIKIS_WEB_TEST_JAR_FILE_PATH=${CI_HOME}/${SRC}/${APPDIR}/build/wikis.web.test/lib/${WIKIS_WEB_TEST_JAR_FILE_NAME}

SHARE_TEST_WAR_FILE_NAME=share.test.war
SHARE_TEST_WAR_FILE_PATH=${CI_HOME}/${SRC}/${APPDIR}/build/share.test.war/lib/${SHARE_TEST_WAR_FILE_NAME}

DEPLOY_SCRIPT_NAME=updt-files.py
DEPLOY_SCRIPT_PATH=${CI_HOME}/${DEPLOY_SCRIPT_NAME}

FILES_TO_COPY[1]=${EAR_FILE_PATH}
FILES_TO_COPY[2]=${ANT_JUNIT_JAR_FILE_PATH}
FILES_TO_COPY[3]=${JUNIT_JAR_FILE_PATH}
FILES_TO_COPY[4]=${REST_TEST_JAR_FILE_PATH}
FILES_TO_COPY[5]=${SHARE_PLATFORM_TEST_JAR_FILE_PATH}
FILES_TO_COPY[6]=${SHARE_SERVICES_TEST_JAR_FILE_PATH}
FILES_TO_COPY[7]=${SHARE_SERVICES_TEST_FVT_JAR_FILE_PATH}
FILES_TO_COPY[8]=${FILES_WEB_TEST_JAR_FILE_PATH}
FILES_TO_COPY[9]=${WIKIS_WEB_TEST_JAR_FILE_PATH}
FILES_TO_COPY[10]=${SHARE_TEST_WAR_FILE_PATH}
FILES_TO_COPY[11]=${DEPLOY_SCRIPT_PATH}
NUM_FILES_TO_COPY=${#FILES_TO_COPY[@]}

# Copy the files to the remote WAS.
for i in `seq 1 $NUM_FILES_TO_COPY`
do
	echo "Copying ${FILES_TO_COPY[i]} to ${REMOTE_USER}@${WAS_HOST_FQDN}:${REMOTE_USER_HOME}/ci/${APPLICATION}..."
	scp ${FILES_TO_COPY[i]} ${REMOTE_USER}@${WAS_HOST_FQDN}:${REMOTE_USER_HOME}/ci/${APPLICATION}
	if [ $? != 0 ]; then
		echo "Failed to copy file."
		exit 1
	fi
done

# Execute the wsadmin command on the remote WAS to deploy the EAR.
echo "Executing wsadmin on ${WAS_HOST_FQDN}..."
ssh ${REMOTE_USER}@${WAS_HOST_FQDN} ${REMOTE_USER_HOME}/lc-update/bin/was adm -f ${REMOTE_USER_HOME}/ci/${APPLICATION}/${DEPLOY_SCRIPT_NAME} ${REMOTE_USER_HOME}/ci/${APPLICATION} ${WAS_SERVER} ${WAS_NODE}
if [ $? != 0 ]; then
	echo "Failed to execute wsadmin command."
	exit 1
fi
