/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* OCO Source Materials                                              */
/*                                                                   */
/* Copyright IBM Corp. 2015                                          */
/*                                                                   */
/* The source code for this program is not published or otherwise    */
/* divested of its trade secrets, irrespective of what has been      */
/* deposited with the U.S. Copyright Office.                         */
/*                                                                   */
/* ***************************************************************** */

/* Generated By:JavaCC: Do not edit this line. VCard21ParserConstants.java */

package com.ibm.lconn.automation.framework.services.profiles.vcard.parser;

/**
 * Token literal values and constants. Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface VCard21ParserConstants {

	/** End of File. */
	int EOF = 0;
	/** RegularExpression Id. */
	int EOL = 1;
	/** RegularExpression Id. */
	int SEOL = 2;
	/** RegularExpression Id. */
	int SEOL_QUOTED_PRINTABLE = 3;
	/** RegularExpression Id. */
	int COLON = 4;
	/** RegularExpression Id. */
	int COLON_QUOTED_PRINTABLE = 5;
	/** RegularExpression Id. */
	int SEMICOLON = 6;
	/** RegularExpression Id. */
	int SEMICOLON_QUOTED_PRINTABLE = 7;
	/** RegularExpression Id. */
	int EQUAL = 8;
	/** RegularExpression Id. */
	int VCBEGIN = 9;
	/** RegularExpression Id. */
	int VCEND = 10;
	/** RegularExpression Id. */
	int EXTENSION = 11;
	/** RegularExpression Id. */
	int WS = 12;
	/** RegularExpression Id. */
	int IDENTIFIER = 13;
	/** RegularExpression Id. */
	int CONTENTSTRING = 14;
	/** RegularExpression Id. */
	int CONTENTSTRING_QUOTED_PRINTABLE = 15;
	/** RegularExpression Id. */
	int NONBREAKINGEQUALS = 16;
	/** RegularExpression Id. */
	int QUOTED_PRINTABLE = 17;
	/** RegularExpression Id. */
	int PARAMSTRING = 18;

	/** Lexical state. */
	int DEFAULT = 0;
	/** Lexical state. */
	int CONTENTSTATE = 1;
	/** Lexical state. */
	int CONTENTSTATE_QUOTED_PRINTABLE = 2;
	/** Lexical state. */
	int PARAMSTATE = 3;
	/** Lexical state. */
	int PARAMSTATE_QUOTED_PRINTABLE = 4;

	/** Literal token values. */
	String[] tokenImage = { "<EOF>", "<EOL>", "<SEOL>", "<SEOL_QUOTED_PRINTABLE>", "\":\"", "\":\"", "\";\"", "\";\"", "\"=\"",
			"<VCBEGIN>", "<VCEND>", "<EXTENSION>", "<WS>", "<IDENTIFIER>", "<CONTENTSTRING>", "<CONTENTSTRING_QUOTED_PRINTABLE>", "\"=\"",
			"<QUOTED_PRINTABLE>", "<PARAMSTRING>", "\".\"", };

}
