package com.ibm.conn.auto.webui.constants;

public final class ActivitiesUIConstants {

    public static String Start_Activity_NoResultFound = "css=div[id='lconn_core_PeopleTypeAhead_0_popup0']";
    public static String Activities_Tab = "css=a.lotusTab[aria-label='Activities']";
    public static String ActivityListName = "css=h1[id='activityList-Name'][dojoattachpoint='listName_AP']";
    public static String activityTab = "css=li[id='myActivitiesTab'] a[class='lotusTab']";
    public static String ActivityHome_ExpandActivityDetails_TopActivity = "css=td[class^=lotusAlignRight]:nth(0) a";
    public static String ActivityOutline_More_ExpandDescription = "link=... [more]";
    public static String Activities_LeftNav_Trash = "css=a[href='#dashboard,trash,']>span:contains(Trash)";
    public static String Activities_LeftNav_Members = "css=a:contains(Members)";
    public static String SearchTextArea = "css=span#commonSearchControlContainersearchInput input[title='Search'], span[id^='lconn_core_SearchBar'] input[title='Search']";
    public static String SearchButton = "css=span.lotusBtnImg input.lotusSearchButton[title='Search']";
    public static String AddToDo = "css=div span.lotusBtn a:contains('Add To Do Item')";
    public static String ToDo_InputText_Title = "css=input[id^=lconn_act_ToDoForm_][id$=title]:nth(0)";
    public static String ToDo_InputText_Tags = "css=input[id^=lconn_act_ToDoForm_][id$=tags]:nth(0)";
    public static String More_Actions = "css=a[aria-label='More Actions']";
    public static String ToDo_More_Options = "css=a#moreOptionsLink span[dojoattachpoint='moreOptionsText_AP'],a[id='moreOptionsLink'] span:contains(More Options)";
    public static String ToDo_AssignTo_Pulldown = "css=select[dojoattachpoint='assignType_AP']";
    public static String ToDo_DueDate = "css=input[id^=lconn_act_ToDoForm_][id$=duedate]";
    public static String ToDo_Assign_FilterBox = "css=input[id^='lconn_core_FilteringCheckbox']";
    public static String AddSection = "css=div span.lotusBtn a:contains('Add Section'):nth(0)";
    public static String Section_InputText_Title = "css=input[id^=lconn_act_SectionForm_][id$=sectionInputTitle]:nth(0)";
    public static String Section_Action_Menu = "css=a.actionsMenu";
    public static String New_Entry = "css=div span.lotusBtn a:contains('Add Entry')";
    public static String New_Entry_InputText_Title = "css=input[id^='lconn_act_EntryForm_'][id$='title']";
    public static String New_Entry_InputText_Tags = "css=input[id^='lconn_act_EntryForm_'][id$='tags']";
    public static String New_Entry_Add_Bookmark = "link=Add Bookmark";
    public static String New_Entry_Bookmark1_Row = "css=input[title='Bookmark Name']";
    public static String New_Entry_Bookmark1_Label_InputText_LableName = New_Entry_Bookmark1_Row;
    public static String New_Entry_Bookmark1_InputText_LinkURL = "css=input[title='Bookmark Url']";
    public static String New_Entry_AddCustomFieldsMenu = "css=a:contains('Add Custom Fields')";
    public static String New_Entry_AddCustomFields_TextLabel = "css=input[id^='dijit_form_TextBox_']";
    public static String New_Entry_AddCustomFields_Text = "css=input[title='Text Field']";
    public static String New_Entry_Date_Row = "css=input[id^='lconn_act_DateTextBox_']";
    public static String New_Entry_Date_Label_InputText_LableName = New_Entry_Date_Row;
    public static String New_Entry_Description = "css=iframe[title^='Rich Text Editor']";
    public static String New_Entry_Private_Checkbox = "css=input[id*='privateCheck']";
    public static String New_Entry_Notify_Checkbox_Notify = "css=input[id$='notifyCheck']";
    public static String New_Entry_Notify_Checkbox_NotifyAll = "css=input[id*='notifyAll']";
    public static String New_Entry_Notify_Message = "css=textarea[id*='notifyMessage']";
    public static String ActivityEntry_ExpandThisEntry = "css=div:contains('PLACEHOLDER') > a[aria-label='Expand this entry']";
    public static String ActivityEntry_MoreActions = "css=div[uuid='PLACEHOLDER'] > div[class='entryFooter'] > div > ul > li > a[aria-label='More Actions']";
    public static String ActivityEntry_SelectUser_Checkbox = "css=input[id*='PLACEHOLDER'][name*='_FilteringCheckbox_']";
    public static String ActivityEntry_SendButton = "css=input[value='Send']";
    public static String AddFileLink = "css=a[aria-label='Add File']";
    public static String AttachFileLink = "css=a[aria-label='Attach File']";
    public static String AttachFileLinkFromAddButton = "css=table[class$='dijitMenuActive'] tbody[class='dijitReset'] tr:contains(Attach File)";
    public static String AttachDownload = "css=a.lotusFileAction";
    public static String AttachmentField = "css=span input.fieldFileNode";
    public static String ActivityHome_EditActivity_TopActivity = "css=a:contains(Edit):nth(0)";
    public static String ActivitiesHome_DeleteActivity_TopActivity = "css=a:contains(Delete):nth(0)";
    public static String Delete_Activity_Dialogue_OkButton = "css=input[value='OK']";
    public static String EntryComment = "css=div[class='entryFooter'] div ul li[class='lotusFirst feedCapVisible'] a:contains(Add Comment)";
    public static String Start_An_Activity = "css=span[id^=lconn_act_StartActivityButton_] a,div span a:contains(Create Your First Activity)";
    public static String Start_An_Activity_Community = "css=div#startActivity > span.lotusBtn > a";
    public static String Start_An_Activity_InputText_Name = "css=input#lconn_act_ActivityForm_0_titleInput";
    public static String Start_An_Activity_InputText_Tags = "css=input#lconn_act_ActivityForm_0tagz";
    public static String Start_An_Activity_Textarea_Activity_Goals = "css=textarea[id*='descriptionInput']";
    public static String Start_An_Activity_InputText_DueDate = "id=lconn_act_ActivityForm_0duedate";
    public static String Start_An_Activity_InputSelect_MemberType = "css=select[title='Member Type']";
    public static String Start_An_Activity_InputSelect_MemberRole = "css=select[title='Member Role']";
    public static String Start_An_Activity_InputText_Members_PeopleTypeAhead = "css=div span input[aria-label='Start typing a name to add a member']";
    public static String sc_Start_An_Activity_InputText_Members_PeopleTypeAhead = "css=*[name='bhc_PeopleTypeAhead']";
    public static String Start_An_Activity_Members_TypeaheadPromptList = "css=#lconn_core_PeopleTypeAhead_0";
    public static String UsersActivitySearchIdentifier = Start_An_Activity_Members_TypeaheadPromptList + "_searchDir";
    public static String memberHasReaderRole = "css=div[id$=_memberRoleDiv]:contains(Reader)";
    public static String SelectedActivityUserIdentifier = "css=*[id$='lconn_core_PeopleTypeAhead_0'] li:nth(1)";
    public static String ToDoListTab = "css=div ul li a[aria-label='To Do List']";
    public static String TemplateTab = "css=div ul li a[aria-label='Activity Templates']";
    public static String Activity_Template = "css=a[dojoattachpoint='mytemplates_AP']";
    public static String createATemplate = "link=Create a Template";
    public static String Template_InputText_Title = "css=input[id^=lconn_act_ActivityForm_][id$=titleInput]";
    public static String Template_InputText_Tags = "css=input[id^=lconn_act_ActivityForm_][id$=tagz]";
    public static String Template_InputText_Description = "css=textarea[id^=lconn_act_ActivityForm_][id$=descriptionInput]";
    public static String NoActivitiesMessage = "css=div.lconnEmpty:contains(No activities to display.)";
    public static String templateActionsLink = "css=li[dojoattachpoint='moreActions_AP'] a span:contains(Template Actions)";
    public static String editTemplateOption = "css=td[id^='lconn_act_DynamicMenuItem']:contains(Edit Template)";
    public static String startAnActivityFromTemplate = "link=Start an Activity from this Template";
    public static String startAnActivityFromTemplateInList = "css=ul li a:contains('Start Activity from this Template')";
    public static String activitiesOption = "css=a>strong:contains(Activities)";
    public static String activitiesToDoList = "css=td>a:contains(To Do List)";
    public static String activitiesHighPriorityAct = "css=td>a:contains(High Priority Activities)";
    public static String nameInputField = "css=div span input[id='lconn_core_PeopleTypeAhead_0']";
    public static String nameListSearchIcon = "css=li[id='lconn_core_PeopleTypeAhead_0_popup_searchDir'], div[id='lconn_core_PeopleTypeAhead_0_popup_searchDir']";
    public static String namesInList = "css=div[id^='lconn_core_PeopleTypeAhead_0_popup'], div[class='dijitMenuItem'][id^='lconn_core_PeopleTypeAheadMenu']";
    public static String Change_Access = "css=a[title^='Change'][title$='Access']";
    public static String PublicAccess_RadioBtn = "css=*[id^='lconn_act_PublicAccessSelector_'][id$='publicAccess']";
    public static String Change_Access_SC = "css=a[dojoattachpoint='organizationChange_AP']";
    public static String PublicAccess_RadioBtn_SC = "css=#lconn_act_PublicAccessSelector_1publicAccess";
    public static String PublicActivities_Active = "css=#dashNavPanel-publicSection > ul > li > a:contains(Active),#dashNavPanel-orgSection > ul > li > a:contains(Active)";
    public static String ActivityAddCommentBtn = "css=li.lotusFirst a:contains('Add Comment')";
    public static String moreLink ="css=span:contains(More)";
    public static String navigateAwayPromptOK = "css=input[class='lotusBtn submit cnxPrimaryBtn']";
    public static String navigateAwayPromptCancel = "css=input[class='cancel lotusBtn cnxSecondaryBtn']";
    public static String navigateAwayPromptClose = "css=a.lotusDialogClose img[aria-label='Close']";
    public static String EditActivity_Save = "css=div[id*='lconn_act_Dialog_'][class*='lotusDialogWrapper'] div.lotusDialogBorder div.lotusDialog div.lotusDialogFooter span input.lotusFormButton";
    public static String EditActivity_StartPage = "css=select[id^='lconn_act_ActivityForm']";
    public static String Recent_Updates_Tab = "css=a.lotusTab[aria-label='Recent Updates']";
    public static String recentUpdatesHeader = "css=h1:contains('Recent Updates')";
    public static String ToDoHeader = "css=h1:contains('To Do Items')";
    public static String actionCopy = "css=tr[aria-disabled='false'] > td:contains('Copy')";
    public static String Close_Welcome = "css=a[title='Close Activities Welcome Panel']";
    public static String showMoreInfo = "css=tbody tr td a[aria-label='Show more information about this Activity']";
    public static String activityActionMenu = "css=span:contains(Activity Actions)";
    public static String actionMenuAddRelatedActivity = "css=[id^=lconn_act_DynamicMenuItem_][id$=_text]:contains(Add Related Activity)";
    public static String Activities_Help = "link=Find out how an activity can keep your team focused on a goal.";
    public static String Activities_Help_ToDo = "link=assign and track to-do items.";
    public static String View_Demo = "link=View Demo";
    public static String Footer_Demo = "link=Demo";
    public static String Activity_View_Demo = "css=div.lotusWelcomeBox > div.lconnDemoThumbnail > div > a[title='View Demo'] > img";
    public static String About_Watch_Demo = "link=Watch a demo";
    public static String Todo_CompleteCheckBox="css=input[id*='miniCheckBox']";
    public static String Todo_CompleteCheckBox_Unique = "css=div[class='entryIcon nodeTypeTodo'] > input[id*='PLACEHOLDER'][aria-label*='REPLACE_THIS']";
    public static String ToDo_AssignedTo_SelectAll_CheckBox="css=input[id*='selectAllAssignees']";
    public static String Todo_CompleteConfirmation="css=span#lconn_act_NonceSaveButton_3.dijitButtonForm input.lotusFormButton";
    public static String editEntry = "css=a[role='button'][id$=editLink]:contains('Edit')";
    public static String Todo_Select_AssignedUser ="css=label[id*='lconn_core_FilteringCheckbox_0notifyCheckbox']";//requires user display name also to select correct user ie [title='testUser2.getDisplayName()']
    public static String Todo_SaveButton_AssignUser ="css=div.lotusFormFooter>span>input";
    public static String External_Activity_Creation ="css=span[title='This activity can have members from outside your organization.']";
    public static String ActivitiesTab ="css=a[dojoattachpoint='myactivities_AP']";
    public static String Permissions_Warning ="css=span[dojoattachpoint='warnMessage_AP']:contains(Activity content will be seen by people both inside and outside of your organization.)";
    public static String SelectMoreOption = "css=a:contains('... [more]')";
    public static String SelectMembers = "css=a:contains('Members')";
    public static String SaveButton_PermissionChange = "css= span#lconn_act_NonceSaveButton_0.dijitButtonForm input.lotusFormButton";
    public static String SaveButton_PermissionChange_SC = "css= span#lconn_act_NonceSaveButton_1.dijitButtonForm input.lotusFormButton";
    public static String activitiesAddButton = "css=input[id='activitiesAddButton']";
    public static String AddMembersButton = "css=input[id='addMembersButton']";
    public static String OverallMyActivity = "css=a[href='#dashboard,myactivities,']>span:contains(My Activities)";
    public static String OverallHighPriority = "css=a[href='#dashboard,highpriority,']>span:contains(High Priority)";
    public static String OverallMediumPriority = "css=a[href='#dashboard,medpriority,']>span:contains(Medium Priority)";
    public static String OverallTurnedOut = "css=a[href='#dashboard,tunedout,']>span:contains(Tuned Out Activities)";
    public static String OverallTrash = "css=a[href='#dashboard,trash,']>span:contains(Trash)";
    public static String OverallCommunityActivities = "css=a[href='#dashboard,commactivities,']>span:contains(Community Activities)";
    public static String OverallCompletedActivities = "css=a[href='#dashboard,completed,']>span:contains(Completed Activities)";
    public static String OverallInCompletedToDos = "css=a[href='#todolist,incomplete,']";
    public static String OverallCompletedToDos = "css=a[href='#todolist,completed,']";
    public static String StartCommunityActivityImplicitRole = "css=select[title='Member Role'][aria-label='Allow all members of this community access in the activity as:']";
    public static String StartCommunityActivityExplicitRole = "css=select[title='Member Role'][aria-label='Allow only the following community members access in the activity as:']";
    public static String CommunityActivityImplicitRoleOption="css=input[id^='lconn_act_CommunityMembersSection_'][id$='notifyAll']";
    public static String CommunityActivityExplicitRoleOption="css=input[id^='lconn_act_CommunityMembersSection_'][id$='notifySeparate']";
    public static String CommunityActivityFollow = "css=td[id^='dijit_MenuItem_']:contains('Follow this Activity')";
    public static String CommunityActivityUnFollow = "css=td[id^='dijit_MenuItem_']:contains('Stop Following this Activity')";
    public static String CommunityFolowMenu = "css=a[id^='lconn_core_FollowMenu_']";
    public static String followThisActivityLink = "css=a[role='button']:contains(Follow this Activity)";
    public static String CommunityActivities_LeftNav_Members = "css=a[href^='#activitypage_members,']:contains(Members)";
    public static String Activities_LeftNav_Outline = "css=a:contains(Activity Outline)";
    public static String LinkToFileFromAddButton = "xpath=//tr[@aria-label='Link to File ']";
    //table[class$='dijitMenuActive'] tbody[class='dijitReset'] tr:contains(Link to File)";
    public static String LinkToFolderFromAddButton = "css=table[class$='dijitMenuActive'] tbody[class='dijitReset'] tr:contains(Link to Folder)";
    public static String linkToFolderDropdown = "css=div[id^=lconn_files_widget_PersonalFolderPicker][id$=_content_searchBar] > select";
    public static String Start_An_Activity_InputText_Members_CommunityTypeAhead = "css=div span input[aria-label='Start typing a name to add a community']";
    public static String actionNotify = "css=tr[aria-disabled='false'] > td:contains('Notify Other People')";
    public static String actionLinkToEntry = "css=td:contains('Link to this Entry')";
    public static String actionMove = "css=tr[aria-disabled='false'] > td:contains('Move')";
    public static String actionDelete = "css=tr[aria-disabled='false'] > td:contains('Delete')";
    public static String actionConvert = "css=tr[aria-disabled='false'] > td:contains('Convert to To Do Item')";
    public static String actionMenuHighPriority = "css=[id^=lconn_act_DynamicMenuItem_][id$=_text]:contains(High Priority)";
    public static String actionMenuMediumPriority = "css=[id^=lconn_act_DynamicMenuItem_][id$=_text]:contains(Medium Priority)";
    public static String actionMenuNormalPriority = "css=[id^=lconn_act_DynamicMenuItem_][id$=_text]:contains('Normal Priority (Default)')";
    public static String actionMenuTurnedOut = "css=[id^=lconn_act_DynamicMenuItem_][id$=_text]:contains(Mark as Tuned Out)";
    public static String actionMenuCopyActivity = "css=[id^=lconn_act_DynamicMenuItem_][id$=_text]:contains(Copy Activity)";
    public static String actionMenuDeleteActivity = "css=[id^=lconn_act_DynamicMenuItem_][id$=_text]:contains(Delete Activity)";
    public static String actionMenuCopyAsTemplate = "css=[id^=lconn_act_DynamicMenuItem_][id$=_text]:contains(Copy as New Template...)";
    public static String Activity_Todo_Item_Link = "css=div[entrytype='todo'] > div[class='MiniNode'] > h4[id*='miniTitle'] > span:contains('PLACEHOLDER')";
    public static String Activity_Public_Access_On_Prem = "css=span[title='Public Access']:contains('Public')";
    public static String Activity_Public_Access_SC = "css=span[title*='Access']:contains('Everyone')";
    public static String activityDetailDisplayOn = "//a[@class='lotusSprite lotusView lotusDetailsOff']";
    public static String activityTabNewUI = "//div[@id='tertiary_level_nav']//a[@aria-label='Activities']";
    //TinyEditor Element
    public static String editFirstEntryNewEntry = "css=div.Node a:contains(Edit)";
    public static String activityEntryDescDOM="css=div.entryContent > div.description";
    public static String activityToDoItemLink="xpath=//div[@class='MiniNode']//span[text()='PLACEHOLDER']";
    public static String activityToDoItemDOM="xpath=//h4[@class='entryTitleBar']/span[text()='PLACEHOLDER']/../../..//div[@class='entryContent']/div[@class='description']";
    public static String activityToDoItemEditLink="xpath=//h4[@class='entryTitleBar']/span[text()='PLACEHOLDER']/../../..//a[text()='Edit']";
    
    //VisitorModel elements
    public static String editSectionOption = "css=td[id^='dijit_MenuItem']:contains(Edit Section)";
    public static String editSectionTitle = "css=input[id$='sectionInputTitle']";

    //MT
    public static String activitiesNavigationBar = "css=#activitiesNagvigationToolbar";
    public static String Activity_Private_Access = "css=span[title*='Access'][dojoattachpoint^='organizationAccessLevel']:contains(Private (Default))";

    //Add Link to File
  	public static String viewDetails="xpath=//a[contains(text(),'View Details')]";
  	
  //Hudos Board
  	public static String huddoIcon= "//a[@id='back-to-dashboard'] [@title='Huddo Boards']";
  	
  	// Cnx8UI 
  	public static String startAnActivityBtn = "//div[@id='activityList'] //a[contains(text(),'Start an Activity')]";
  	public static String myActivities_tagSection = "//div[@id='dashboard'] //div[@title='Tags']";
  	public static String activitiesTab = "//div[@id='tertiary_level_nav']//li[@id='myActivitiesTab']";
  	public static String toDoListTab = "//div[@id='tertiary_level_nav']//li[@id='todoListTab']";
  	public static String activityTemplatesTab = "//div[@id='tertiary_level_nav']//li[@id='templatesTab']";
  	public static String recentUpdatesTab = "//div[@id='tertiary_level_nav']//li[@id='updatesTab']";
  	public static String addSectionBtn = "//a[@id='activityAddSectionButton']";
  	public static String addEntryBtn = "//a[@id='activityAddEntryButton']";
  	public static String addToDoItemBtn = "//a[@id='activityAddToDoButton']";
  	public static String activityOutline_tagSection = "//div[@id='activitypage'] //div[@title='Tags']";
  	public static String followThisActLink = "//div[@class='lotusColRight'] //a[contains(text(),'Follow this Activity')]";
  	public static String markActCompleteLink = "//div[@class='lotusColRight'] //a[contains(text(),'Mark Activity Complete')]";
  	public static String activityActionLink = "//div[@class='lotusColRight'] //a[@aria-label='Activity Actions']";
  	public static String loadingIcon = "div[class='SpinnerOverlay']";
  	public static String communityActivitiesLink = "//div[@id='dashNavPanel-activity-list']//span[contains(text(),'Community Activities')]";
  	public static String communityActivitiesName = "//table[@class='lotusTable lotusClear']//a[contains(text(),'PLACEHOLDER')]";
  	//Community Activities
  	public static String communityHeaderName = "//div[@id='activitiesTitleBar']//div[contains(text(),'PLACEHOLDER')]";
  	public static String actionsButton = "//div[@id='communityActionBarContainer']//a[contains(text(),'PLACEHOLDER')]";
  	public static String activityActionButton = "//div[@id='communityActionBarContainer']//span[contains(text(),'Activity Actions')]";
  	public static String comActivities_tagSection = "//div[@id='activitypage'] //div[@title='Tags']";
  	
  	public static String activityOutline = "//span[@id='actNavPaneloutlineLabel']";
  	public static String recentUpdates = "//a[contains(text(),'Recent Updates')]";
  	public static String todoItems = "//a[contains(text(),'To Do Items')]";
  	public static String trash = "//a[contains(text(),'Trash')]";
  	public static String members = "//a[contains(text(),'Members')]";
  	public static String sectionsDropdown = "//span[contains(text(),'Sections')]";
  	public static String todoPageTitle = "//h1[@id='todolistWidget-Title']";
  	public static String activityTemplatesPageTitle = "//h1[@id='t_activityList-Name']";
	public static String recentUpdatesPageTitle = "//h1[@id='eventLog-Title']";
	public static String activitiesPagination = " //div[@id='custom_stream_pagination_dropdown']";
	public static String resultPerPageDropdown = "//div[@class='pagination-dropDown-select-wrapper']";
	public static String myActivity = "//a[@href='#dashboard,myactivities,']//span[contains(text(),'My Activities')]";
	public static String highPriorityLeftNav = "//a[@href='#dashboard,highpriority,']//span[contains(text(),'High Priority')]";
	public static String mediumPriorityLeftNav = "//a[@href='#dashboard,medpriority,']//span[contains(text(),'Medium Priority')]";
	public static String turnedOutLeftNav = "//a[@href='#dashboard,tunedout,']//span[contains(text(),'Tuned Out Activities')]";
	public static String trashLeftNav = "//a[@href='#dashboard,trash,']//span[contains(text(),'Trash')]";
	public static String communityActivities = "//a[@href='#dashboard,commactivities,']//span[contains(text(),'Community Activities')]";
	public static String completedActivities = "//a[@href='#dashboard,completed,']//span[contains(text(),'Completed Activities')]";
	public static String highPriority = "//table//td[text()='High Priority']";
	public static String mediumPriority = "//table//td[text()='Medium Priority']";
	public static String markAsTurnedOut = "//table//td[text()='Mark as Tuned Out']";
	public static String createATemplateBtn = "//a[text()='Create a Template']";
	public static String startAnActivityFromTemplateBtn = "//a[text()='Start an Activity from this Template']";

    private ActivitiesUIConstants() {}

}
