package com.ibm.conn.auto.webui.constants;

public final class BlogsUIConstants {


	/** Ideation Blogs Tabs */
	public static final String FirstIdeaLink = "link=Create Your First Idea";
	public static final String VoteBtn = "css=a:contains(Vote)";
	public static final String VoteNumber = "css=div[class='ideaVotingNumber']";
	public static final String VoteText = "css=span[dojoattachpoint='voteText']";
	public static final String Ideation_NewIdea = "link=New Idea";
	public static final String Ideation_IdeasTab = "css=a[aria-label='Ideas']";
	public static final String MoreActions = "link=More Actions";
	public static final String MarkAsDuplicateMsg = "css=h1#duplicateFormTitle";
	public static final String DuplicateShowDetail = "css=a[role='button']:contains(Show Details)";
	public static final String DuplicateConfirmWin = "css=#com_ibm_oneui_controls_MessageBox_0";
	public static final String IdeaVoteBtn = "css=div[class='ideaVotingButtonDiv']";
	public static final String VoteSubmitBtn = "css=input[class='lotusFormButton submit']";
	public static final String IdeaCommentLink = "css=div[class='lotusMeta'] a[href*='comment']";
	/** Blogs Tabs */
	public static String MyBlogs = "css=ul li a:contains(My Blogs)";
	public static String myBlogsTab = "xpath=//div[@id='tertiary_level_nav']//span[text()='My Blogs']";
	public static String PublicBlogs = "css=ul li a:contains(Public Blogs)";
	public static String Administration = "css=ul li a:contains(Administration)";
	public static String BlogsSetAsPrimaryBlog = "css=a[aria-label='Set as Primary Blog']";
	//public static String BlogsNewEntry = "css=span[class='lotusBtn lotusLeft']";
	public static String BlogsNewEntry = "css=span[class='lotusBtn lotusLeft'] a:contains('New Entry')";
	public static String BlogsNewEntryAddTags = "css=div a[aria-label='Add Tags']";
	public static String BlogsNewEntryAddTagsTextfield = "css=input[id='addtagwidgetAddTagsTypeAhead']";
	public static String BlogsNewEntryAddTagsOK = "css=input[value='OK']";
	public static String BlogsNewEntryTitle = "css=input[id='title']";
	public static String BlogsNewEntryPost = "css=input#postEntryID";
	public static String BlogsFileUploadButton = "css=input#uploadBtn.lotusBtn";
	public static String blogsSettings = "css=div ul li a:contains(Manage Blog)";
	public static String blogsSettingsAllowComments = "css=input[id='allowComments']";
	public static String blogsUpdateSettings = "css=input[value='Update Blog Settings']";
	public static String blogsIdeationUpdateSettings = "css=input[value='Update Ideation Blog Settings']";
	public static String blogManage = "css=a[role='button']:contains(Manage Blog)";
	public static String blogsNewEntryMenuItem = "//div[@id='lotusContent']/div/span[contains(a, 'New Entry')]/a";
	public static String blogsNewEntryLink = "css=a[id='blogsAddNewEntryLink']";
	public static String blogsActionMenu = "css=a:contains(Blog Actions)";
	public static String blogsManage = "css=td:contains(Manage Blog)";
	public static String entriesLinkLeftNav = "css=div#lotusColLeft a.bidiAware:contains(Entries)";
	public static String blogLeftNav = "css=div ul[id='bizCardNav'] li a:contains(Blog)";
	public static String BlogsCKEImageDlgCloseIcon = "css=a[id='closeDialog']";
	public static String BlogsCKEImageDlgHeader = "css=span[id='insertImageDialogTitle']:contains(Insert Image)";
	public static String BlogsCKEImageDlgLocalFilesTab = "css=div ul li[id='localFilesTab']";
	public static String BlogsCKEImageDlgLocalFilesSelected = "css=div[class='lotusDialog localFilesSelected']";
	public static String BlogsCKEImageDlgWebUrlTab = "css=div ul li[id='externalUrlTab']";
	public static String BlogsCKEImageDlgWebUrlTabSelected = "css=a[id='externalUrlTabLink'][aria-selected='true']";
	public static String BlogsCKEImageDlgWebUrlFieldLabel = "css=label[id='blogImgWebUrlPrompt']:contains(Web Image URL:)";
	public static String BlogsCKEImageDlgWebUrlPreviewArea = "css=span[id='blogImgWebUrlPreviewPlaceholder']:contains(Preview area: Large images might take awhile to display.)";
	public static String BlogsCKEImageDlgExistingImagesTab = "css=ul[id='blogImgLotusTabList'] li[id='existingImageTab'] a:contains(Existing Images)";
	public static String BlogsCKEImageDlgExistingImagesTabSelected = "css=a[id='existingImageTabLink'][aria-selected='true']";
	public static String BlogsCKEImageDlgExistingImagesNoImagesIcon = "css=img[class='lconnNoImagesIcon']";
	public static String BlogsCKEImageDlgExistingImagesNoImageMsg = "css=span[id='noImageLabel']:contains(Oops! No image has been added yet.)";
	public static String BlogsCKEImageDlgAddiOptLabel = "css=a[id='blogImgLayoutPropLabel']";
	public static String BlogsCKEImageDlgAddiOptTwistieCollapsed = "css=input[class='lotusArrow lotusTwistyClosed']";
	public static String BlogsCKEImageDlgAddiOptTwistieExpanded = "css=input[class='lotusArrow']";
	public static String BlogsCKEImageDlgAddiOptExpanded = "css=a[title='Collapse Additional Options']";
	public static String BlogsCKEImageDlgAddiOptCollapsed = "css=a[title='Expand Additional Options']";
	public static String BlogsCKEImageDlgLayoutLabel = "css=form[id='insertImageSettings'] p:contains(Image Layout:)";
	public static String BlogsCKEImageDlgLayoutLeft1Selected = "css=input[id='blogImgLayoutLeft1'][class='blogImgLayout lotusSelected']";
	public static String BlogsCKEImageDlgLayoutLeft2 = "css=input[id='blogImgLayoutLeft2']";
	public static String BlogsCKEImageDlgLayoutCenter = "css=td input[id='blogImgLayoutCentered']";
	public static String BlogsCKEImageDlgLayoutCenterSelected = "css=td input[id='blogImgLayoutCentered'][class='blogImgLayout lotusSelected']";
	public static String BlogsCKEImageDlgLayoutRight = "css=input[id='blogImgLayoutRight']";
	public static String BlogsCKEImageDlgMessageInvalidURL = "css=div[id^='com_ibm_oneui_controls_MessageBox_'] div span:contains(Invalid URL. Make sure to enter a valid URL and try again.)";
	public static String BlogsCKEImageDlgMessageNonImageURL = "css=div[class='lotusMessageBody'] span:contains(The image seems to have failed to load, are you sure this is a valid image url?)";
	public static String BlogsCKEImageDlgImageSizeLabel = "css=span:contains(Image Size:)";
	public static String BlogsCKEImageDlgImageSizeHelpIcon = "css=a[id='sizeHelpLink'] img[class$='lconnSprite-iconHelp16']";
	public static String BlogsCKEImageDlgImageSizeOriginal = "css=label[class='image-size-table']:contains(Original)";
	public static String BlogsCKEImageDlgImageSize200Pixels = "css=label[class='image-size-table']:contains(200 pixels wide)";
	public static String BlogsCKEImageDlgLayoutMedSize = "css=tr td div nobr input[id='radio_medium']";
	public static String BlogsCKEImageDlgImageSizeFitPage = "css=label[class='image-size-table']:contains(Fit page width)";
	public static String BlogsCKEImageDlgLayoutChkDef = "css=#insertImageSettings input[id='check_default']";
	public static String BlogsCKEImageDlgWebUrlInput = "css=div input[id='blogImgWebUrlInput']";
	public static String BlogsCKEImageDlgBrowseButton = "css=span[class$='pickerInputSpan'] input[value='Browse...']";
	public static String BlogsCKEInsertImageButton = "css=a[data-title='Insert Image']";
	public static String BlogsCKEImageDlgInsertImageButton ="css=input[id='insertButton'][value='Insert Image']";
	public static String BlogsCKEInsertImageButtonDisabled = "css=input[class$='lotusBtnDisabled'][value='Insert Image']";
	public static String BlogsCKEUploadImageButton = "css=input[id='insertButton'][value='Upload Image'])";
	public static String BlogsCKEUploadImageButtonDisabled = "css=input[class$='lotusBtnDisabled'][value='Upload Image']";
	public static String BlogsCKECancelButton = "css=input[id='cancelButton'][class='lotusFormButton']";
	public static String BlogsCKEInsertFromRecent = "css=a[id='existingImageTabLink']";
	public static String BlogsCKEChoosePhoto = "//td[@id='uploadedImageDiv1']/img[@id='uploadedImage1']";
	public static String BlogsCKEInsertButton = "css=input[id='insertButton'][value='Insert Image']";
	public static String BlogsCKEInsertButtonJS = "javascript:document.getElementById('insertButton').click()";
	public static String BlogsSiteSettingsHandleOfBlog = "css=input[name='site.frontpage.weblog.handle']";
	public static String blogsSettingsUpdateButton = "css=*[value='Update Blog Settings']";
	public static String BlogsAddACommentLink = "css=#AddWeblogEntryCommentLink";
	public static String BlogsCommentTextArea = "css=div[id^='mentionstextAreaNode']";
	public static String scBlogsCommentTextArea = "css=textarea[dojoattachpoint='textAreaNode'], div[class='cke_contents cke_reset lotusTextExpanded']";
	public static String BlogsCommentSubmit = "css=input[value='Submit'][name='submitButton']";
	public static String BlogsFileUploadsLink = "css=a:contains(File Uploads)";
	public static String BlogsFileUploadInput = "css=input[id^='uploadFile0']";
	public static String blogsSettingsDisplay = "css=tbody tr td input#entryDisplayCount";
	public static String BlogsSettingsRemoveBlog = "css=input[class='lotusBtn'][value='Remove Blog'], "
								+ "input[class='lotusBtn'][value='Delete Blog']";
	public static String BlogsSettingsRemoveBlogCheckBox = "css=input[id='agreeToDeleteWebsite']";
	public static String BlogsSettingsRemoveBlogConfirmationNo = "css=input[value='No'], input[class='lotusFormButton cancel']";
	public static String BlogsSettingsRemoveBlogConfirmationYes = "css=input[value='Yes'], input[class='lotusFormButton submit']";
	public static String BlogsCurrentSearchScope = "css=#global_search_containersearchOpt";
	public static String BlogsSearchBar = "css=#global_search_containersearchInput input.lotusText";
	public static String BlogsSearchButton = "css=#global_search_container.lotusGlobalSearch form table.lotusLayout tbody tr td span.lotusBtnImg input.lotusSearchButton";
	public static String PublicBlogsMyLikesVotesHeader = "css=#lotusContent.lotusContent div.lotusHeader";
	public static String BlogsEntryLikeCount = "css=div[class='lotusLikeText']";
	public static String BlogsEntryLike = "css=a[title='Like this'], a[id^='TOGGLE_entry_']:contains(Like)";
	public static String BlogsEntryUnlike = "css=a:contains(Unlike)";
	public static String BlogsEntryCommentLike ="css=a[id='TOGGLE_com_ibm_oneui_controls_Like_0']";
	public static String BlogsEntryLikeDescription = "css=span[class=lotusLikeDescription]";
	public static String BlogsEntryLikesWidget = "css=#entries table.lotusTable div[class='lotusLike']";
	public static String BlogsEntryLikePopup = "css=div[id^='com_ibm_oneui_controls_internal__MasterPopup']";
	public static String BlogsPublicLikes = "link=My Likes/Votes";
	public static String BlogsPublicSortByLikes = "link=Likes/Votes";
	public static String BlogCommentTrackbackCheckBox = "css=input[id='postCommentAsTrackback']";
	public static String BlogCommentTrackDropDown = "css=select[title='Target blog']";
	public static String allowedExtensions = "323, asc, bas, c, etx, h, jw, log, mcw, msg, ow, pfs, qa, rtf, sow, text, tsv, tw, txt, uls, vw3, ws," +
									  " xy,doc, docm, docx, dot, dotm, dotx, en4, enw, leg, lwp, lwp7, manu, msw, mwp, mwp2, mwpf, odc, odg, odt," +
									  " ort, otg, oth, otm, ott, pages, pcl, rtx, std, stw, sxd, sxq, sxw, w6, w97, wm, wp5, wp6, wpf,123, 12m, acs," +
									  " csv, dbs, dez, ens, fcd, fcs, mwkd, mwks, odf, ods, oss, otf, ots, qad, smd, sms, stc, sxc, sxm, wg2, wk4, wk6," +
									  " xla, xlam, xlc, xlm, xls, xlsb, xlsm, xlsx, xlt, xltm, xltx, xlw,flw, key, mass, odp, ope, otc, otp, pot, potm," +
									  " potx, pp2, pp97, ppam, pps, ppsm, ppsx, ppt, pptm, pptx, prz, shw3, sti, sxi, pdf, swf, fla, asp, axs, css, htc," +
									  " htm, html, js, jsp, php, sct, stm, wml, xml, xsl, bmp, cgm, cmx, cod, djv, djvu, drw, dxf, eshr, gif, hgs, ico, ief," +
									  " img, jfif, jpe, jpeg, jpg, odi, oti, pbm, pcx, pgl, pgm, pic, pict, png, pnm, pntg, ppm, psd, psp6, ras, rgb, sdw, svg," +
									  " svgz, tga, tif, tif6, tiff, wbmp, wpg, xbm, xpm, xwd, ai, eps, ich, ich6, iwp, pdf, ps, aac, aif, aifc, aiff, au, kar, m3u," +
									  " m4a, mid, midi, mp3, mpga, ra, ram, rm, rmi, rpm, snd, wav, wma,asf, asr, asx, avi, divx, flv, lsf, lsx, mov, movie, mp2, mp4," +
									  " mpa, mpe, mpeg, mpg, mpv2, qt, svi, wmv,cab, dmg, gtar, gz, jar, rar, sit, sqx, tar, taz, tgz, z, zip, crd, vcard, vcf, vcrd";
	public static String[] textExtensions = {"323", "asc", "bas", "c", "etx", "h", "jw", "log", "mcw", "msg", "ow", "pfs", "qa", "rtf", "sow", "text", "tsv", "tw", "txt", "uls", "vw3", "ws", "xy"};
	public static String[] documentExtensions = {"doc", "docm", "docx", "dot", "dotm", "dotx", "en4", "enw", "leg", "lwp", "lwp7", "msw", "mwp", "mwp2", "mwpf", "odc", "odg", "odt", "ort", "otg", "oth", "otm", "ott", "pages", "pcl", "rtx", "std", "stw", "sxd", "sxq", "sxw", "w6", "w97", "wm", "wp5", "wp6", "wpf"};
	public static String[] dataExtensions = {"123", "12m", "acs", "csv", "dbs", "dez", "ens", "fcd", "fcs", "mwkd", "mwks", "odf", "ods", "oss", "otf", "ots", "qad", "smd", "sms", "stc", "sxc", "sxm", "wg2", "wk4", "wk6", "xla", "xlam", "xlc", "xlm", "xls", "xlsb", "xlsm", "xlsx", "xlt", "xltm", "xltx", "xlw"};
	public static String[] presentationExtensions = {"flw", "key", "mass", "odp", "ope", "otc", "otp", "pot", "potm", "potx", "pp2", "pp97", "ppam", "pps", "ppsm", "ppsx", "ppt", "pptm", "pptx", "prz", "shw3", "sti", "sxi"};
	public static String[] pdfExtensions = {"ai", "eps", "ich", "ich6", "iwp", "pdf", "ps"};
	public static String[] flashExtensions = {"swf", "fla"};
	public static String[] codeExtensions = {"asp", "axs", "css", "htc", "htm", "html", "js", "jsp", "php", "sct", "stm", "wml", "xml", "xsl"};
	public static String[] graphicExtensions = {"bmp", "cgm", "cmx", "cod", "djv", "djvu", "drw", "dxf", "eshr", "gif", "hgs", "ico", "ief", "img", "jfif", "jpe", "jpeg", "jpg", "odi", "oti", "pbm", "pcx", "pgl", "pgm", "pic", "pict", "png", "pnm", "pntg", "ppm", "psd", "psp6", "ras", "rgb", "sdw", "svg", "svgz", "tga", "tif", "tif6", "tiff", "wbmp", "wpg", "xbm", "xpm", "xwd"};
	public static String[] audioExtensions = {"aac", "aif", "aifc", "aiff", "au", "kar", "m3u", "m4a", "mid", "midi", "mp3", "mpga", "ra", "ram", "rm", "rmi", "rpm", "snd", "wav", "wma"};
	public static String[] videoExtensions = {"asf", "asr", "asx", "avi", "divx", "flv", "lsf", "lsx", "mov", "movie", "mp2", "mp4", "mpa", "mpe", "mpeg", "mpg", "mpv2", "qt", "svi", "wmv"};
	public static String BlogsNewEntryAllowComments = "css=input[id='allowCommentsCheck'][type='checkbox']";
	public static String BlogsPublicListing = "link=Blogs Listing";
	public static String BlogsNewEntryAllowCommentsFor = "css=select[id='commentDays']";
	public static String BlogsTimeZone = "css=select[id='timeZone']";
	public static String fileUploadDirectoryName = "uploads\\";
	public static String BlogsSiteSettingsSave = "css=input[value='Save']";
	public static String BlogsNewEntryDelay = "css=#miscSettingsLabel.lotusLeft";
	public static String BlogsNewEntryHour = "css=select[title='Hours']";
	public static String BlogsNewEntryMinutes = "css=select[title='Minutes']";
	public static String BlogsNewEntryDate = "css=div[id='widget_publishDate']";
	public static String BlogsSettingsApplyCommentDefaultsToExisting = "css=input[id='applyCommentDefaults'][type='checkbox']";
	public static String BlogsEditEntry = "link=Edit";
	public static String BlogsNewEntryAdvancedSettings = "css=#miscSettingsLabel.lotusLeft";
	public static String BlogsNewEntryAdvanEmoticons = "css=input[id='Emoticons'][type='checkbox']";
	public static String BlogsEmoticonSelect = "css=input[id='Emoticons'][checked='checked']";
	public static String BlogsNewEntryAdvanPinnedToMain = "css=input[id='pinnedToMain']";
	public static String BlogsNewEntryAdvanDelayPub = "css=input[id='delayedPub'][type='checkbox']";
	public static String BlogsNewEntryButton = "xpath=//a[contains(text(),'PLACEHOLDER')]/../../..//a[text()='New Entry']";
	public static String NewIdea = "link=New Idea";
	public static String StartABlog = "xpath=//a[text()='Start a Blog']";
	public static String BlogsNameField = "css=input[id='name']";
	public static String BlogsAddressObject = "css=input[id='handle']";
	public static String BlogsTags = "css=input[id='tagsAsString']";
	public static String BlogsDescription = "css=textarea[id='description']";
	public static String BlogsTheme = "css=select[id='theme']";
	public static String blogsOption = "css=a>strong:contains(Blogs)";
	public static String blogsLatestEntries = "css=td>a:contains(Latest Entries)";
	public static String blogsPublicBlogsListing = "css=td>a:contains(Public Blogs Listing)";
	public static String BlogsCommentRecommend = "css=a[id='TOGGLE_com_ibm_oneui_controls_Like_0']";
	public static String BlogsCommentMoreActions_Delete = "css=td[id*='delete-'][role='presentation']";
	public static String BlogsCommentMoreActions = "css=a[id*='moreActions-']";
	public static String BlogsCommentEdit = "css=td[id*='edit'][role='presentation']";
	public static String BlogsCommentEditContent = "body[aria-label='Content']";
	public static String BlogsGraduate = "css=a[id='graduateIdeaButton']";
	public static String BlogsGraduateOK = "css=input[type='button'][value='OK']";
	public static String BlogsCommentDeleteOK= "css=input[type='button'][value='OK']";
	public static String BlogsMoreActions = "css=#focusMoreActionsLink";
	public static String MarkAsDuplicate = "css=#duplicateEntryLink";
	public static String DuplicateIdeaTextbox = "css=#ideasAsString";
	public static String DuplicateIdeaTypeahead = "css=#ideasAsString_popup0";
	public static String DuplicateIdeaSaveBtn = "css=#dupIdeaSaveBtn";
	public static String BlogsTagCloud = "css=div[id='lconnTagWidget_tagCloudView']";
	public static String BlogsCommentDiv = "css=div[id='blogCommentPanel']";
	public static String BlogsAnnouncement = "css=table[id='announcementBox']";
	public static String BlogsTagCloudView = "css=div[id='lconnTagWidget_tagCloudView'] ul li";
	public static String Smiley = "css=img[class='smiley']";
	public static String CloseAnnouncementBtn = "css=a[class='lotusClose'][role='button']";
	public static String BlogsSaveChangeMsg = "css=div[class='lotusMessageBody'] span span:contains(Saved changes to blog settings)";
	public static String SiteAdminSaveChangeMsg = "css=div[class='lotusMessageBody'] span span:contains(Change saved)";
	public static String BlogsTurnOffCommentMsg = "css=div[class='lotusMessageBody'] span span:contains(Turned comments off for inactive blog)";
	public static String BlogsErrorMissingNameMsg = "css=div[class='lotusMessageBody'] span span:contains(You must enter a name for the blog)";
	public static String BlogsModerateMsg = "css=div[class='lotusMessageBody'] span span:contains(Your comment has been submitted to the moderator for approval)";
	public static String BlogsCommentsDisabled = "css=a[class='disabledLink']:contains(Add a Comment)";
	public static String BlogsSubmitButton = "css=input[value='Submit']";
	public static String BlogsPagingNumbers = "css=#lotusContent.lotusContent div.lotusPaging";
	public static String BlogsCommentDisabled = "css=a[class='disabledLink'][title='Comment is disallowed for this entry']";
	public static String BlogsUIBlogTitleLink = "css=div[class*='blogsBoard'] > div[class='lotusPost lotusClear'] > div > h4 > a";
	public static String deleteEntry = "css=#deleteEntryLink_text";
	public static String deleteEntryButton = "css=a#deleteBtn";
	public static String deleteEntryOKButton = "css=.lotusFormButton.submit";
	public static String BlogEntryLink="css=div[aria-label='Entry list'] a:contains('PLACEHOLDER') ";
	public static String BlogEntry_MoreActions = "css=div[id='entries']:contains('PLACEHOLDER') > div[aria-label='Entry list'] > ul[aria-label='Entry Actions'] > li > nobr > a > img";
	public static String BlogEntry_NotifyOtherPeople = "css=td:contains('Notify Other People')";
	public static String BlogEntry_NotificationForm_NameEntryField = "css=input[id='notificationForm_typeahead']";
	public static String BlogEntry_NotificationForm_Typeahead_Menu = "css=div[id='notificationForm_typeahead_popup']";
	public static String BlogEntry_NotificationForm_Typeahead_Full_Search = "css=div[id='notificationForm_typeahead_popup_searchDir']";
	public static String BlogEntry_NotificationForm_Typeahead_MenuItem = "css=div[id*='notificationForm_typeahead_popup'][exid='PLACEHOLDER']";
	public static String BlogEntry_NotificationForm_SendButton = "css=input[name='sendBtn']";
	public static String followThisBlogBtn = "css=li[class='lotusFirst'] a[class='blogsFollowBtn']";
	public static String SettingsLink = "css=nobr a:contains(Settings)";
	public static String ReplyLink = "css=div ul li a[title='Reply to this comment']:contains(Reply)";
	public static String BlogsNewEntryFormHeader = "css=h1:contains(New Entry)";
	/** Embedded experience */
	public static String BlogsEEFrameIdentifier = "css=iframe[id^=__gadget_gadget]";
	public static String BlogsEECommentsTab = "css=a[role='tab']:contains(Comments)";
	public static String BlogsEECommentTextField = "css=div[id^='mentionstextAreaNode'][aria-label='Add a comment']";
	public static String BlogsEECommentContent = "css=div.lotusPostDetails.eeCommentContent p";
	public static String BlogsEEReadMore = "link=Read more ...";
	public static String BlogsEEShowPrevComments = "link=Show Previous Comments";
	public static String BlogsEEHiddenCommentField = "css=div[id^='com_ibm_social_ee_widget_Comments'] li[class='lotusAddComment'][style='display: none;']";
	public static String BlogsEEVoteIdeation = "css=div.lotusChunk div span a:contains('Vote')";
	public static String BlogsEERecentUpdatesTab = "css=a[role='tab']:contains(Recent Updates)";
	public static String BlogsEEUndo = "css=div.lotusChunk div span a:contains('Undo')";
	public static String BlogsEEUserPopupClose = "css=a.lotusPopupClose img";
	public static String BlogsEELike = "css=div.lotusChunk div.lotusLike span a:contains('Like')";
	public static String BlogsEEUnlike = "css=div.lotusChunk div.lotusLike span a:contains('Unlike')";
	public static String BlogsEEPopupLikeNumber = "css=div.lotusLikeText";
	public static String BlogsEELikeIcon = "css=img.lotusIconLike";
	public static String BlogsEEPopupNumLikesPopup = "css=div#com_ibm_oneui_recommend_internal_PopupContents_0";
	public static String BlogsEEPopupNumLikesPopupUser = "css=div.vcard.lotusLikeAvatarLink a";
	public static String BlogsEEPostComment = "link=Post";
	public static String BlogsEECloseFrame = "css=input[alt='Close']";
	public static String BlogEntryCancelBtn = "css=input[name='cancel']";
	public static String GoToCommunityOption = "css=#communityMenu_GOTOCOMM_text";
	public static String closeAnnouncement = "css=a[class='lotusClose'][role='button']";
	public static String BlogTimeZone = "css=span[id='timezoneStr']";
	public static String blogPostEntryID = "css=input[id='postEntryID']";
	public static String blogMsgBody = "css=span[dojoattachpoint='msgBody']";
	public static String allowedExtensionsInput = "css=tr:contains(Allowed extensions:) input";
	public static String BlogsTimezone = "css=#timezoneStr";
	public static String ideaVoteNumber = "css=div#lconn_blogs_voting_1 div[class='ideaVotingNumber']";
	public static String ideaVoteDisable = "css=#lconn_blogs_voting_1 a[class='ideaVotingButtonDisabled']";
	public static String ideaContent = "css=div[class='blogsWrapText']";
	public static String blogDeleteConfirm = "css=input[value='Delete']";
	public static String blogDeleteConfirmChkBox = "css=input[id='agreeToDeleteWebsite']";
	public static String blogDelete = "css=input[value='Delete Blog']";
	public static String contributeAnIdeaButton = "css=a[role='button'][dojoattachpoint='createIdeaLinkAP']";
	public static String ideationBlogTitle = "css=h4[id='entry_title']";
	public static String createIdeaBlogNameField = "css=div[class='lotusFieldWrapper'] input[id='name']";
	public static String createIdeaBlogDescField = "css=div[class='lotusFieldWrapper'] textarea[id='description']";
	public static String saveButton = "css=div[class='lotusFormFooter'] input[value='Save']";
	public static String ideationBlogLinks = "css=table[dojoattachpoint='tableListAP'] h4[class='lotusBreakWord']>a:contains('PLACEHOLDER')";
	public static String existingImageTabLink = "css=a[id='existingImageTabLink']";
	public static String BlogsCKEUnifyChoosePhoto = "//td[@id='uploadedImageDiv1']/img[@id='uploadedImage1']";
	public static String BlogsCKEUnifyInsertButton = "css=input[id='insertButton']";
	public static String BlogsEntryDescDOM = "css=div.entryContentContainer.blogsWrapText";
	// Bosch UAT Test Case
	public static String SaveButton = "xpath=//td[contains(@class,'lotusFormFooter')]//input[@value='Save']";
	public static String msgBody = "css=div[class*=lotusMessageBody]";
	public static String entryNameLink = "css=a[id$='link:entries']";
	public static String viewAllLinksBtn = "css=a:contains(View All Entries)";
	public static String editLink = "css=a:contains(Edit)";
	public static String commentHeadline = "css=h1:contains(Comment on this Entry)";
	public static String commentCancelBtn = "css=input[name*=cancelButton]";
	public static String HTML_Source_Tab = "css=ul#editorTab a:contains(HTML Source)";
	public static String Rich_Text_Tab = "css=ul#editorTab a:contains(Rich Text)";
	public static String HTMTTextArea = "css=textarea[title*='Rich Text Editor']";
	public static String createdBlogEntryLink = "xpath=//a[contains(text(),'PLACEHOLDER')]";
	public static String BlogsCKEInsertTableButton = "css=a[data-title='Insert Table']";
	public static String BlogsCKEClickOkButton = "css=a[title='OK']";
	public static String BlogNameHeaderText = "css=h1[class='bidiAware'],h1[role='presentation']>a";
	public static String BlogInnerTabs = "//span[@class='lotusTabInner']";
	
	// CNX8UI Blogs
	public static String blogEntryForm = "//table[@class='lotusFormTable'] //h2[contains(text(),'Start a Blog')]";
	public static String publicBlogsTab = "//div[@id='tertiary_level_nav']//span[contains(text(),'Public Blogs')]";
	public static String blogsListingNav = "//div[@aria-label='Public Blogs']//a[contains(text(),'Blogs Listing')]";
	public static String latestBlogEntryNav = "//div[@aria-label='Public Blogs']//strong[contains(text(),'Latest Blog Entries')]";
	public static String myLikesNav = "//div[@aria-label='Public Blogs']//a[contains(text(),'My Likes/Votes')]";
	public static String myUpdatesTab = "//div[@id='tertiary_level_nav']//span[contains(text(),'My Updates')]";
	public static String SelectedNavTab = "div[id='tertiary_level_nav'] li[class*='lotusSelected']";
	public static String administrationTab = "//div[@id='tertiary_level_nav']//span[contains(text(),'Administration')]";
	public static String recentEntryNav = "//div[@aria-label='My Updates']//strong[contains(text(),'Recent Entries and Comments')]";
	public static String notificationReceiveNav = "//div[@aria-label='My Updates']//a[contains(text(),'Notifications Received')]";
	public static String notificationSentNav = "//div[@aria-label='My Updates']//a[contains(text(),'Notifications Sent')]";
	public static String notificationReceivedNav = "//div[@aria-label='My Updates']//a[contains(text(),'Notifications Received')]";
	public static String configurationNav = "//div[@aria-label='Administration']//strong[contains(text(),'Configuration')]";
	public static String administerUsersNav = "//div[@aria-label='Administration']//a[contains(text(),'Administer Users')]";
	public static String blogHomepageThemeNav = "//div[@aria-label='Administration']//a[contains(text(),'Blogs Homepage Theme')]";
	public static String tagsListLink = "//div[@name='section_tags']//a[contains(text(),'List')]";
	public static String tagsCloudLink = "//div[@name='section_tags']//a[contains(text(),'Cloud')]";
	public static String listTagCount= "div[id='lconnTagWidget_tagListView'] a";
	public static String listTagName = "div[id='lconnTagWidget_tagListView'] span";
	public static String cloudTagName = "div[id='lconnTagWidget_tagCloudView'] a[title*='tag PLACEHOLDER, count']";
	public static String tagRemove = "a[title='Remove the tag PLACEHOLDER from the selected filter tags']";
	public static String tagSelection = "a[title$='selected filter tags - PLACEHOLDER']";
	public static String resultPerPage = "#resultsPerPage";
	public static String resultPerPage_10 = "#resultsPerPage option[data-value='10']";
	public static String entryListCount = "div[aria-label='Entry list'] tr";
	public static String pagination_firstPage = "ul[class='lotusInlinelist pagination'] a[class='page-first']";
	public static String pagination_prevPage = "ul[class='lotusInlinelist pagination'] a[class='prev']";
	public static String pagination_nextPage = "a[class='next']";
	public static String pagination_lastPage = "a[class='page-last']";
	public static String selectedPageNum = "span[class='active']";
	public static String pagesCount = "ul[class='lotusInlinelist pagination'] ul li";
	public static String tagInput = "input[id='lconnTagWidgetcommonTagsTypeAhead']";
	public static String tagSubmit = "input[name='submit']";
	public static String tagPopUp = "//div[@id='lconnTagWidgetcommonTagsTypeAhead_popup']//b[contains(text(),'PLACEHOLDER')]";
	public static String featuredBlogEntrySection = "div[id='lotusColRight'] [aria-label='Featured Blog Entries']";
	public static String featuredBlogEntry = "div[aria-label='Featured Blog Entries'] h4 a";
	public static String viewAllEntriesBtn = "//span[@class='lotusBtn lotusLeft']//a[contains(text(),'View All Entries')]";
	public static String selectedSortByFilter = "div[class='lotusSort'] a[aria-pressed='true']";
	public static String sortBy= "div[class='lotusSort'] a[title^='Sort by PLACEHOLDER']";
	public static String sortOrder = "div[class='lotusSort'] a[title$='Click to sort in PLACEHOLDER order.']";
	public static String heartIcon = "//h4//a[contains(text(),'PLACEHOLDER')]/ancestor::h4/following-sibling::div/span/div";
	public static String administration_settings = "//form[@name='rollerConfigForm'] //h2[contains(text(),'PLACEHOLDER')]";
	public static String entry_MoreAction = "//a[contains(text(),'More Actions')]";
	public static String entry_NotifyOtherPeople = "#focusAddNotificationLink_text";
	public static String sendEmailInput = "#notificationForm_typeahead";
	public static String blogName = "//a[contains(text(),'PLACEHOLDER')]";
	public static String notificationFormSubmitBtn = "input[name='sendBtn']";
	public static String typeAheadFullSearch = "//div[@id='notificationForm_typeahead_popup_searchDir']";
	public static String typeAheadItem = "//div[@aria-labelledby='bc_document_node']";
	public static String notificationSentCount = "div[aria-label='Notification list'] tr";
	public static String typeAhead = "//div[@id='notificationForm_typeahead_dropdown']";
	public static String typeAheadFirstEle = "//div[@id='notificationForm_typeahead_popup0']";

	private BlogsUIConstants() {}

}
