package com.ibm.conn.auto.webui.constants;

import com.ibm.conn.auto.appobjects.library.FileThumbnailWidget;
import com.ibm.conn.auto.appobjects.library.FolderThumbnailWidget;

public final class CommunitiesUIConstants {

	/** Create a Community selectors */
	public static String CommunitiesLink = "css=h2.lotusHeading span.lotusText a:contains(Communities)";
	public static String communityNameLink = "xpath=//div[@aria-label='PLACEHOLDER']//a[contains(text(),'PLACEHOLDER')]";
	public static String OwnerCommunitiesView = "css=span[data-value='/ownedcommunities']";
	public static String MemberCommunitiesView = "css=div ul li a[href$='/communities/service/html/mycommunities']";
	public static String PublicCommunitiesView = "css=div ul li a[href$='/communities/service/html/allcommunities']";
	public static String StartACommunity = "css=div span a[href$='/communities/service/html/communitycreate']";
	public static String StartACommunityDropDown = "css=div#lconn-create-community-container";
	public static String StartACommunityFromDropDown = "css=li[title='Create a New Community']";
	// [6.0 CR4] "Create a Community" drop-down button in Catalog Card View
	public static String StartACommunityDropDownCardView = "css=.icCatalogCommunityCreate";
	public static String StartACommunityFromDropDownCardView = "css=.icCatalogCommunityCreate li ul li:nth-child(1) a";
	public static String StartACommunityFromCopyExistingCardView = "css=.icCatalogCommunityCreate li ul li:nth-child(2) a";
	public static String CommunityName = "css=*[id='addCommunityName']";
	public static String ListRestrictedCommunity = "css=input[id='listRestrictedCom']";
	public static String ListRestrictedSubCommunity = "css=tr[id='addListRestrictedRow'] input[id='addListRestrictedCom']";
	public static String AccessRequired = "css=label[id='privacy'] span.lotusFormRequired";
	public static String CommunityHandle = "css=input[id='autocompletehandle']";
	public static String CommunityTag = "css=tbody tr td input[id='autocompletetags']";
	public static String SubCommunityTag = "css=tbody tr td input[id='addCommunityTags']";
	public static String CommunityAccessPublic = "//*[@id='addPublicAccess']";
	public static String CommunityAccessModerated = "//*[@id='addPublicInviteOnlyAccess']";
	public static String CommunityAccessPrivate = "//*[@id='addPrivateAccess']";
	public static String CommunityallowExternalBox = "css=input[id='allowExternal']";
	public static String SubCommunityAccessPublic = "//*[@id='addPublicAccess']|//*[@id='addPublicAccessCtl']";
	public static String SubCommunityAccessModerated = "//*[@id='addPublicInviteOnlyAccess']|//*[@id='addSubPublicInviteOnlyAccess']";
	public static String SubCommunityAccessPrivate = "//*[@id='addPrivateAccess']|//*[@id='addSubPrivateAccess']";
	public static String CloseWidget = "css=div a[id='closePalette']";
	public static String publicCommunities = "css=a[title='View/Refresh My Organization communities']";
	public static String leftNavOverview = "link=Overview";
	public static String leftNavOverviewLink = "css=ul[id='lotusNavBar'] li[widgetdefid='Overview']";
	public static String leftNavMembers = "link=Members";
	public static String leftNavUpdates = "link=Updates";
	public static String leftNavForums = "link=Forums";
	public static String leftNavBookmarks = "link=Bookmarks";
	public static String leftNavFiles = "link=Files";
	public static String leftNavFeeds = "link=Feeds";
	public static String leftNavBlogs = "link=Blog";
	public static String leftNavIdeationBlogs = "link=Ideation Blog";
	public static String leftNavMediaGallery = "link=Media Gallery";
	public static String leftNavWikis = "link=Wiki";
	public static String leftNavActivities = "link=Activities";
	public static String leftNavRecentUpdates ="link=Recent Updates";
	public static String leftNavSurveys = "link=Surveys";
	public static String show100Comm = "css=a[role='button']:contains(100)";
	// [6.0 CR4] top-nav menu buttons
	public static String topNavMyCommunitiesCardView = "css=div#lconn-nav-tabs-container nav ul li:nth-child(1) a";
	public static String topNavDiscoverCardView = "css=div#lconn-nav-tabs-container nav ul li:nth-child(2) a";
	public static String topNavInvitedCardView = "css=div#lconn-nav-tabs-container nav ul li:nth-child(3) a";
	public static String getCommunityTitles = "css=div[class^='community-card-grid'] div[id^='community-card'] div[class='card-title'] p";
	public static String getCommunityLabels = "css=div[class^='community-card-grid'] div[id^='community-card']";
	// [6.0 CR4] View Selector drop-down menu
	public static String viewSelectorDropDownCardView = "css=div#view-select-container div[role='button']"; // expand/collapse drop-down
	public static String viewSelectorDropDownCardViewNameAscending = "css=div.bx--list-box__menu [data-value='name-ascending']"; // both
	public static String viewSelectorDropDownCardViewNameDescending = "css=div.bx--list-box__menu [data-value='name-descending']"; // both
	public static String viewSelectorDropDownCardViewNumMembers = "css=div.bx--list-box__menu [data-value='members']"; // if "Trending" unavailable
	public static String viewSelectorDropDownCardViewRecentlyUpdated = "//div[@class='bx--list-box__menu']//a[@title='Recently Updated']//span[contains(text(),'Recently Updated')]"; // "My Communities"
	public static String viewSelectorDropDownCardViewRecentlyVisited = "css=div.bx--list-box__menu [data-value='recently-visited']"; // "My Communities"
	public static String viewSelectorDropDownCardViewSuggested = "css=div.bx--list-box__menu [data-value='suggested']"; // "Discover"
	public static String viewSelectorDropDownCardViewTrash = "css=div.bx--list-box__menu [data-value='trash']"; // "My Communities"
	public static String viewSelectorDropDownCardViewTrashMT = "css=div.bx--list-box__menu [data-value='/trashedcommunities']"; // "My Communities"
	public static String viewSelectorDropDownCardViewTrending = "css=div.bx--list-box__menu [data-value='trending']"; // "My Communities"
	public static String viewSelectorDropDownCardViewTrendingCompany = "css=div.bx--list-box__menu [data-value='trendingcompany']"; // "Discover"
	public static String viewSelectorDropDownCardViewTrendingNetwork = "css=div.bx--list-box__menu [data-value='trendingnetwork']"; // "Discover"
	// [6.0 CR4] Filter side-bar
	public static String filterSideBarNotExpanded = "css=div.filter-refiner:not(.expanded)";
	public static String filterSideBar = "css=div.filter-refiner";
	public static String filterSideBarExpandCardView = "css=div.filter-refiner button";
	public static String filterSideBarOwnerCardView = "css=ul.primary-filters li:nth-child(1) a";
	public static String filterSideBarOwnerCardViewSelected = "css=ul.primary-filters li:nth-child(1) .primary-filter-tag--selected";
	public static String filterSideBarMemberCardView = "css=ul.primary-filters li:nth-child(2) a";
	public static String filterSideBarMemberCardViewSelected = "css=ul.primary-filters li:nth-child(2) .primary-filter-tag--selected";
	public static String filterSideBarFollowingCardView = "css=ul.primary-filters li:nth-child(3) a";
	public static String filterSideBarFollowingCardViewSelected = "css=ul.primary-filters li:nth-child(3) .primary-filter-tag--selected";
	public static String filterSideBarCreatedCardView = "css=ul.primary-filters li:nth-child(4) a";
	public static String filterSideBarCreatedCardViewSelected = "css=ul.primary-filters li:nth-child(4) .primary-filter-tag--selected";
	public static String leftNavPublicCommunities = "css=a[id='toolbar_catalog_menu_allcommunities']";
	public static String leftNavStatusUpdates = "css=a:contains(Status Updates)";
	public static String leftNavOverviewButton = "css=li[id='dropdownNavMenuTitleLink'] a div[id='dropdownNavMenuSelection']";
	public static String leftNavSubcommunitiesButton ="css=li[id='dropdownSubMenuTitleLink'] a div[id='dropdownSubMenuSelection']";
	public static String SearchTextArea = "css=input[id='dijit_form_TextBox_0'][title='Search This Community'][id='dijit_form_TextBox_0']";
	public static String SearchButton = "css=#lconn_search_searchPanel_SearchBar_0 > a:nth-child(3) > svg:nth-child(1)";
	public static String SearchResults =  "css=h4 span[id^='lconn_communities_catalog_widgets_PlaceDisplayWidget'] a";
	public static String SearchResultsTable = "css=table[dojoattachpoint='resultsTable']:nth(0)";
	public static String CalendarSearchTab = "css=ul#searchPageTabContanierId li:contains(Events)";
	public static String commSearchResultsPageTabs="css=div[class='lotusTabContainer'] ul li[id$='_TabItem'] a";
	public static String commDeleteName = "css=input[id='communityInputField']";
	public static String commDeleteUser = "css=input[id='signature']";
	public static String commDeleteButton ="css=button[class='lotusBtn']:contains(OK)";
	public static String CommunityThemeLink = "css=#themeLinkButton";
	public static String CommunityThemeLinkHidden =("css=tr[id='themeSelection'][style='display:none']");
	public static String ThemeDefault = "css=#defaultCtlAddComm";
	public static String ThemeRed = "css=#redCtlAddComm";
	public static String ThemeGreen = "css=#greenCtlAddComm";
	public static String ThemeCoffee = "css=#goldCtlAddComm";
	public static String ThemeSilver = "css=#silverCtlAddComm";
	public static String ThemeBlue = "css=#blueCtlAddComm";
	public static String ThemePink = "css=#pinkCtlAddComm";
	public static String ThemeOnyx = "css=#onyxCtlAddComm";
	public static String ThemePurple = "css=#purpleCtlAddComm";
	public static String ThemeOrange = "css=#orangeCtlAddComm";
	public static String MenuItem_My_Communities = "css=a[id='toolbar_catalog_menu_mycommunities']";
	public static String CommunityMemebersPageNewMembersSaveButton = "css=input[value='Save'][onclick*='saveMemberFields']";
	public static String CommunityMembersDropdown = "css=select[id^='addMembersSelectBox']";
	public static String CommunityMembersOptionVisitorModel = "css=input[id^='vmAddType']";
	public static String AddMembersToExistingTypeAhead = "//input[@id='addComMembersWidgetPeopleTypeAhead'] | //input[@id='addMembersWidgetPeopleTypeAhead']";
	public static String AddMembersToExistingTypeAheadVisitorModel = "css=input[id^='vmAddMembersWidgetPeopleTypeAhead']";
	public static String AddMembersToExistingTypeAheadWithoutCom = "//input[@id='addComMembersWidgetPeopleTypeAhead'] | //input[@id='addMembersWidgetPeopleTypeAhead']|//input[@id='bhc_lconn_core_PeopleTypeAhead']";
	public static String fullSearchLink = "Person not listed? Use full search...";
	public static String fullUserSearchIdentifier1 = "css=*[id='addMembersWidgetPeopleTypeAhead_popup'] *[dojoattachpoint='searchButton']";
	public static String Add_To_ExistingMembers_Textfield_Typeahead = "css=*[id='addComMembersWidgetPeopleTypeAhead_popup'] li:nth-child(2)";
	public static String Add_To_ExistingMembers_Textfield_TypeaheadWithoutCom = "css=*[id='addMembersWidgetPeopleTypeAhead_popup'] li:nth-child(2)";
	public static String AddMembersToExistingCommunity = "link=Add Members";
	public static String AddMembersToExistingCommunityVistorModel = "link=Invite or Add Members";
	public static String RemoveMemberCommunity = "link=Remove";
	public static String InviteMemberButton = "css=a#memberInviteButtonLink";
	public static String InviteMembersToExistingTypeAhead = "css=input[id='inviteMembersWidgetPeopleTypeAhead']";
	public static String Invite_To_ExistingMembers_Textfield_TypeaheadWithoutCom = "css=*[id='inviteMembersWidgetPeopleTypeAhead_popup'] li:nth-child(2)";
	public static String fullInvitedUserSearchIdentifier = "css=*[id='inviteMembersWidgetPeopleTypeAhead_popup'] *[dojoattachpoint='searchButton']";
	public static String InviteSelectUsers = "css=div[id*='inviteMembersWidgetPeopleTypeAhead_popup']";
	public static String SendInvitesButton = "css=input[value='Send Invitations'][class='lotusFormButton']";
	public static String acceptInviteConfirmationMsg = "css=div[class=lotusMessageBody] span:contains(Thanks for joining)";
	public static String addMember_Typeahead_SelectUser ="css=div[id='addMembersWidgetPeopleTypeAhead_popup0']";
	public static String addExMemBtn = "css=#communitiesAddButton";
	public static String addExtMemBtnHidden = "css=#communitiesAddButton style:contains(none)";
	public static String CommunitiesHelp = "css=a#headerHelpLink";
	public static String HelpFrame = "Help -";
	public static String CommunitiesHelpFrame = "Communities";
	public static String scHelpFrame = "IBM SmartCloud for Social Business";
	public static String HelpPageTitle = "css=h1[class$='title topictitle1 welcomePage']";
	public static String AddBookmarkButton = "css=#addBookmarkBtn";
	public static String EnterBookmarkURL = "css=#addBookmarkUrl";
	public static String EditBookmarkURL = "css=*[id^='editBookmarkUrl']";
	public static String EnterBookmarkName = "css=#addBookmarkName";
	public static String EditBookmarkName = "css=*[id^='editBookmarkName']";
	public static String EnterBookmarkDescription = "css=#addBookmarkDescription";
	public static String EditBookmarkDescription = "css=*[id^='editBookmarkDescription']";
	public static String EnterBookmarkTag = "css=#autocompletetags2";
	public static String EditBookmarkTag = "css=#autocompletetags2";
	public static String AddAsImportant = "css=input[name='homepage']";
	public static String EditAddAsImportant = "css=#homepage.noSpacing";
	public static String ImportantBookmarks = "css=a.action";
	public static String OverviewBookmarksLink = "css=table#bookmarksTableContainer.lotusTable tbody tr td h4 a";
	public static String MoreLink = "//a[contains(text(),'More')]";
	public static String optionsInMoreDropdownMenu ="css=[aria-label='CommunitiesMoreMenu'] td";
	public static String BookmarksEditLink = "css=li.lotusFirst > a.lotusAction";
	public static String firstBookmarksMoreLink = "css=a[class='lotusAction commFocusMR']:contains(More)";
	public static String leftNavBookmarksLink = "css=ul[id='lotusNavBar'] li[widgetdefid='Bookmarks']";
	public static String EditLink = "css=tbody tr td a:contains('Edit')";
	public static String TopicsLink = "css= div ul li a:contains(Topics)";
	public static String StartATopicLink = "link=Start a Topic";
	public static String TopicTitle = "css=input[id$='postTitle']";
	public static String TopicTag = "css=input[id$='postTag']";
	public static String SCPostTitle = "css=h1 span.entry-title";
	public static String Start_A_Topic_InputCheckbox_MarkAsQuestion = "css=input#lconn_forums_PostForm_0_postQestionMark";
	public static String PostTitle = "css=h1 span.forumPostTitle";
	public static String AddAFeed = "css=a.lotusAction:contains('Add Your First Feed')";
	public static String TestFeedURL = "communities/service/atom/communities/my";
	public static String WidgetFeeds = "link=Feeds";
	public static String WidgetSectionClose = "css=#closePalette img";
	public static String SaveButton = "css=input[id='addCommunityButton']";
	public static String CancelButton = "css=input[id='addCommmunityCancelBtn']";
	public static String SubCommunityCancelButton = "css=input[id='addSubcommunityCancelBtn']";
	public static String inviteCancelButton = "css=div#wai_memberInviteFormDiv input.lotusFormButton[value='Cancel']";
	public static String SaveButton2 = "css=input.lotusFormButton";
	public static String SaveButton3 = "css=div.lotusFormFooter span input.lotusFormButton";
	public static String SaveButtonEntry = "css=input[value='Save'][class='lotusFormButton']";
	public static String SaveSubCommunity = "//input[@id='addCommunityButton']";
	public static String FormButton = "css=input.lotusFormButton";
	public static String OKButton = "css=input[value='OK'][class='lotusFormButton'][type='submit']";
	public static String DeleteButton = "css=input[value='Delete'][class='lotusFormButton'][type='submit'], input[value='OK'][class='lotusFormButton'][type='submit']";
	public static String OKTypeButton = "css=input[value='OK'][class='lotusFormButton'][type='button']";
	public static String RevokeInviteOK = "css=input[value='OK'][class='lotusFormButton submit'][type='button']";
	public static String CancelLink = "css=*[title='Cancel']";
	public static String EditSaveButton = "css=input[value='Save'][type='submit'][name='submit']";
	public static String EditSaveButton1 = "//table[3]/tbody/tr/td/input";
	public static String EditMemberDialogSaveButton = "css=input[class='lotusFormButton submit'][value='Save']";
	public static String MediaGalleryWidgetDropdown = "css=h2.ibmDndDragHandle a";
	public static String MediaGalleryUploadLink = "css=a[title='Upload a photo or a video'] img";
	public static String MediaGalleryUploadPhoto = "css=div[id^='popup'] table tr:nth(0)";
	public static String MediaGalleryUploadVideo = "css=div[id^='popup'] table tr:nth(1)";
	public static String MediaGalleryViewAllLink = "css=div a.lotusAction.qkrViewAll";
	public static String MediaGalleryViewCount = "css=span[dojoattachpoint='pagingHeader']";
	public static String MediaGalleryFileUploadFilePath = "css=input.qkrFile";
	public static String MediaGalleryFileUploadFilename = "name=_label";
	public static String MediaGalleryFileUploadTags = "name=uploadFileTaggerTypeAhead";
	public static String MediaGalleryFileUploadDescription = "name=_description";
	public static String MediaGalleryFileUploadDescriptionIE = "//textarea[contains(@id,'qkrLW_label_')]";
	public static String MediaGalleryAboutThisFileTab = "css=div ul li a:contains(About this File)";
	public static String UploadPhoto = "css=a[aria-label='Upload Photo']";
	public static String MainPageContent = "css=div.lotusContent[role=\"main\"]";
	public static String CommunitiesFullpageWidgetContainer = "css=#widget-container-fullpage";
	public static String LibraryWidgetRoot = "css=div.qkrLibraryWidget";
	public static String LibraryDocMain = "css=div.qkrMain";
	public static String LibraryDocSummary = "css=div.qkrDocSummary";
	public static String LibraryTitle = "css=div.lotusHeader > h1.lotusHeading";
	public static String LibraryBreadcrumbs = "css=div.lotusBreadcrumbs";
	public static String LibraryBreadcrumbLibraryWithNameSuffix = "link=";
	public static String LibraryBreadcrumbBackToLibraryWithNameSuffix = "link=Back to ";
	public static String LibraryViewSelector = "css=.lotusViewControl";
	public static String LibraryGridViewSelectorLinkOff = "css=a.lotusView.lotusTileOff";
	public static String LibraryGridViewSelectorLinkOn = "css=a.lotusView.lotusTileOn";
	public static String LibraryDetailsViewSelectorLinkOff = "css=a.lotusView.lotusDetailsOff";
	public static String LibraryDetailsViewSelectorLinkOn = "css=a.lotusView.lotusDetailsOn";
	public static String LibrarySummaryViewSelectorLinkOff = "css=a.lotusView.lotusSummaryOff";
	public static String LibrarySummaryViewSelectorLinkOn = "css=a.lotusView.lotusSummaryOn";
	public static String LibrarySortArea = "css=div.sortArea";
	public static String LibrarySortKeyNameLinkByText = "link=Name";
	public static String LibrarySortKeyUpdatedLinkByText = "link=Updated";
	public static String LibrarySortKeyDownloadsLinkByText = "link=Downloads";
	public static String LibrarySortKeyCommentsLinkByText = "link=Comments";
	public static String LibrarySortKeyLikesLinkByText = "link=Likes";
	public static String LibraryTableBody = "css=div.qkrLibraryTable table.lotusTable > tbody";
	public static String LibraryCommunityMembers = "css=*[title='Community Members']";
	public static String LibraryCommunityOwners = "css=*[title='Community Owners']";
	public static String LibraryEveryoneInMyOrg = "Everyone in My Organization (public)";
	public static String LibraryFileSharingTab = "css=div[class='lotusTabContainer'] ul[class='lotusTabs'] li[class=''] a:contains(Sharing)";
	public static String LibraryPeopleTypeAheadDropDown = "css=div[class='dijitPopup dijitComboBoxMenuPopup']";
	public static String LibraryPeopleTypeAheadTextField = "css=input[id^='quickr_lw_widget_PeopleTypeAhead']";
	public static String LibraryShareButton = "css=*[title='Share this library']";
	public static String LibrarySharingTab = "css=li[class='lotusSelected'] a:contains(Sharing)";
	public static String LibraryFolderShareButton = "css=*[title='Share this folder']";
	public static String LibraryFileMoreActions = "css=*[id^='quickr_lw_widget_DropDownButton']";
	public static String LibraryFileShareMenuItem = "css=*[title='Share this file']";
	public static String editCommunityLibraryTab = "css=*[title='Library']";
	public static String LibraryChangeSharingOnLink = "css=a:contains(Change sharing on)";
	public static String LibraryResetToDefaultSharing = "css=a:contains(Reset to default sharing)";
	public static String ThumbnailWidgetByClass = "css=div.ic-thumb-widget-flip-card";
	public static String FolderThumbnailWidgetsByPartialId = "css=div[id*='" + FolderThumbnailWidget.idPrefix + "']";
	public static String FileThumbnailWidgetsByPartialId = "css=div[id*='" + FileThumbnailWidget.idPrefix + "']";
	public static String ThumbnailWidgetWithIdSuffix = "css=div#";
	public static String ThumbnailWidgetFrontName = "css=div.card-front > div.summary > span.text";
	public static String ThumbnailWidgetDownloadLink = "css=div.actions > a[title=\"Download\"]";
	public static String ThumbnailWidgetPreviewLink = "css=div.actions > a[title=\"Preview\"]";
	public static String ThumbnailWidgetSummaryLink = "css=div.actions > a[title=\"View file details\"]";
	public static String ThumbnailWidgetBackSideLink = "css=div.card-back";
	public static String LibraryAddTags = "link=Add Tags";
	public static String LibraryDownload = "css=a[aria-label='Download']";
	public static String LibraryNewVersion = "css=a[aria-label='Upload New Version']";
	public static String LibraryCheckOut = "css=a[aria-label='Check Out']";
	public static String LibraryMoreActions = "css=.lotusActions.lotusInlinelist>li>a:contains(More Actions)";
	public static String LibraryViewTrash = "link=View Trash";
	public static String UploadedFileNameInView = "css=td h4 a:contains";
	public static String LibraryDocSummaryFileTitleWithTextSuffix ="css=.qkrFileSummaryTitle:contains";
	public static String LibraryMoreLink = "css=#expandLink_";
	public static String LibraryAddTagsTextfield = "css=input[title='Tags:']";
	public static String LibraryAddRemoveTags = "css=tbody tr td div a[title='Add or remove tags on this file']";
	public static String LibraryMoreActionOption = "css=tbody[class='dijitReset'] tr";
	public static String UploadNewVerionLink = "css=ul li a[aria-label='Upload New Version']";
	public static String FileUploadBrowse = "css=input[id^='qkrLW_label_']";
	public static String UploadAFileButton = "css=span.lotusBtn a[aria-label='Upload Files']";
	public static String NewFolderButton = "css=span.lotusBtn a[aria-label='New Folder']";
	public static String LibraryFileInputField = "css=input[type='file'][id^='qkrLW_label_']";
	public static String CheckInButton = "css=input[type='submit'][value='Check In']";
	public static String LibraryFileInput = "css=input[type='file'][id^='qkrLW_label_']";
	public static String ShareLink = "css=li#headerSharebox.shareboxLi a.lotusBannerBtn";
	public static String ShareBoxStatusFrameIdentifer = "css=iframe[id^='__gadget'][title='Status update Section']";
	public static String ShareBoxPostType = "css=select#postType";
	public static String ShareBoxTextArea = "css=[id^='mentionstextAreaNode']";
	public static String ShareBoxAddAFile = "css=div ul.lotusInlinelist li.lotusFirst a:contains(Add a File)";
	public static String ShareBoxPost = "css=input[value='Post']";
	public static String ShareBoxCancel = "css=input[value='Cancel']";
	public static String ShareBoxFilesTab = "css=span[id*='sharebox']:contains('Files')";
	public static String ShareBoxFilesLabel = "css=td.lotusFormLabel > span:contains(Files)";
	public static String ShareBoxFileFrameIdentifer = "css=iframe[id^='__gadget'][title='Files']";
	public static String ShareBoxFileInput = "css=input[id$='_contents_contents'][type='file']";
	public static String ShareBoxCommunityPickerTextBox = "css=input[id='commPicker']";
	public static String ShareBoxCommunityPickerPopup = "css=#commPicker_popup0";
	public static String ShareBoxComment_iFrame = "css=iframe.cke_wysiwyg_frame[title='Add a comment']";
	public static String Join_the_Community = "css=#joinDisplayActionsBtn";
	public static String SendJoinRequest_Btn = "css=#submit";
	public static String Moderation_Blogs="css=div[widgetid='lconn_moderation_scenes__NavigationTreeNode_1'] span:contains(Blogs)";
	public static String Moderation_Files="css=div[widgetid='lconn_moderation_scenes__NavigationTreeNode_1'] span:contains(Files)";
	public static String Moderation_Forums = "css=div[widgetid='lconn_moderation_scenes__NavigationTreeNode_1'] span:contains(Forums)";
	public static String Moderation_Blogs_Entries = "css=div[widgetid='lconn_moderation_scenes__NavigationTreeNode_1'] span:contains(Entries)";
	public static String Moderation_Files_Content = "css=div[widgetid='lconn_moderation_scenes__NavigationTreeNode_1'] span:contains(Content)";
	public static String Moderation_Forums_Posts = "css=div[widgetid='lconn_moderation_scenes__NavigationTreeNode_1'] span:contains(Posts)";
	public static String ContentApproval_Checkbox = "css=input[id='contentApproval']";
	public static String ContentApproval="css=span span:contains(Content Approval)";
	public static String SelectAllEntries = "css=input#selectall_cbx";
	public static String Approve = "css=button.lotusBtn:contains('Approve')";
	public static String Ideation_NewIdea = "link=New Idea";
	public static String Ideation_ContributeAnIdea = "css=a:contains(Contribute an Idea)";
	public static String IdeasTab = "css=div[id='ideatoins_main'] div a:contains(Ideas)";
	public static String NewIdea_Title = "css=input[id='title']";
	public static String NewIdea_TagLink = "css=a[title='Add Tags']";
	public static String NewIdea_Tag = "css=input[id='addtagwidgetAddTagsTypeAhead']";
	public static String NewIdea_TagSave = "css=input[value='OK']";
	public static String okButton = "css=input[value='OK']";
	public static String NewIdea_Save = "css=input#postEntryID";
	public static String createActivButton = "css=div[id='startActivity'] span[class='lotusBtn'] a:contains(Create Your First Activity)";
	public static String createActivDesc = "css=p[id='widgetDescription']:contains(Community activities can)";
	public static String newActivValidation = "css=div[class='lotusContent'][role='main'][aria-label='Start New Activity']";
	public static String createCommunityActivityButton = "css=div[id='startActivity'] span[class='lotusAction'] a:contains(Create Your First Activity)";
	public static String MyBlogsTab = "css=span[class='lotusTabInner']:contains(My Blogs)";
	public static String PublicBlogsTab = "css=span[class='lotusTabInner']:contains(Public Blogs)";
	public static String MyUpdatesBlogsTab = "css=span[class='lotusTabInner']:contains(My Updates)";
	public static String BlogsNewEntryButton = "css=a[role='button']:contains(New Entry)";
	public static String BlogsEntryTitle = "css=div[class='lotusContent'][role='main'] h1:contains(New Entry)";
	public static String BlogsComment_iFrame = "css=iframe[class^='cke_wysiwyg_frame']";
	public static String BlogsComment_Body = "css=body[class^='cke_editable']";
	public static String BlogsComment_Submit = "css=input[value='Submit'][name='submitButton']";
	public static String CommActivityActionsMenu = "ul.lotusActions li a:contains(Activity Actions)";
	public static String CommActivityActionsMenu_MoveActivity = "div.dijitPopup td.dijitMenuItemLabel:contains(Move Activity)";
	public static String CommActivity_moveActivity_selectAll = "div.lotusDialog form input#selectAllCommunities";
	public static String CommActivity_moveActivity_OkButton = "div.lotusDialog div.lotusDialogFooter span input.lotusFormButton[value='OK']";
	public static String CommunityNameLink = "a#communityName";
	public static String mainCommunityLinkFromSubcommunity = "css=div.lotusPlaceBar a.comNavInline";
	public static String CommunityMembersViewAll = "div#membersdiv a.lotusAction";
	public static String RejectBlog = "css=button.lotusBtn:contains('Reject')";
	public static String SelectAllEntries1 = "css=#selectall_cbx";
	public static String ModerationFlag = "link=Flag as Inappropriate";
	public static String ModerationConfirmFlag = "css=.lotusDialog .lotusDialogFooter .lotusFormButton[value='Flag']";
	public static String ModerationFlagContent = "link=Flag Content";
	public static String ModerationQuarantineFlag = "css=#lconn_moderation_action_forumspostsactions_1";
	public static String ModerationConfirmQuarantineFlag = "css=.lotusFormButton[value='OK']";
	public static String ModerationQuarantined = "link=Quarantined";
	public static String ModerationQuarantinedDelete = "css=.lotusBtn:contains('Delete')";
	public static String ModerationQuarantinedDeleteConfirm = "css=.lotusFormButton[value='OK']";
	public static String Moderation_Forums_PostsFC = "css=a[href*='fc/forums/posts']";
	public static String visitorFilesLink = "css=li[id='lotusBannerFilesExternal']";
	public static String EditCommunity = "css=#communityMenu_EDITURL_text";
	public static String ModerateApproveOption = "css=#contentApproval";
	public static String ModerationRejectField = "css=#lconn_share_widget_Dialog_0_reason";
	public static String ModerationRejectOK = "css=.lotusFormButton[value='OK']";
	public static String ModerationRejectForumField = "css=#lconn_forums_FlagInappropriate_0_deleteReason";
	public static String ModerationRejectForumFlag = "css=.submit[value='Flag']";
	public static String ModerationFilesMoreActions = "css=.lotusBtn[title='More Actions']";
	public static String ModerationFilesFlagInAppropriate = "css=#lconn_files_action_flagdialogaction_0_text";
	public static String ModerationFlagButton = "css=.lotusFormButton[value='Flag']";
	public static String ModerationFilesFlagContent = "css=div[widgetid='lconn_moderation_scenes__NavigationTreeNode_14'] span:contains(Content)";
	public static String ModerationFilesQuarantineFlag = "css=#lconn_moderation_action_filesactions_1";
	public static String MemberResultsContainer = "css=div[id$='MembersWidgetPeopleTypeAhead_dropdown']";
	public static String MemberSelectUserSearch = "css=li[id$='MembersWidgetPeopleTypeAhead_popup_searchDir'], div[id='addComMembersWidgetPeopleTypeAhead_popup_searchDir'], "
			+ "div[id='addMembersWidgetPeopleTypeAhead_popup_searchDir'], div[id='inviteMembersWidgetPeopleTypeAhead_popup_searchDir'], div[id='vmAddMembersWidgetPeopleTypeAhead_popup_searchDir']";
	public static String NoResultFoundFor = "css=div[id='addMembersWidgetPeopleTypeAhead_popup_resultsNode'], div[id='vmAddMembersWidgetPeopleTypeAhead_popup_resultsNode'], div[id='addComMembersWidgetPeopleTypeAhead_popup_resultsNode']";
	public static String MemberSelectUsers = "css=div[id^='addComMembersWidgetPeopleTypeAhead_popup'][class^='dijitMenuItem'], div[id^='addMembersWidgetPeopleTypeAhead_popup'][class^='dijitMenuItem'], div[id^='inviteMembersWidgetPeopleTypeAhead_popup'][class^='dijitMenuItem']";
	public static String MemberUserInputField = "input[id$='MembersWidgetPeopleTypeAhead']";
	public static String MemberSaveButton = "css=input[value='Save']";
	public static String MemberCancelButton = "css=input[value='Cancel']";
	public static String membersWidgetViewAllLink = "css=div[id='membersdiv'] span table tbody tr td[class='lotusLeft'] span a[title='All Members']";
	public static String InviteUserInputField ="input#inviteMembersWidgetPeopleTypeAhead";
	public static String InviteUserNoResultFoundFor ="css=div[id='inviteMembersWidgetPeopleTypeAhead_popup_resultsNode']";
	public static String rightsideGalleryWidget = "css=h2[class='ibmDndDragHandle']>span:contains(Gallery), span.ibmDndDragHandle:contains(Gallery)";
	public static String subCommunitiesWidgetTitle = "css=h2[class='ibmDndDragHandle']>span:contains(Subcommunities), span.ibmDndDragHandle:contains(Subcommunities)";
	public static String surveysSummaryWidget = "//span[contains(text(),'Surveys')]//ancestor::h2//parent::div";
	public static String featuredSummarySurveyWidget = "//span[contains(text(),'Featured Survey')]//ancestor::h2//parent::div";
	public static String richContentWidgetTitle = "css=h2[class='ibmDndDragHandle']>span:contains(Rich Content), span.ibmDndDragHandle:contains(Rich Content), div:contains(Rich Content)";
	public static String richContentWidgetTitleTE = "//div[contains(text(),'Rich Content')] | //span[@class='ibmDndDragHandle'][text()='Rich Content']";
	public static String featuredSurveyWidgetTitle = "css=span.ibmDndDragHandle:contains(Featured Survey)";
	public static String communitiesStatusPostPage = "css=div[id='widget-container-col2statusposts']";
	public static String leftnavbar = "css=#lotusNavBar > li > a";
	public static String leftnavbutton = "css=a#dropdownNavMenuTitleLinkAnc";
	public static String sendEmailLink = "css=li.lotusFirst a.email";
	public static String userLinkOnMembersPage = "css=span[class='vcard'] a:contains(PLACEHOLDER)";
	public static String editMemberLink = "css=a[id='edit_REPLACE_THIS']";
	public static String catalogViewSortByDateTab = "css=a[id='sort_button_1']:contains(Date)";
	//This selector is meant for both Edit community/SubCommunity page
	public static String editCommunityStartPageDropDown = "css=select[id$='tartPage']";
	public static String editCommunitySaveButton = "css=input[name='communityEditSubmit']";
	public static String contentEnabledWidgets = "css=div[id='col2DropZone'] div[class='lotusWidget2 dojoDndItem']";
	public static String rightColumnWidgets = "css=div[id='col3DropZone'] div[class='lotusWidget2 dojoDndItem']" ;
	public static String leftColumnWidgets = "css=div[id='col1DropZone'] div[class='lotusWidget2 dojoDndItem']";
	public static String bannerAreaWidgets = "css=div[id='bannerDropZone'] div[class='lotusWidget2 dojoDndItem']";
	public static String helpMenu = "css=a[id='bsscom-helpMenu_btn']";
	public static String helpItem = "css=td a[id='svcHelp']";
	public static String helpWindowTitle = "IBM SmartCloud for Social Business";
	public static String WidgetHideButton = "css=input[class='lotusFormButton submit'][value='Hide']";
	public static String WidgetNameInput = "css=input[id='communityInputField']";
	public static String SignatureInput ="css=input[id='signature']";
	public static String OkButtonOnRemoveWidget ="xpath=//button[@class='lotusBtn'][text()='OK']";
	public static String OkButtonOnRemoveWidgetWithoutSignature="css=input[class='lotusFormButton submit']";
	public static String RemoveMemberLink = "css=a[role='button'][title='Remove']";
	public static String RemoveMembersOKBtn = "css=.submit";
	public static String setupGalleryLink = "css=a.gallerySetupLink";
	public static String filePickerStream = "css=div[widgetid^='lconn_share_widget_Stream']";
	public static String filePickerAllFiles = "css=div[id^='lconn_share_widget_Node']:contains(All Community Files)";
	public static String filePickerOkButton = "css=div.lotusDialogFooter > input.lotusFormButton";
	public static String WidgetHelpPageTitle = "css=h1[class='title topictitle1']";
	public static String widgetChangeTitleInput = "css=div[class='lotusDialogContent'] span input[class^='lotusText']";
	public static String widgetChangeTitleSaveButton = "css=div[class='lotusDialogFooter'] input[class='lotusFormButton submit']";
	public static String widgetChangeTitleDialog = "css=h1.lotusHeading span[class='title']";
	public static String comAdvancedLink = "css=a[id='advancedLinkButton']";
	public static String TrashLink = "css=#toolbar_catalog_menu_trashedcommunities";
	public static String RestoreCommunityFromTrash = "link=Restore";
	public static String MessageAfterCommunityRestore = "css=span[data-dojo-attach-point='msgBody'] > div";
	public static String MessageAfterCommunityCardRestore = "css=.bx--toast-notification__subtitle";
	public static String SuccessMessageAfterCommunityCardRestore = "css=.bx--toast-notification.bx--toast-notification--success";
	public static String GalleryWidget = "css=div.gallery";
	public static String CommunityAddAppsLink = "css=#communityMenu_CUSTOMIZE_text";
	public static String communityChangeLayoutLink = "css=#communityMenu_CHANGELAYOUT";
	public static String communityChangeLayout2ColumnsLink = "link=2 Columns";
	public static String communityChangeLayout3ColumnsLink = "link=3 Columns";
	public static String communityChangeLayout3ColumnsWithBannerLink= "link=3 Columns with banner";
	public static String communityLayoutLeftColumn = "css=div[id='widget-container-col1'] div[id='col1DropZone']";
	public static String communityLayoutWideColumn = "css=div[class='lotusContent wpthemeWide']";
	public static String communityLayoutRightColumn = "css=div[class='lotusColRight wpthemeNarrow wpthemeNarrowOrig'], div[class='lotusColRight wpthemeNarrow wpthemeNarrowPlus']";
	public static String communityBannerArea = "css=div[id='bannerDropZone'] div[class^='lotusWidget2']:contains(Drag apps here.)";
	public static String communityChangeLayout2ColumnsWithSideMenu = "link=2 Columns with side menu";
	public static String communityChangeLayout3ColumnsWithSideMenu = "link=3 Columns with side menu";
	public static String communityChangeLayout3ColumnsSideMenuAndBanner = "link=3 Columns with side menu and banner";
	public static String communityChangeLayout3ColumnsWithTopMenu = "link=3 Columns with top menu";
	public static String communityChangeLayout3ColumnsWithTopMenuAndBanner ="link=3 Columns with top menu and banner";
	public static String selectedLayout3ColumnsWithTopMenuAndBanner = "css=span[class='titleNodeSpanSelected']:contains(3 Columns with top menu and banner)";
	public static String AddAppsSubcommunities = "link=Subcommunities";
	public static String editCommDescSaveAndCloseButton = "css=div[class$='Content edit'] form p input[id='description.saveAndClose']";
	public static String editCommDescCancelButton = "css=div[class$='Content edit'] form p input[id='description.cancel']";
	public static String editCommDescEditorToolbar = "css=div[id='descContent'] div[id='cke_descText'] div span[id='cke_1_top']";
	public static String moveButton = "css=button.lotusBtn:contains('Move')";
	public static String moveCommunityDialogBox = "css=div[id^='dijit_Dialog'] div[id^='lconn_comm_controls_dialog_MoveCommunity']";
	public static String moveSubcommDialogBox = "css=div[id^='dijit_Dialog'] div[id^='lconn_comm_controls_dialog_MoveSubCommunity']";
	public static String moveCommToSubcommInputField = "css=div[id^='dijit_Dialog'] div[class='dijitDialogPaneContent'] div[class='lotusDialogContent'] fieldset input[id='communityTypeAhead']";
	public static String moveCommunityTypeaheadPicker = "css=#communityTypeAhead_popup0";
	public static String moveSubcommCancelButton = "css=div[id^='lconn_comm_controls_dialog_MoveSubCommunity'] div[class='lotusDialogFooter'] button[class='lotusBtn']:contains(Cancel)";
	public static String moveTopLevelCommCancelButton = "css=div[id^='lconn_comm_controls_dialog_MoveCommunity'] div[class='lotusDialogFooter'] button[class='lotusBtn']:contains(Cancel)";
	public static String makeTopLevelRadioButton = "css=span[dojoattachpoint='ForSubCommunity'] input[id='makeTopLevel']";
	public static String makeSubcommRadioButton = "css=span[dojoattachpoint='ForSubCommunity'] input[id='makeSub']";
	public static String moveCommDialogCloseButton = "css=div[id^='lconn_comm_controls_dialog_MoveCommunity'] div[class='lotusDialogHeader'] a[title='close']";
	public static String moveSubcommDialogCloseButton = "css=div[id^='lconn_comm_controls_dialog_MoveSubCommunity'] div[class='lotusDialogHeader'] a[title='close']";
	public static String moveCommIAcknowledgeCheckbox = "css=div[dojoattachpoint='warningPanel'] input[type='checkbox']";
	public static String moveCommIAcknowledgeText = "css=div[dojoattachpoint='warningPanel'] label[id='acknowledgeLabel']";
	public static String moveCommWarningIcon = "css=div[class^='lotusWarning'] img[class='lotusIcon lotusIconMsgWarning']";
	public static String moveCommWarningMsgText = "css=div[class^='lotusWarning'] span:contains(Moving this community will cause the following changes and cannot be undone)";
	public static String moveCommAddMembersToParentMsg = "css=div[dojoattachpoint='namesMovedUpContainer'] div[dojoattachpoint='namesMovedUpTitle']:contains(These (1) users will be made members of the Parent community)";
	public static String moveCommAddOwnersToSubcommMsg = "css=div[dojoattachpoint='namesMovedDownContainer'] div[dojoattachpoint='namesMovedDownTitle']:contains(These (1) users will be made owners of the Subcommunity)";
	public static String moveCommViewMembersTwistie = "css=div[dojoattachpoint='namesMovedUpContainer'] div[class='lotusIndent10'] div[dojoattachpoint='namesMovedUpTwistie']";
	public static String moveCommViewOwnersTwistie = "css=div[dojoattachpoint='namesMovedDownContainer'] div div[dojoattachpoint='namesMovedDownTwistie']";
	public static String moveCommSuccessMsg = "css=div[class='lotusMessageBody'] span:contains(Community has been successfully moved.)";
	public static String myOrgCommunitiesView = "css=#toolbar_catalog_menu_allcommunities";
	public static String listedRestrictedCheckboxComm = "css=input[id='listRestrictedCom']";
	public static String listedRestrictedCheckboxSubcomm = "css=input[id='addListRestrictedCom']";
	public static String uploadedFileIcon="css=img[class^='lconnFileUploadIcon']";
	public static String additionalOptionsLink="css=tr[class='lotusFormFieldRow'] td img[class='lotusArrow lotusTwistyClosed']";
	public static String importantBkmkCheckbox ="css=td[class='lotusFormFieldRow'] input[id='addBookmarkImportant']";
	public static String selectedUserToAddToComm="css=div[id='memberList'] a[class^='lotusFilter'],div[class='nameContent'] span[class^='fn person']";
	public static String changeLayoutPalette = "css=div[class='lotusPaletteContentAreaNode'] div[id^='lconn_core_palette_ChangeLayoutContentPanel']";
	public static String moderatedIconFullMembersPage = "css=span[class='cnxnsType lotusMeta'] img[title='Moderated']";
	public static String reqToJoinModeratedCommForm = "css=h2:contains(Request Membership:)";
	public static String ContentViewFrame = "css=frame[name='ContentViewFrame']";
	public static String ContentFrame = "css=frame[name='ContentFrame']";
	public static String HelpTagFrame = "css=frame[name='HelpFrame']";
	public static String newToCommJoinCommHelpLink = "css=li[id='commWelcomeMsg1'] a:contains(Join a community)";
	public static String newToCommForumHelpLink = "css=li[id='commWelcomeMsg2'] a:contains(Participate in your community's forum)";
	public static String newToCommShareResourcesHelpLink = "css=li[id='commWelcomeMsg3'] a:contains(Share useful web resources)";
	public static String newToCommCreateCommHelpLink = "css=li[id='commWelcomeMsg4'] a:contains(creating your own community)";
	public static String uploadCommunityImageLink = "css=li[id='photoUploadLink'] a[role='button']:contains(Upload a Community Image)";
	public static String communitiesMailAllRadioBtn = "css=input[id='mailAll']";
	public static String communitiesMailOwnersOnlyRadioBtn = "css=input[id='mailOwners']";
	public static String communitiesMailNoOneRadioBtn = "css=input[id='mailNoOne']";
	public static String emailCommDialogAllMembersRadioBtn = "css=input[id='allMembers'][type='radio']";
	public static String emailCommDialogOwnersOnlyRadioBtn = "css=input[id='ownersOnly'][type='radio']";
	public static String emailCommDialogCancelBtn = "css=input[class='lotusFormButton'][type='button'][value='Cancel ']";
	public static String addRelatedCommBtn = "css=a[role='button'][title='Add a Community']";
	public static String thisCommunitySearchLink = "css=div[class='icScopes'] a[class='icLocalScope'], div[class='icScopes lconnClearFix'] a[class='icLocalScope']";
	public static String AddMembers_SaveButton = "css=input[id='saveButton']";
	public static String IamFollowing = "css=a#toolbar_catalog_menu_followedcommunities";
	public static String IamInvited = "css=#toolbar_catalog_menu_communityinvites";
	public static String InvitationsTab ="css=div['lotusTabContainer'] ul li[id='invitesTab'] a:contains(Invitations)";
	public static String InvitedMemberResendLink = "css=a[title=Resend]";
	public static String InvitedMemberResendButton = "css=a[role=button]:contains(Resend)";
	public static String InvitedMemberRevokeLink = "css=a[title=Revoke]";
	public static String InvitedMemberRevokeButton = "css=a[role=button]:contains(Revoke)";
	public static String SelectRoleImportMember = "css=select[id='selectRoleimportMembersForm1']";
	public static String ImportMemberFile = "css=input[id='csvfileimportMembersForm1']";
	public static String ImportMemberCSV_File = "css=input[id='radiocsvfileimportMembersForm1']";
	public static String ImportMembersButton = "link=Import Members";
	public static String ExportMembersButton = "link=Export Members";
	public static String ExportMembersDialogHeading = "css=h1[class='lotusHeading'] span:contains(Export People from this Community to a CSV file)";
	public static String ExportMembersDialogCloseIcon = "css=a[class='lotusDialogClose'][title='Close']";
	public static String ExportMembersOwnersCheckbox = "css=input[id='ownersCheckboxexportMembersForm1']";
	public static String ExportMembersMembersCheckbox = "css=input[id='membersCheckboxexportMembersForm1']";
	public static String ExportMembersOwnersCheckboxSelected = "css=input[id='ownersCheckboxexportMembersForm1'][checked='yes']";
	public static String ExportMembersMembersCheckboxSelected = "css=input[id='membersCheckboxexportMembersForm1'][checked='yes']";
	public static String ExportMembersDialogExportButton = "css=input[value='Export']";
	public static String ExportMembersDialogCancelButton = "css=div[class='lotusDialogFooter'] input[class='lotusFormButton cancel'][value='Cancel']";
	public static String MembersImportTextArea = "css=#csvtextareaimportMembersForm1";
	public static String MemberImportButton = "css=input[value='Import']";
	public static String MemberImportSubmitButton = "css=input.lotusFormButton.submit";
	public static String MemberEditionPopUp = "css=div.lotusDialogHeader";
	public static String CancelButtonEditMemberScreen = "css=input.lotusFormButton.cancel";
	public static String EditCommunityName ="css=#editCommunityName";
	public static String RestrictedAccess = "css=#privateAccess";
	public static String ModeratedAccess = "css=#publicInviteOnlyAccess";
	public static String PublicAccess = "css=#publicAccess";
	public static String EditCommunityCancelButton = "css=#editCommunityCancelBtn";
	public static String editCommStartPageListItem = "css=tr[class='lotusFormFieldRow'] td select";
	public static String MemberFilterBy = "css=#roleFilter";
	public static String FindAMember = "css=#findAMember";
	public static String FindMembers = "css=#filterString";
	public static String SortMembersByName = "css=#sortMembersByName";
	public static String SortMembersByDate ="css=#sortMembersByDate";
	public static String createSubCommunityFromDropdown ="css=[id='communityMenu_CREATESUB_text'] ,td[id='communityMenu_CREATESUBURL_text']";
	public static String FollowThisCommunity = "css=a[id='followDisplayActionsBtn']:contains('Follow this Community')";
	public static String StopFollowingThisCommunity = "css=a[id='followDisplayActionsBtn']:contains('Stop Following this Community')";
	public static String bannerNoCommunitiesFollowed = "css=td.lotusLastCell > span:contains('You are not following any communities')";
	public static String CommunityLeavingWarningOkButton = "css=button:contains('OK')";
	public static String CommunityLeavingMessageShowOnMemberScreen = "css=#com_ibm_oneui_controls_MessageBox_2 > div.lotusMessageBody > span";
	public static String LastOwnerCommunityLeavingMessage = "css=h1.lotusHeading";
	public static String LastOwnerComLeavingThenReturnButton = "//input[@value='Back to the My Communities view']";
	public static String SubcommunityLinkAfterAddApp = "link=Add Your First Subcommunity";
	public static String ParentCommunityLinkOnSubCommunity = "css=div.lotusBreadcrumbs > a";
	public static String bannerBreadcrumbParentCommLinkOnSubcommPage = "css=div[class='lotusInner'] h2 a[class='lotusBold comNavInline'], div[id='tabNavParentName'] a[class='lotusBold comNavInline tabNavTextEllipsis']";
	public static String CommunityHandleError = "css=div.lotusMessageBody > span";
	public static String viewAllmembersLink = "css=div#membersdiv a[title='All Members']";
	public static String iframePostMessage = "css=iframe[title='What do you want to share?']";
	public static String PostStatusMessage = "css=div.lotusMessage.lotusConfirm > span";
	public static String LikeStatusMessage = "css=a.lotusLikeAction";
	public static String commentStatusMessage = "css=li.commentAction a";
	public static String LikeCountStatusMessage = "css=div.lotusLikeText";
	public static String commentiframe = "css=iframe[title='Add a comment']";
	public static String commentPostButton = "css=a[dojoattachpoint='commentPostActoin']";
	public static String RecentUpdateMessageList = "css=div.lotusPostAction.asLinkContainer";
	public static String getCommunityMembers = "css=table[id='membersEntriesFullMembers'] span[class='vcard'] a";
	public static String getMemebers = "css=table[id='membersEntriesFullMembers'] td[id^='id0x']";
	public static String radioFirstFolder = "css=div#lconn_share_widget_Node_0_headerselector";
	public static String foldersTab = "css=a[role='tab']:contains('Folders')";
	public static String AddToFolder = "link=Add to Folder";
	public static String noFilesToDisplay = "css=div.qkrGalleryThumbnailView:contains('There are no files to display in this Gallery.'), div.qkrGalleryThumbnailView:contains('There are no files to display in this Gallery.')";
	public static String menuOption = "css=tbody[class='dijitReset'] tr";
	public static String deletedFolder = "css=div.landingpage:contains(' This folder cannot be found. It might have been deleted or is no longer shared. Select another folder or remove this gallery.')";
	public static String galleryConfig = "css=div h2 a[aria-label='Actions for: Gallery']";
	public static String JoinACommunity = "css=*[id='joinDisplayActionsBtn']";
	public static String tabbedNavMetricsTab = "css=li[id='metricsLinkId'] a:contains(Metrics)";
	public static String tabbedNavMenuItems = "css=div[id='tabNavContainer'] ul[id='lotusNavBar'] li[id$='_navItem']";
	public static String recentUpdatesHeader = "css=span[id='RecentUpdatesId']";
	public static String statusUpdatesHeader = "css=span[class='ibmDndDragHandle']:contains(Status Updates)";
	public static String tabbedNavParentCommunityName = "css=div[id='tabNavParentName']";
	public static String tabbedNavFilesTab = "css=li[widgetdefid='Files']";
	public static String tabbedNavForumsTab = "css=li[widgetdefid='Forum']";
	public static String tabbedNavBookmarksTab = "css=li[widgetdefid='Bookmarks']";
	public static String tabbedNavActivitiesTab = "css=li[widgetdefid='Activities']";
	public static String tabbedNavBlogTab = "css=li[widgetdefid='Blog']";
	public static String tabbedNavIdeationBlogTab = "css=li[widgetdefid='IdeationBlog']";
	public static String tabbedNavEventTab = "css=li[widgetdefid='Calendar']";
	public static String tabbedNavWikiTab = "css=li[widgetdefid='Wiki']";
	public static String tabbedNavBoxTab = "css=li[widgetdefid='Box']";
	public static String tabbedNavRelatedCommTab = "css=li[widgetdefid='RelatedCommunities']";
	public static String tabbedNavSurveysTab = "css=li[widgetdefid='Surveys']";
	public static String addAppsLibraryAddedLink = "css=span[title='Library added']";
	public static String tabbedNavLeftScrollBtn = "css=li[class='tabNavScrollBtn'] a img[class$='dijitTabStripSlideLeftIcon']";
	public static String tabbedNavRightScrollBtn = "css=li[class='tabNavScrollBtn'] a img[class$='dijitTabStripSlideRightIcon']";
	public static String tabbedNavHiddenSubcommField = "css=div[id='tabNavSubMenuContainer'] [class='lotusHidden']";
	public static String tabbedNavSubcommLink = "css=div[id='tabNavSubMenuSelection']";
	public static String tabbedNavSubcommMenuIcon = "css=a[id='tabNavSubMenuTitleLinkAnc'] div[class='tabNavItemInline'] img[class='lotusArrow lotusDropDownSprite']";
	public static String tabbedNavSubcommCount = "css=div[id='tabNavSubMenuSelection']:contains(PLACEHOLDER Subcommunities)";
	public static String tabbedNavSubcommMenuItem = "css=table[id='SubcommunityMenu'] tbody tr[id^='subcomIdx_']";
	public static String tabbedNavRecentUpdatesTab = "css=li[id='RecentUpdates_navItem'] a:contains(Recent Updates)";
	public static String tabbedNavMembersTab = "css=li[id='Members_navItem'] a:contains(Members)";
	public static String tabbedNavOverviewTab = "css=li[role='tab'] a:contains(Overview)";
	public static String tabbedNavMoreTab = "css=li[id='tabNavMoreBtn']";
	public static String megaMenuOptionCommunities = "css=a[id='lotusBannerCommunitiesLink'],div[id='communitiesMenu_container'],a[id='communitiesMenu_container']";
	public static String businessOwnerRadioButton = "css=input[id^='businessownerradioid'][value='business-owner'][type='radio']";
	public static String statusUpdateFirstEECommentLike = "css=a[id='TOGGLE_com_ibm_oneui_controls_Like_0']:contains(Like)";
	public static String statusUpdateFirstEECommentUnlike = "css=a[id='TOGGLE_com_ibm_oneui_controls_Like_0']:contains(Unlike)";
	public static String statusUpdateFirstEECommentLikeNum = "css=li[class='lotusCommentItem lotusFirst'] div[class='lotusLikeText']";
	public static String tabbedNavStatusUpdatesTab = "css=li[id='StatusUpdates_navItem'] a:contains(Status Updates)";
	public static String communityOverviewPageURL = "communityoverview";
	public static String communityActions ="css=[id='displayActionsBtn']";
	public static String addAppsLink="css=td:contains(Add Apps)";
	public static String addAppsHighlightWidget = "css=a:contains(Highlights)";
	public static String closeAddAppsButton = "css=a[title='Close palette']>img";
	// radio Button to add file to the folder from files widget
	public static String addToFolderRadio = "css=input[id='lconn_share_widget_Stream_1_0']";
	public static String previewDialog = "css=div.qkrDialog.dijitDialog[id^='lconn_share_widget_PreviewDialog_']";
	public static String fileViewer = "css=div.ics-viewer";
	public static String closeThumbnail = "css=a[id='share_action_dialogclose_0']";
	public static String closeViewer = "css=.ics-viewer-action-close img";
	public static String filesMoveToTrash = "css=td[id^='lconn_files_comm_actions_deletefile']:contains(Move to Trash)";
	public static String filesMoreActionsButton = "css=a[id^='lconn_files_action_more'][title='More Actions']";
	public static String filesWidgetAddButton = "css=div[id='actionContainer'] button[id^='lconn_files_action_additem_']";
	public static String filesWidgetShareFileWithCommunityLink = "css=td[id^='lconn_files_comm_actions_sharecommfiles']:contains(Share File with Community...)";
	public static String filesWidgetShareFolderWithCommunityLink = "css=td[id^='lconn_files_comm_actions_sharecommfolder']:contains(Share Folder with Community...)";
	// when evoking file selection dialog the 2nd time. id gets incremented by 1.
	public static String folderSecondTime = "css=div#lconn_share_widget_Node_2_headerselector";
	public static String businessOwnerhover = "css=a[id='lconn_core_HelpLauncher_5']";
	public static String BizzCardFrame = "css=iframe[id='dojo_request_iframe_IoIframe']";
	// Communities UI URL Preview selector(s)
	public static String URLPreview_AfterPostingSU = "css=div[class*='activityStreamNewsItemContainer']:contains(PLACEHOLDER) > div[class='lotusPostContent'] > div[aria-label*='REPLACE_THIS']";
	public static String URLPreview_AfterPostingSU_ThumbnailImage = URLPreview_AfterPostingSU + " > div[class='lconnPreviewLeft'] > a[class='lconnPreviewCenter']";
	public static String StatusPost = "link=Post";
	public static String StatusComment = "link=Comment";
	public static String StatusClear = "link=Clear";
	public static String CommentAddTextArea ="css=#mentionstextAreaNode_1";
	public static String CommentOnStatus = "css=div.lotusPostDetails > div.asLinkContainer";
	public static String leftNavGallery = "link=Gallery";
	public static String leftNavEvents = "link=Events";
	public static String leftNavRelatedComm = "link=Related Communities";
	public static String leftNavLibrary = "link=Library";
	public static String AddAppsDefaultCount = "css=span.lotusRight > span:contains(0 applications added)";
	public static String AddAppsCountAfterAdditonofApps = "css=span.lotusRight.lotusAdded  > span, span[class='lotusRight lotusAdded'] p[data-dojo-attach-point='itemAddedTextHolder']";
	public static String AddAppsBlogs = "link=Blog";
	public static String AddAppsDialog = "css=div[id='app_palette_dialog_modal'] span[class='widgetContainer']";
	public static String HiddenAppsLink = "link=Hidden";
	public static String RecentUpdateCommunityName = "css=div.lotusPostContent.bidiAware";
	public static String RecentUpdateCommunityCreatorInfo = "css=div.lotusPostAction.asLinkContainer.lotusTitle";
	public static String eventsAppDefaultMsg="css=div[dojoattachpoint='noUpcomingEventsMsgBox']";
	//This selector is meant for both Edit community/SubCommunity page
	public static String StartPageInEditCommunity = "css=label[id$='tartPageLabel']";
	public static String CatalogViewCloudTag = "css=div[id='lconnTagWidget_0_tagCloudView'] div ul li a[title*='communitytesttag123']";
	public static String CatalogViewListTag = "css=div[id='lconnTagWidget_0_tagListView'] ul li a[title*='communitytesttag123']";
	// CR4 Tag list
	public static String CatalogCardViewListTag = "css=.bx--tag__list[aria-label='Tags']";
	public static String CatalogCardFilterExpanded = "css=.filter-refiner.expanded";
	public static String TagOfCloud = "css=span.lotusBold:contains('Cloud')";
	public static String Recommendation = "css=h2[id='lconn_communities_catalog_widgets_RecommendationsBox_0recommendTitle']";
	public static String RecommendationLoginToSee = "css=div[dojoattachpoint='recommendErrorNode']";
	public static String RecommendationMenu = "css=a[id='actionsIcon'][title='Recommendations actions']";
	public static String DefaultRecommendatioMessage = "css=#lconn_sand_RecommendWidget_0_welcomeNode";
	public static String OwnerRadioButton = "css=label.lotusCheckbox:contains('Owner')";
	public static String OwnerRadioButton1 = "css=input[value='owner'][type='radio']";
	public static String MemberRadioButton = "css=label.lotusCheckbox:contains('Member')";
	public static String MemberDetailArea = "css=div.lotusFloatContent";
	public static String AddYourFirsBookMark = "link=Add Your First Bookmark";
	public static String DeleteBookmark = "link=Delete";
	public static String overviewPageTagInCloud="css=a.lotusF3, a[class^='lotusF']";
	public static String TagInCloud = "css=a.lotusF1";
	public static String TagInList = "css=a.lotusLeft";
	public static String ListUnderTag = "css=a:contains('List')";
	public static String BrowseButton = "css=[value='Browse...']";
	public static String AddFileLink = "link=Add a File";
	public static String OkButtonFileUpload = "css=input.lotusFormButton[value='OK']";
	public static String communitiesMegaMenu = "css=li[id='lotusBannerCommunities']>a";//:contains(Communities)";
	public static String Visitor_communitiesLink = "css=li[id='lotusBannerCommunitiesExternal']>a";
	public static String communitiesMegaMenuMyCommunities = "css=a[class='lotusBold']:contains(My Communities)";
	public static String communitiesMegaMenuOwner = "//a[contains(text(),'m an Owner')] | //a[@class='lotusBold'][contains(text(),'m an Owner')]";
	public static String communitiesMegaMenuPublic = "css=a.lotusBold:contains(Public Communities),a.lotusBold:contains(My Organization Communities)";
	public static String communitiesMegaMenuMember = "css=a[class='lotusBold']:contains(I'm a Member)";
	public static String communitiesMegaMenuFollow = "css=a[class='lotusBold']:contains(I'm Following)";
	public static String communitiesMegaMenuInvited = "css=a[class='lotusBold']:contains(I'm Invited)";
	public static String filesMoreActionsBtn = "css=button[id^='lconn_files_action_more']";
	public static String filesMoreActionsArrow = "css=div.lconnBreadcrumbitem.lconnBreadcrumbnode img.lotusArrow.lotusDropDownSprite";
	public static String filesEditPropertiesOption = "xpath=//td[starts-with(@id,'lconn_files_comm_actions') and contains(text(), 'Edit Properties')]";
	public static String filesDeleteOption = "xpath=//td[starts-with(@id,'lconn_files_comm_actions') and contains(text(), 'Delete')]";
	public static String CancelButtonFileUpload ="css=input.lotusFormButton[value='Cancel']";
	public static String InvitedUnreadCount = "css=span[class='lotusUnreadBadge']";
	// CR4 invited count
	public static String InvitedCardUnreadCount = "css=.nav-item__invite-count";
	public static String HiddenArea="css=a[categoryid='hiddenCat']";
	public static String resendInviteMsg = "css=div[class='lconnEmpty']:contains(This community has no pending invitations.)";
	public static String GenericMemberElement = "css=table[id='membersEntriesFullMembers'] tr[class='lotusFirst'] td[id^='id0x'], table[id='membersEntriesFullMembers'] tr[class='lotusFirst'] td[id^='ID']";
	public static String CreateaSurvey = "css=a[class='lotusAction']:contains(Create a Survey)";
	public static String AllowExternalTxt = "Allow people from outside of my organization to become members of this community";
	public static String AllowExternalCheckboxDisabled = ("css=label[id='allowExternalLabel'][class='lotusDisabled']");
	public static String InternalCommunityMsg = "Once a community is designated as solely for your organization, "
		+ "it can never be changed to allow people from outside your organization.";
	public static String SubcommLeftDropdown = "css=div.lotusMenu[role='navigation'] div#dropdownSubMenu a:contains(SubCommunity)";
	public static String OpenOverViewMenu = "css=#dropdownNavMenuTitleLink";
	public static String leftNavMenuItems = "css=li[id$='_navItem'] a";
	public static String topNavMoreMenuItems = "css=table[id='CommunitiesMoreMenu'] tbody tr td[class$='dijitMenuItemLabel']";
	public static String RecentUpdateFileContent = "css=div.lotusPostDetails.lotusChunk div.lotusPostObject img, div.lotusPostDetails.lotusChunk div img";
	public static String RecentUpdateTags = "css=div.lotusMeta li[dojoattachpoint='tagsListItem']";
	public static String AddMemberscheckbox = "css=input[id='addAllMembers']";
	public static String ShareUpdateAttachmentFile = "css=span[dojoattachpoint='fileAttachmentDetailsNode'] span";
	public static String ShareUpdateRemoveLink = "css=a.lotusDelete[title='Remove file attachment']";
	public static String filesFullWidgetPageHeader = "css=div[id='lotusContentHeader'] h1 a:contains(All Community Files)";
	public static String widgetPaletteNextButton = "css=div[class='lotusPaging'] ul[data-dojo-attach-point='scrollControlNode'] li a:contains(Next)";
	public static String widgetPaletteNavButton = "css=div[class='lotusPaging'] ul[data-dojo-attach-point='scrollControlNode'] li a";
	// create survey form
		public static String NameField = "css=input[id*='FULLPAGE_createViewSection_surveyName']";
	public static String DescriptionField = "css=textarea[id*='_FULLPAGE_createViewSection_surveyDesc']";
	public static String ContinueBtn = "css=input[value='Continue']";
	// Add question to Survey
		public static String AddQuestion = "css=button[title='Add Question']";
	public static String QuestionFrame = "css=iframe[id*='_FULLPAGE_designerSection_myFrame']";
	public static String QuestionDescriptionField = "css=input[id='freedom_widget_ide_environment_QuestionCreator_0_questionTextBox']";
	public static String SelectOne = "css=select[id='freedom_widget_ide_environment_QuestionCreator_0_questionTypeSelect']";
	public static String NotSavedObj = "css=div[class='lotusMessage2 lotusWarning']";
	public static String MultipleChoice = "css=select[value='choice_many']";
	public static String OKBtn = "css=span[id='dijit_form_Button_7_label']";
	// Start Survey
		public static String SaveBtn = "css=button[title='Save']";
	public static String StartBtn = "css=button[title='Start']";
	public static String CloseBtn = "css=input[value='Close']";
	public static String SurveyImage = "css=img[class='lconn-survey_complete_32']";
	public static String Option = "css=input[type='radio']";
	// Take survey
		public static String TakeSurveyFrame = "css=iframe[id*='_FULLPAGE_singleViewSection_iFrame']";
	public static String WidgetHideConfirm = "css=input[value='Hide']";
	// Moderated icon & Text locators for Moderated community
		public static String ModeratedIcon = "css=span[dojoattachpoint='moderatedIconNode'] img[class*='lconnSprite-iconModeratedCommunity']";
	public static String ModeratedIconHidden = "css=span[dojoattachpoint='moderatedIconNode'][style$='none']";
	public static String ModeratedText = "css=span[dojoattachpoint='moderatedIconNode']";
	public static String Moderated = "Moderated";
	public static String ModeratedIconOverviewPage = "css=img[title='This is a moderated community']";
	// new for CR4
		public static String ModeratedCardIcon = "css=.access-icon.moderated-icon";
	public static String ModeratedCardText = "css=.access-icon.private-icon[title='Moderated']";
	// Restricted icon & Text locators for Restricted community
		public static String RestrictedIcon = "css=span[dojoattachpoint='restrictedIconNode'] img[class*='iconsStates16-CheckedOut']";
	public static String RestrictedIconHidden = "css=span[dojoattachpoint='restrictedIconNode'][style$='none']";
	public static String RestrictedText = "css=span[dojoattachpoint='restrictedIconNode']";
	public static String Restricted = "Restricted";
	public static String RestrictedIconMembersPage = "css=span[class='cnxnsType lotusMeta'] img[class*='iconsStates16-CheckedOut'][title='Restricted']";
	public static String RestrictedIconOverviewPage = "css=img[title='This is a restricted community']";
	// new for CR4
		public static String RestrictedCardIcon = "css=.access-icon.private-icon";
	public static String RestrictedCardText = "css=.access-icon.private-icon[title='Restricted']";
	// External icon & Text locators for public community
		public static String ExternalIcon = "css=span[dojoattachpoint='externalIconNode'] img[class*='lconnIconListSharedExternal']";
	public static String ExternalIconHidden = "css=span[dojoattachpoint='externalIconNode'][style$='none']";
	public static String ExternalText = "css=span[dojoattachpoint='externalIconNode']";
	public static String ExternalIconOverviewPage = "css=img[title='This community can have members from outside your organization']";
	// new for CR4
		public static String ExternalCardIcon = "css=.shared-icon";
	public static String ExternalCardText = "css=.shared-icon[title='Shared External']";
	// SubCommunity Handler
		public static String SubCommunityHandle = "css=input[id='addHandle']";
	public static String WebAddressHandle = "css=tr[id='addAdvHandleRow1'] span[dir='ltr']";
	public static String EditSubCommunityCancelBtn = "css=#editSubcommunityCancelBtn";
	//Start Page in community
		public static String OverviewSelected = "css=option[value='Overview'][aria-selected='true']";
	//Hide Community
		public static String ContentInDialogBox = "css=div.lotusDialog div.lotusDialogContent";
	//Feeds
		public static String AddFeedLink = "link=Add a Feed";
	public static String FeedsViewAllLink = "css=td.lconnfeedBottomAction a";
	public static String FeedDate = "css=span[lcnodetype='AtomFeedDate']";
	//Start a Community dropdown menu in Catalog view
		public static String StartACommunityMenu = "css=a[role='button']:contains(Start a Community)";
	public static String CopyExistingCommOption = "css=td[id='copyExistingCommMenuItem_text'], td[id='communityMenu_CREATECOPY_text']";
	public static String StartFromNewOption = "css=td[id='startNewCommMenuItem_text']";
	public static String communityCreateURL = "communitycreate";
	//Copy Existing Community
	public static String CancelButtonCopyCommSearchDB = "css=input[value='Cancel']";
	public static String copyFromExistingURL = "copyFromExisting=true";
	public static String CopyStructureFormTitle = "Copying an Existing Community";
	public static String appendCopy = " Copy";
	public static String appendCopy1 = " Copy 1";
	public static String copyCommChooseBySearchingTextField = "css=input[id='communityTypeAhead']";
	public static String copyCommChooseBySearchingTypeAheadPopup = "css=div[id^='communityTypeAhead_popup']";
	public static String copyCommChooseBySearchingNoResultsFound = "No results found";
	//Community Guided Tour popup window
		public static String closeCommGuidedTour = "css=button[id='close-tooltip']";
	//Rich Content widget
		public static String rteAddContent = "css=a[title='Add Content']";
	public static String rteSave = "css=input[id=create_saveclose]";
	public static String richContentDescription = "css=[class='qkrWikiPreview bidiAware']";
	public static String richContentActions = "css=a[title='Actions for: Rich Content']";
	public static String richContentEditActions = "css=div[label='More Action Menu']>table>tbody>tr:nth-of-type(3)>td:nth-of-type(2)";
	//Gallery widget
		public static String setupTheGalleryDialogHeader = "css=div[id^='dialog_title'] h1:contains(Set up the Gallery)";
	public static String setAsGalleryButton = "css=input[value='Set as Gallery']";
	public static String galleryViewAllLink = "css=a[class='galleryViewAllHint']";
	public static String catalogFilter = "css=input[dojoattachpoint='filterInput']";
	public static String catalogFilterCardView = "css=input#icCatalogFilter";
	//MT
		public static String topNavMoreItems = "css=div[class*='dijitMenuPopup'] #CommunitiesMoreMenu tr td[data-dojo-attach-point*='containerNod']";
	public static String topNavBar = "css=#tabNavMenu #tabNavContainer";
	public static String widgetPageContent = "css=#lotusContent";
	public static String navmenu = "css=div#tabNavContainer>ul li";
	public static String communityFolders = "css=div#navCommunityFoldersSelector";
	public static String tabNavCommunityName = "css=div[id='tabNavCommunityName']";
	public static String communityOverview = "css=li[id='communityHomeLink']>a";
	public static String communityActivityHeader = "css=h1[dojoattachpoint='activityViewLabel_AP']";
	public static String communityEventHeader = "css=div[class*='eventHeader']";
	public static String communityStatusUpdates="css=div[id='contentArea'] span:contains('Status Updates')";
	public static String communityHighlights ="css=div.tabNavItemInBlk.tabNavOverflowHidden a:contains(Highlights)";
	public static String communityDescription = "css=[id='descContent']";
	public static String editCommunityDescription = "css=a[title='Actions for: Community Description']";
	public static String editCommunitySaveAndClose = "css=input[id='description.saveAndClose']";
	public static String imageNameInPreview = "css=a[class='ics-viewer-title-name']";
	public static String communitiesNames = "css=div[aria-label='PLACEHOLDER']";
	public static String commBlogEntryFeedLink = "css=#lotusContent #entryFeedLink";
	public static String commWikiPagActionBtn = "css=#lotusContent a[aria-label='Page Actions']";
	public static String commMetricsHeader = "css=#lotusContent h2";
	public static String commRecentUpdatesHeader = "css=#lotusContent span[id='RecentUpdatesId']";
	public static String commStatusUpdatesHeader = "css=#lotusContent span[class='ibmDndDragHandle']";

	//Bosch Automation
		public static String editCommunity = "css=td#communityMenu_EDITURL_text";
	public static String addAppslink = "css=td[id='communityMenu_CUSTOMIZE_text'], td[id='communityMenu_CUSTOMIZEURL_text']";
	public static String editCommunityNameInputField = "css=input[id='editCommunityName']";
	public static String uploadImageForCommunityLogo = "css=a:contains(Upload Image for Community Logo)";
	public static String chooseFile = "css=input[type='file']";
	public static String communityName = "css=div > a.comNavInline.tabNavTextEllipsis,div.comNavInline.tabNavTextEllipsis";
	public static String backToOverviewPage = "css=input[class='lotusFormButton'][value='Back to Overview Page']";
	public static String postStatusUpdateBtn = "css=a[class='ublogPost']";
	public static String widgetActMenu = "css= a[id^='widgetActionsMenuW']";
	public static String deleteOptionfromwidgetActMenu = "css=tr[aria-label='Delete ']";
	public static String deleteStatusUpdateBox = "css=div[id='lconn_communities_bizCard_dialogs_deleteConfirmWidget_0_title']";
	public static String confirmApplicationName = "css=input[id='communityInputField']";
	public static String signWithYourName = "css=input[id='signature']";
	public static String deleteStatsUpateCancelBtn = "css=button[name='yourButtonName']";
	public static String deleteStatsUpateOKBtn = "css=button:contains(OK)";
	public static String applicationNameFromDeleteCommStatusWindow = "css=div.lotusFieldWrapper span:contains(Status Updates)";
	public static String statusUpdateWidgetAdd = "css=a:contains(Status Updates)";
	public static String sharePointWidgetAdd = "css=a[title='SharePoint Library']";
	public static String closeAddAppsWindow = "css=a#closePalette";
	public static String insertImageLink = "css=a[data-title='Insert/Edit Image']";
	public static String uploadedVidoeNote = "css=span[id$='status_msg']";
	public static String viewDetailsLink = "css=a[title*='View details of ']";
	public static String videoLink1 = "css=a[title^='Download ']";
	public static String videoLink = "css=div#showRichContent a[title^='Download ']";
	public static String CommunityMyComputer = "css=span[class='lconnPickerSourceLabelSpan']:contains('My Computer')";
	public static String changeTitleLink = "css=div[aria-label='More Action Menu'] tr[aria-label='Change Title ']";
	public static String changeTitleDailogue = "css=div[class='lotusDialog'] h1 span:contains('Change Title')";
	public static String changeTitleInputField = "css=input[aria-labelledby='newTitleLabel']";
	//PDF Export Access
		public static String pdfExportAccessLinkHolder="css=#pdfexportaccess";
	public static String pdfExportAccessDialogHeading= "css=div[aria-label='PDF Export Access']";
	public static String pdfExportAccessDialogFrame="xpath=//iframe[contains(@src,'pdf-export-community-access')]";
	public static String pdfExportAccessDialogOptionAllowed="css=input[value='allow'";
	public static String pdfExportAccessDialogOptionNotAllowed="css=input[value='deny'";
	public static String pdfExportAccessDialogSaveAndClose="css=button[ng-click^='saveCommunityAccessAndClose']";
	//Create community using TE Widget
		//Community Details
		public static String communityNameTE = "xpath=//input[@name='communityName']";
	public static String emptyCommunityNameErrorText = communityNameTE + "//parent::div/div/p";
	public static String communityDescriptionTE = "css=textarea[name='communityDescription']";
	public static String communityTypePublic = "xpath=//div[text()='Public to My Organization ']";
	public static String communityTypeModerate = "xpath=//div[text()='Moderated']";
	public static String communityTypeRestricted = "xpath=//div[text()='Restricted']";
	public static String communityTypeRestrictedHidden = "xpath=//input[@name='listWhenRestrictedSubCom']";
	public static String uploadCommunityLogo = "css=.MuiButtonBase-root.MuiFab-root";
	public static String missingCommunityWarning= "xpath=//span[contains(text(),'Community Details') and contains(@class,'Mui-error')]";
	public static String communityDetailsStageCompleted = "xpath=//span[contains(text(),'Community Details') and contains(@class,'MuiStepLabel-completed')]";
	//Select a Template
	public static String searchForCommunityTemplate = "css=input[class^='MuiInputBase-input-'][placeholder='Search for community templates']";
	public static String searchTemplateIcon = "css=div[class^='MuiInputAdornment-root']>div>svg[class^='MuiSvgIcon-root']";
	public static String defaultCommunityTemplate = "xpath=//p[@title='Default Community' or @title='Default template']";
	public static String selectTemplateStageCompleted = "xpath=//span[contains(text(),'Select a Template') and contains(@class,'MuiStepLabel-completed')]";
	//Add Members
		public static String searchMemberToAdd = "css=input#memberList";
	public static String searchMemberFromParentCommunity = "css=input#outlined-adornment";
	public static String addMember = "css=button.MuiButtonBase-root.MuiButton-root.MuiButton-contained";
	public static String allowExternalUsers = "xpath=//span[contains(text(),'Allow external users')]";
	public static String addedMemberListTable = "css=.MuiTable-root.MuiTable-stickyHeader";
	public static String memberListPopup = "css=#memberList-popup";
	public static String addMemberStageCompleted = "xpath=//span[contains(text(),'Add Members') and contains(@class,'MuiStepLabel-completed')]";
	//Optional Settings
		public static String communityTags = "css=input#communityTags";
	public static String addedTag = "css=.MuiChip-root.MuiAutocomplete-tag>span";
	public static String communityWebAddress = "css=input[name='webAddress']";
	//Footer
		public static String backToPrevStep = "xpath=//span[text()='BACK']";
	//public static String backToPrevStep = "css=.jss66";
		public static String proceedToNextStep = "xpath=//span[text()='NEXT']";
	public static String ftCreateCommunity = "xpath=//span[text()='CREATE']";
	public static String skipAndCreateCommunity = "xpath=//span[text()='Skip And Create Community']";
	//Create Alert
		public static String createCommunityAlert = "css=div#alert-dialog-title>h2";
	public static String continueEditing = "xpath=//span[contains(text(),'Continue Editing')]";
	public static String createCommunity = "xpath=//span[contains(text(),'Create')]";
	public static String successMessage = "Community Created Successfully";
	public static String closeCommunityWizard = "css=button[title='Close community wizard']";
	public static String customizeButton="css=.customizebutton";
	public static String customizeButtonClose="css=.customizebutton.enabledEditMode";
	public static String communityHighlightTab="xpath=//div[@class='tabNavItemInBlk tabNavOverflowHidden']//a[text()='Highlights']";
	//Tailored Experience
        public static String templateAdmin="xpath=//label[contains(@class, 'drawerItemLabel')][text()='Template Administration']";
	public static String templateBtn="xpath=//span[contains(@class, 'MuiButton-label')][text()='Create Template']";
	public static String commURL="css=input[type='url']";
	public static String commName="css=input[placeholder='Type template name'][type='text']";
	public static String tempDes="css=textarea[placeholder='Type template description']";
	public static String createBtn="xpath=//div[starts-with(@class,'MuiDialogActions-root')]//span[contains(text(),'Create')]";
	public static String homePage="css=span#lconnBannerHomepageLabel";
	public static String searchBoxAdminPage = "css=input[class^='MuiInputBase-input']";
	public static String deleteTemplateButton = "xpath=//div[starts-with(@class,'MuiCardActions-root')]//*[2]";
	public static String yesButtonDeleteConfrimation ="xpath=//span[contains(@class, 'MuiButton-label')][text()='Yes']";
	public static String CreateSubcommunityMenu="css=td[id='communityMenu_CREATESUBURL_text']";
	public static String ViewCardList="css=div.community-card";
	public static String CommunityCardRecentUpdate="css=p.short-info.recent-updates";
	public static String templateCategory="xpath=//label[contains(@class, 'drawerItemLabel')][text()='Categories']";
	public static String templateLabel="xpath=//label[contains(@class, 'drawerItemLabel')][text()='Templates']";
	public static String templateCategoryNew ="xpath=//span[contains(@class, 'MuiButton-label')][text()='New']";
	public static String templateCategoryName = "css=input[placeholder='Type name']";
	public static String templateCategoryDesc ="css=textarea[placeholder='Type description']";
	public static String templateCategoryAdd ="xpath=//span[contains(@class, 'MuiButton-label')][text()='Add']";
	public static String templateCategorySearch ="css=input[placeholder='Type to find a category']";
	public static String editCategory ="xpath=//td[starts-with(@class,'MuiTableCell-root')]//*[local-name() = 'svg']";
	public static String saveEditedCategory ="xpath=//span[contains(@class, 'MuiButton-label')][text()='Save']";
	public static String editTemplateButton = "xpath=//div[starts-with(@class,'MuiCardActions-root')]//*[local-name() = 'svg']";
	public static String selectCategory = "css=#edit-template-dialog-content-select";
	public static String editTemplateLabel = "xpath=//h2[contains(@class, 'MuiTypography-root')][text()='Edit Template']";
	public static String selectCategoryToSearch = "xpath=//div[contains(@class, 'MuiSelect-root')][text()='Select category']";
	public static String templateNameBox = "xpath=//div[starts-with(@class, 'MuiPaper-root')]//h2[text()='Template name']//following::div[1]//input";
	public static String templateDescriptionBox = "xpath=//div[starts-with(@class, 'MuiPaper-root')]//h2[text()='Template description']//following::div[1]//textarea";
	public static String uploadLogoBtn = "css=#filelogo";
	public static String uploadPreviewBtn = "css=#filepreview";
	public static String previewTemplateButton = "xpath=//div[starts-with(@class,'MuiCardActions-root')]//*[local-name() = 'svg'][4]";
	public static String closeTemplateBtn = "css=button[aria-label=close]";
	public static String exportTemplateButton = "xpath=//div[starts-with(@class,'MuiCardActions-root')]//*[local-name() = 'svg'][3]";
	public static String importTemplateButton = "css=#file";
	public static String BlogViewAllLink = "css=#blogsViewAllLink";
	public static String topicReply = "xpath=//*[contains(text(),'Topic Reply')]/ancestor::div[@class='lotusPostContent']//a[text()='Like']";
	public static String topicReplyLike = "xpath=//*[contains(text(),'Topic Reply')]/ancestor::div[@class='lotusPostContent']//div[@class='lotusLikeText']";
	public static String IMViewAllLink = "css=div#importantBookmarks > ul.lotusList a.lotusAction";
	public static String downloadCount = "css=div[data-dojo-attach-point='downloadsContainer'] span.dropdownLinkSpan:contains(0)";
	public static String statusUpdate = "css=div.activityStreamNewsItemContainer div.lotusPostContent";
	public static String versionNumber = "css=span.header1 > span.versionNumber";
	public static String moderatedCommunityImage ="css=div#tabNavCommunityName img[title='This is a moderated community']";
	public static String restrictedCommunityImage = "css=div#tabNavCommunityName img[title='This is a restricted community']";

	// Related Communities
	public static String relatedCommunityRemoveLink = "xpath=//a[text()='Remove this community']";
	public static String relatedCommunityMoreLink = "xpath=//td[@class='lotusAlignRight lotusLastCell lotusTiny']//a[@class='lotusAction']";
	public static String noUpdatesMsgforExtuser = "xpath=//div[contains(text(),'There are no updates to display.')]";
	
	public static String accessDeniedMsg = "xpath=//h1[contains(text(),'Access denied.')]";

	public static String editSubCommunityDescription = "xpath=//div[text()='Community Description']/..//button";
	public static String members = "//table[@id='membersEntriesFullMembers']//td[starts-with(@id, 'id')]";
	public static String membersName = "//span[text()='Member']//parent::div//span[@class='vcard']//a[starts-with(@id, 'name')]";
	public static String commMembersName = "//span[@class='vcard']//a[starts-with(@id, 'name')]";
	public static String membersEditLink = members+"//a[contains(@id, 'edit_id')][text()='Edit']";
	public static String membersRemoveLink = members+"//a[text()='Remove']";
	public static String findMembersSearchIcon = "//form[contains(@id ,'findMember_')]//a[contains(@class,'button_UI')]";
	public static String memberListPageInfo ="//div[@id='MemberListPageInfo']";
	public static String addMembersButton ="//a[@id='memberAddButtonLink']";
	public static String addInviteMembersButton ="//a[@id='memberInviteButtonLink']";
	public static String addImportMembersButton ="//a[@id='memberImportButtonLink']";
	public static String addExportMembersButton ="//a[@id='memberExportButtonLink']";
	public static String blogsNewEntryButton ="//a[text()='New Entry']";
	public static String createAnEventButton ="//a[text()='Create an Event']";
	public static String editAnEventButton ="//a[text()='Edit Event']";
	public static String deleteAnEventButton ="//a[text()='Delete Event']";
	public static String startAnIdeationBlogButton ="//a[text()='Start an Ideation Blog']";
	public static String EventsTab ="#listTab";
	
	private CommunitiesUIConstants() {}

}
