package com.ibm.conn.auto.webui.constants;

public final class FilesUIConstants {

	public static final String FILELIST_GRIDMODE_FILENAME_LNK = "css=table.dojoDndContainer tr.dojoDndItem > td > h4.lotusBreakWord > a[title='%s']"; // use String.format to inject the filename in %s
	public static final int waitAfterDownloadInMilliSeconds = 7500;
	public static final String fileviewer_previewLinkTitle = "css=a.ics-viewer-title-name";
	public static final String fileviewer_previewImage = "css=img[class^='ics-zoom-img']";
	public static final String fileviewer_previewVideo = "css=div[class='ics-video-widget']";
	public static final String fileviewer_previewOffice = "css=div[class='ics-viewer-widget']";  //need verify this one on daily
	public static final String fileviewer_previewUnsupported = "css=div[class='ics-viewer-icon-preview']";
	public static final String fileviewer_panelAboutThisFile = "css=div[class='ics-viewer-details-shelf'] h3[class='active-panels'] li[class^='about']";
	public static final String fileviewer_panelComment = "css=div[class='ics-viewer-details-shelf'] h3[class='active-panels'] li[class^='comments']";
	public static final String fileviewer_panelShareWith = "css=div[class='ics-viewer-details-shelf'] h3[class='active-panels'] li[class^='share']";
	public static final String fileviewer_panelVersion = "css=div[class='ics-viewer-details-shelf'] h3[class='active-panels'] li[class^='version']";
	public static final String fileviewer_panelCurrentVersion = "css=div[data-dojo-attach-point='versionContainer'] span[class='header1']";
	public static final String fileviewer_fileSize_CurrentVersion = "css=div[data-dojo-attach-point='filesizeContainer'] span[class='header2']";
	public static final String fileviewer_createdBy = "css=div[data-dojo-attach-point='createdDateContainer'] span[class='header2']";
	public static final String fileviewer_close = "css=li[class$='ics-viewer-action-close'] a";
	public static final String fileviewer_addCommentBox = "css=div[class='newCommentBox'] div[class^='lotusText lotusMentionsDiv']";
	public static final String fileviewer_postCommentButton = "css=div[class='newCommentBox'] div[class='commentActions'] li[class='ics-viewer-first'] a";
	public static final String fileviewer_commentContainer ="css=div.panelContent.streamContent";
	//HCL Docs
	public static final String documentInNewDropdown ="css=td[class='dijitReset dijitMenuItemLabel'][id^='com_ibm_concord_lcext_newconcorddoc_']";
	public static final String pptInNewDropdown ="css=td[class='dijitReset dijitMenuItemLabel'][id^='com_ibm_concord_lcext_newconcordpres_']";
	public static final String pptNameField = "css=input#concordnewfilepres";
	public static final String pptTitleBody = "css=div.box [aria-labelledby^='P_arialabel_Title']>div>div";
	public static final String pptSubtitleBody = "css=div.box [aria-labelledby^='P_arialabel_Subtitle']>div>div";
	public static final String pptTitleContentInFIDO = "css=div[aria-labelledby^='P_arialabel_Title']>div>div";
	public static final String pptSubtitleContentInFIDO = "css=p[class^=MP_defaultMaster_Title_subtitle_]";
	public static final String pptEditor_iFrame = "menutoolbarFrame";
	public static final String docName = "css=input#concordnewfiledoc";
	public static final String submitButton = "css=input#submit_button";
	public static final String docBody = "css=div[class^='textArea']>div:first-of-type";
	public static final String notNowButtonDGT = "css=div[id^='pWelcome'] span[label='Not Now']";
	public static final String closeButtonDGT = "css=div.fheader a[title='Close']";
	public static final String docEditor_FileMenu = "css=span:contains(File)";
	public static final String selectPublishNow = "css=td[class='dijitReset dijitMenuItemLabel']:contains(Publish Now)";
	public static final String publishButton = "css=span#C_d_PublishDialogOKButton_label";
	public static final String docTextArea = "css=div[class^='textArea']";
	public static final String docContentInFIDO = "css=div.line>span";
	public static final String docEditor_HelpMenu = "css=div#D_m_Help span#D_m_Help_text";
	public static final String docEditor_iFrame = "editor Frame";
	public static final String docViewer_iFrame = "Preview of this file";
	public static final String docEditor_WelcomeText = "Welcome!";
	public static final String spreadsheetInNewDropdown = "css=td[class='dijitReset dijitMenuItemLabel'][id^='com_ibm_concord_lcext_newconcordsheet_']";
	public static final String spreadsheetName = "css=input#concordnewfilesheet";
	public static final String spreadsheetEntry = "css=div[id^=websheet_widget__SelectRectangle_]";
	public static final String spreadsheetEditor_FileMenu = "css=span#S_i_File_text";
	public static final String ssPublishNow = "css=td#S_i_Publish_text";
	public static final String ssPublishNowBtn = "css=span#C_d_PublishDialogOKButton_label";
	public static final String fileViewAllLink = "xpath=//a[contains(@href, 'files')][contains(text(),'View All')]";
	public static final String previewnotAvailableMessage = "css=span[aria-label='No preview available for this file.']";
	
	//FIDO View Locators
	public static final String pinIcon = "css=div[id^= 'uniqName_'] a[title='Pin this file']";
	public static final String unpinIcon = "css=div[id^= 'uniqName_'] a[title='Unpin this file']";
	public static final String likeIcon = "css=div[id^= 'uniqName_'] a[title='Like the file']";
	public static final String uploadButton = "css=div[id^= 'uniqName_'] a[title='Upload a new version of this file']";
	public static final String unlikeIcon = "css=div[id^= 'uniqName_'] a[title='Unlike the file']";
	public static final String downloadIcon = "css=div[id^= 'uniqName_'] a[title='Download file']";
	public static final String downloadPopUpClose ="css=a#cancel";
	public static final String moreActionIcon = "css=#dijit_form_DropDownButton_0";
	public static final String hidepanelIcon = "css=div[id^= 'uniqName_'] a[title='Hide details panel']";
	public static final String showDetailspanelIcon = "css=div[id^= 'uniqName_'] a[title='Show details panel']";
	public static final String closeIcon = "css=li[class$=ics-viewer-action-close] a[title=Close]";
	public static final String pinMsg_FIDO = "xpath=//span[contains(text(),'You pinned this file.')]";
	public static final String unpinMsg_FIDO = "xpath=//span[contains(text(),'You have unpinned this file.')]";
	public static final String moreActionMenuItem_1 = "css=tr[aria-label='Download as PDF ']";
	public static final String moreActionMenuItem_2 = "css=tr[aria-label='Stop Following ']";
	public static final String moreActionMenuItem_3 = "css=tr[aria-label='Lock File ']";
	public static final String moreActionMenuItem_4 = "css=tr[aria-label='Give Copy to Community... ']";
	public static final String moreActionMenuItem_5 = "css=tr[aria-label='Transfer Ownership... ']";
	public static final String moreActionMenuItem_6 = "css=tr[aria-label='Refresh ']";
	public static final String moreActionMenuItem_7 = "css=tr[aria-label='Move to Trash ']";
	public static final String viewertabs = "css=ul.ics-viewer-tabs";
	public static final String moreEditOption = "css=span[title='More editing options']";
	public static final String createFileLink = "css=tr[title='Create File']";
	public static final String fileNameField = "css=input.name-input";
	public static final String fileCreateBtn = "css=a#ok";
	public static final String fileViewerTitle = "css=a[title='Edit file name']";
	// FIDO Comment Tab
	public static final String commentsTabLink = "css=li#comments";
	public static final String commentArea1_iframe = "css=iframe[class='cke_wysiwyg_frame cke_reset'],iframe[title='Rich Text Area']";
	public static final String commentArea2_iframe = "xpath=(//iframe[@class='cke_wysiwyg_frame cke_reset'])[2] | (//iframe[@title='Rich Text Area'])[2]";
	public static final String CommentTextArea = "css=body[aria-label= 'Comment text area'],#tinymce";
	public static final String commentSaveBtn = "css=a[class='save-button']";
	public static final String commentEditBtn = "css=div[id^='uniqName_']>div[class='actions edit delete']>span[class='action edit']";
	public static final String commentDeleteBtn = "css=div[id^='uniqName_']>div[class='actions edit delete']>span[class='action delete']";
	public static final String commentDeleteOkBtn = "css=a#ok";
	public static final String commentFeedLink = "css=a[title='Follow changes to these comments through your feed reader']";
	// Sharing Tab
	public static final String commSharingMsg = "css=div.sharingMsg.communityShareMsg";
	public static final String commSharingMsgExpected = "Files owned by a community cannot be shared to people or other communities.";
	public static final String stadaloneSharingMsg = "css=div[data-dojo-attach-point='noneShareContent']";
	public static final String standaloneSharingMsgExpected = "This file has not been added to any folders yet.";
	public static final String SharingAddToFolder = "css=a[title='Add To Folder']";
	public static final String SharingAddToFolderStandalone = "css=a[title='Add Folders']";
	public static final String ShareFolderTitle = "css=div[class$='shareFolderTitle']";
	public static final String createLinkButton ="xpath=//div[@class='descriptionContent']//a[contains(text(),'Create a Link')]";
	public static final String copyLinkButton ="css=a.copyLinkBtn";
	public static final String fidoFileName = "css=a#fileviewer_0_title";
	public static final String addPeopleOrCommunities = "xpath=//span[contains(text(),'Add People or Communities')]";
	public static final String memberTypeSelector = "css=select[id$='memberTypeSelector']";
	public static final String roleTypeSelector = "css=select[id$='roleSelector']";
	public static final String commSearchTextBox = "css=input[title^='Type to find']";
	public static final String searchButton = "css=div[dojoattachpoint='searchButton']";
	public static final String firstCommFromSearch = "css=div[id$='people_popup0']";
	public static final String shareButtonForComm = "xpath=//a[@class='manualAdd']//span[contains(text(),'Share')]";
	public static final String editorTitle = "xpath=//div[@data-dojo-attach-point='EditContainer']//div[contains(text(),'Editors')]";
	public static final String readerTitle = "xpath=//div[@data-dojo-attach-point='ViewContainer']//div[contains(text(),'Readers')]";
	public static final String removeEditorButton = "css=div[class$='editor'] a.remove.action";
	public static final String removeReaderButton = "css=div[class*= 'reader'] a.remove.action";
	public static final String shareCommunityTitle = "css=a[title*='Shared with members of the community']";
	public static final String removeShareEveryoneButton = "xpath=//div[contains(@class,'share everyone')]//a[@class='remove action']";
	public static final String shareEveryonetitle= "css=span[title='Everyone in your organization']";
	public static final String okButtonRemoveAction = "css=a#ok";
	public static final String fidShareCommunityList = "css=body > div.dijitPopup.dijitComboBoxMenuPopup > div.lconnPeopleTypeAheadMenu.dijitReset.dijitMenu.dijitComboBoxMenu";
	// UI Strings in File
	public static final String FOLLOWING_FILE_YOU = "You are now following this file.";
	/** Files selectors*/
	public static String GLOBAL_NEW_BUTTON = "css=button[id^='lconn_files_action_createitem_'][role='button']";
	public static String GLOBAL_ADD_BUTTON = "css=button[id^='lconn_files_action_additem_']";
	public static String NEW_FOLDER_IN_GLOBAL_NEW = "css=td[class='dijitReset dijitMenuItemLabel'][id^='lconn_files_action_createcollection_']";
	public static String NEW_FOLDER_IN_GLOBAL_ADD = "css=td[id^='lconn_files_comm_actions_createcommfolder_']";
	public static String UPLOAD_FILE_IN_GLOBAL_NEW = "css=td[class='dijitReset dijitMenuItemLabel'][id^='lconn_files_action_uploadfile_']";
	public static String UploadFiles_Button = "//button[@class='lotusBtn' and @title='Upload files from your computer']";
	public static String ComFilesAdd_Button = "css=button[id^='lconn_files_action_additem_'][role='button']";
	public static String ComFilesNewUpload = "css=tr[id^='lconn_files_comm_actions_createcommfiles_'][widgetid^='lconn_files_comm_actions_createcommfiles_']";
	public static String ComFilesAddFiles_Button = "css=button[id^='lconn_files_comm_actions_sharefiles_']";
	public static String ComFilesOverviewAddFiles_Button = "link=Add Files";
	public static String ComFilesOverviewAddFirstFile_Button = "link=Add Your First File";
	public static String ComFilesNewFolder = "css=td[id^='lconn_files_comm_actions_createcommfolder']";
	public static String LinkToconnectionsFilesUpload= "css=span:contains(My Computer)";
	public static String NewFolder_Button = "css=button.lotusBtn:contains(New Folder)";
	public static String PICKER_SWITCHER = "css=div[id^='lconn_share_widget_LotusDialog_'] div[class='lconnPickerSourceSwitchingArea'] span[class='lconnPickerSourceLabelSpan']:contains(My Computer)";
	public static String AddtionalSection_Button = "css=a[id^='additionalOptions_']";
	public static String AddButton = "//input[@value='Add Folders'] | //input[@value='Create']";
	public static String AddFolders_Button = "css=button.lotusBtn:contains(Add Folders),ul.lotusInlinelist li a:contains(Add Your First Folder),ul.lotusInlinelist li a:contains(Add Folders)";
	public static String AddFoldersOverview_Button = "link=Add Folders";
	public static String sortByViewsButton = "css=div.lotusSort a:contains(Views)";
	public static String UploadFiles_Tag = "css=input[id^='lconn_share_widget_TagTypeAhead_']";
	public static String UploadFiles_Name = "css=input[class='lotusText lotusLtr']";
	public static String Upload_Button = "css=input[type='submit'][value='Upload'][class='lotusFormButton']";
	public static String DownloadButton = "css=button:contains(Download)";
	public static String DownloadFileLink = "css=a[id^='lconn_files_action_downloadfile_']";
	public static String DownloadAnyWayLink = "//a[contains(text(),'Download Anyway')]";
	public static String DownloadActionMenuOption = "css=td.lconnDownloadable";
	public static String PinFileNewPinIcon = "css=div[dojoattachpoint='streamNode'] a.lconnPinnedToggle div.lconnSprite";
	public static String PinFile = "css=div[dojoattachpoint='streamNode'] a.lconnPinnedToggle img.lconnSprite";
	public static String PinFile_FileOverlay = "css=a[class='actionLink'][title='Pin this file']";
	public static String LikeFile = "css=div[dojoattachpoint='streamNode'] a.lotusLikeCount img.lotusIconLike";
	public static String PopupLikeFile = "css=div.lotusLike a.lotusLikeAction";
	public static String RecommendFile = "css=a[id^=TOGGLE_com_ibm_oneui_controls_Like_]";
	public static String AddATagToFile = "link=Add Tags";
	public static String EnterTag = "css=input[id^='fileTags_']";
	public static String SaveTag = "css=input[type='submit']";
	public static String AddACommentLink = "css=a[dojoattachevent='onclick:createComment']";
	public static String EnterTheComment = "id=addCommentBody";
	public static String Messagediv = "css=div.lotusMessage.lotusConfirm > span";
	public static String ActionTwist = "css=img.lconnSprite.lconnSprite-iconContext";
	public static String ClickForActions = "css=button.lotusBtn:contains(More Actions)";
	public static String MoreButton = "css=a:contains(More)";
	public static String ClickForActionsOptionStopFollowing = "css=tbody[class='dijitReset'] tr:contains(Stop Following)";
	public static String ClickForActionsOptionFollow = "css=tbody[class='dijitReset'] tr:contains(Follow)";
	public static String ClickForActionsOptionMoveToTrash = "css=tbody[class='dijitReset'] tr:contains(Move to Trash)";
	public static String ClickForActionsOptionRestore = "css=tbody[class='dijitReset'] tr:contains(Restore)";
	public static String ClickForActionsOptionDelete = "css=tbody[class='dijitReset'] tr:contains(Delete)";
	public static String ClickForActionsOptionEditProp = "css=tbody[class='dijitReset'] tr:contains(Edit Properties)";
	public static String ClickForActionsOptionTransferOwnership = "css=tbody[class='dijitReset'] tr:contains(Transfer Ownership)";
	public static String DownloadLink = "css=a:contains(Download)";
	public static String DownloadAllLink = "link=Download All Files";
	public static String FirstCheckbox = "css=#list_0";
	public static String FileListCheckbox = "css=input[id^='list_']";
	public static String CommunityViewTrashLink = "//span[@id='navCommunityTrash'] | //a[@class='lotusNowrap']";
	public static String MoveToTrashButton = "css=button.lotusBtn:contains(Move to Trash)";
	public static String MoveToFolderButton = "css=button[class='lotusBtn'][id^='lconn_files_action_bulkmove_']";
	public static String MoveToActionMoreLink = "css=div[id='scene-body'] a[role='button'][id^='lconn_files_action_movecollection_']";
	public static String TrashLinkinNav = "css=div[id='lconnSideNavBody'] a[id='trash']";
	public static String EmptyTrash = "css=button.lotusBtn:contains(Empty Trash)";
	public static String MyFolderLink = "css=a[href='/files/app/folders/personal']";
	public static String CreateFolderName = "css=input[id$='name']";
	public static String CreateFolderDescription = "css=textarea[id$='description']";
	public static String CreateFolderPublic = "css=input[id$='visibility_public']";
	//public static String MyFilesInNav = "css=div.lotusMenuSection ul li a:contains(My Files)"; --Selector no longer in use--
	public static String MyFilesInNav = "css=.bidiSTT_URL";
	public static String MyFilesTitleLink = "css=h1[id='scene-title']>a:contains(My Files)";
	public static String PublicFilesInNav = "css=div#lconnSideNavBody a#public";
	public static String SharedWithMeInNav = "css=div.lotusMenuSection ul li a:contains(Shared With Me),a[id='withme'] span:contains(Shared With Me)";
	public static String MyFilesViewMoreLink = "css=td.lotusAlignRight a:nth-child(1)";
	public static String AddToFoldersLink = "css=td ul li a:contains(Add to Folders)";
	public static String MenuAddToFolder = "css=td:contains(Add to Folder)";
	public static String ChooseFolder = "css=input[id$='recentFolders_0']";
	public static String AddToFoldersButton = "css=input[value='Add to Folders']";
	public static String nextLinkTop = "css=div[class='lotusPaging'][dojoattachpoint='topPageNode'] a[title='Next page']:contains(Next)";
	public static String previousLinkTop = "css=ul[dojoattachpoint='topPageNavigateNode'] a[title='Previous page']";
	public static String nextLinkBottom = "css=div[class='lotusPaging'][dojoattachpoint='bottomPageNode'] a[title='Next page']:contains(Next)";
	public static String pathToDownloads = "/seleniumserver/downloads";
	public static String editPropertiesName = "css=tbody tr td input[id$='_name']";
	public static String editPropertiesDesc = "css=tbody tr td textarea[id$='_description']";
	public static String selectViewDetail = "css=tbody tr td div a[aria-label='Customizable']";
	public static String selectViewList = "css=tbody tr td div a[aria-label='List']";
	public static String selectViewGrid = "css=tbody tr td div a.lotusTile.viewOff";
	public static String viewDetailIsActive = "css=tbody tr td div a.lotusSummary.viewOn";
	public static String viewListIsActive = "css=tbody tr td div a.lotusDetails.viewOn";
	public static String viewGridIsActive = "css=tbody tr td div a.lotusTile.viewOn";
	public static String nameLinkInUploadDialog = "css=input[dojoattachpoint='nameInput']";
	public static String transferOwnershipDialogBox = "xpath=//div[@aria-label='Transfer Ownership']/ancestor::div[starts-with(@id,'lconn_share_widget')][not(contains(@style,'display: none;'))]";
	public static String shareButton = "css=button[id^='lconn_files_action_sharefile_']";
	public static String shareDropDown = "css=a[id^='lconn_files_action_share_']";
	public static String shareInDropDown = "css=td[id='lconn_files_action_sharefile_0_text']";
	public static String shareLink = "css=a[id^='lconn_files_action_sharefile_']";
	public static String ComShareButton = "css=input[value='Share Files']";
	public static String shareFolderButton = "css=button[id^='lconn_files_action_sharecollection_'], a[id^='lconn_files_action_sharecollection_']";
	public static String moreActionsFolderButton = "css=button[id^='lconn_files_action_more_']";
	public static String deleteFolder = "css=td[id^='lconn_files_action_deletecollection_']";
	public static String DeleteButton = "css=input[value='Delete Folder']";
	public static String shareWithEveryone = "css=input[value='public'][type='radio']";
	public static String everyoneCanEditTheFolder = "css=input[name*='_shareCollectionPublicAuth']";
	public static String selectShow10 = "css=a[title='Show 10 items per page']";
	public static String MyDriveLeftMenu="css=a[id='menu_fileSync_label']";
	public static String MyFoldersLeftMenu= "css=div[id='lconnSideNavBody'] a[id^='menu_myfolders_label']";
	public static String AllFoldersLeftMenu= "css=div[id='lconnSideNavBody'] a[id^='menu_allfolders_expandLink'][class*='lotusTwistyClosed']";
	public static String FoldersLeftMenu= "css=div[id='lconnSideNavBody'] a[id^='menu_myfolders_expandLink'][class*='lotusTwistyClosed']";
	public static String PinnedFilesLeftMenu= "css=.lotusMenuSection ul li a:contains(Pinned Files)";
	public static String PinnedFoldersLeftMenu= "css=.lotusMain .lotusColLeft .lotusInner a:contains(Pinned Folders)";
	public static String RefinePinnedFoldersLeftMenu= "css=.lotusMain .lotusColLeft .lotusInner div[id='lconn_share_widget_Node_0'] div[name='header']";
	public static String DisplayList = "css=a[title='Include the description and social metadata for each file']";
	public static String FolderAccessNoOne = "css=input[title='(shared with me only)']";
	public static String FolderAccessPeopleGrpComm = "css=input[title='(give specific permissions to others)']";
	public static String FolderAccessPublic = "css=input[title='(shared with everyone)']";
	public static String FilesCommentTextArea = "css=div[id='mentionstextAreaNode_0']";
	public static String FilesCommentTextField = "css=body[class^='cke_editable']";
	public static String addFileToFolder = "//div[@dojoattachpoint='streamNode']//a[starts-with(@id, 'lconn_files_action_addtocollection')] | //div[@dojoattachpoint='streamNode']//a[starts-with(@id,'lconn_files_comm_actions_addtocollection')]";
	public static String addToFolder = "css=input[title^='Add this file to the selected folder']";
	public static String DialogmovetoButton = "css=div[id^='lconn_share_widget_Dialog_'] input[id^='submit_button'][class='lotusFormButton']";
	public static String openMyFilesView = "css=div[id='lconnSideNavBody'] a[id='myfiles']";
	public static String AllFilesView = "css=div[id='lconnSideNavBody'] a[id='menu_allfiles_expandLink'][class*='lotusTwistyClosed']";
	public static String chooseAFile = "css=[role='button'][title='Choose a File']";
	public static String browseForFile = "css=[role='button'][title='Browse...'], [type='button'][value='Browse...']";
	public static String filesOption = "css=a>strong:contains(Files)";
	public static String filesSharedWithMe = "css=div[id='lconnSideNavBody'] a[id='withme']";
	public static String filesPinnedFolders = "css=td>a:contains(Pinned Folders)";
	public static String Browse_Button = "css=span.lconnUploadContainer button.lotusBtn";
	public static String uploadedFileIcon = "css=img.lconnFileUploadIcon";
	public static String fileElements = "css=div[dojoattachpoint='streamNode'] tr[dndtype='file']";
	public static String folderElements = "css=div[dojoattachpoint='streamNode'] tr[dndtype='folder']";
	public static String addOrRemoveTagsLink = "link=Add or Remove Tags";
	public static String moreLink = "link=More";
	public static String hideLink = "link=Hide";
	public static String okButton = "css=input[value='OK']";
	public static String fileRenameDialog = "css=div[class='lotusDialogContent _qkrDialogCompact']";
	public static String fileUpload = "css=input[value='Upload']";
	public static String uploadMyComputer = "css=input[id$='_option_mycomputer']";
	public static String genericMore = "css=a[id^='lconn_files_action_more_']";
	public static String genericMoveToTrash = "css=td[id^='lconn_files_comm_actions_deletefile_']";
	public static String shareFileDialogInputBox = "css=#lconn_share_widget_MemberInput_0_people";
	public static String UploadAFileButton = "css=span.lotusBtn a[aria-label='Upload Files']";
	public static String LibraryFileInputField = "css=input[type='file'][id^='qkrLW_label_']";
	public static String CheckInButton = "css=input[type='submit'][value='Check In']";
	public static String LibraryFileInput = "css=input[type='file'][id^='qkrLW_label_']";
	public static String FileCheckbox = "css=div.lconnPickerStream input[aria-label='%s'], div.checkbox[title='%s'] input[id$='_checkbox']";
	public static String inputFileName = "css=input[id='quickSearch_simpleInput']";
	public static String selectSearch = "css=input[id='quickSearch_submit']";
	public static String getBrowseButton = "css=span.lconnUploadContainer > button.lotusBtn, span.lconnUploadContainer > input[class='lotusBtn'], input.fieldFileNode";
	public static String moreActions = "css=button[id='lconn_files_action_more_0']";
	public static String AddToFolderOption = "css=td[id='lconn_files_comm_actions_addtocollection_0_text']";
	public static String StopFollowingOption = "css=td[id='lconn_files_action_togglefollowingfile_0_text']";
	public static String FollowingOption = "css=td[id='lconn_files_action_togglefollowingfile_0_text'],a[id^='lconn_files_action_togglefollowingfile_']";
	public static String EditPropertiesOption = "css=td[id='lconn_files_action_editfile_0_text']";
	public static String AddCommentOption = "css=td[id='lconn_files_action_addcomment_0_text']";
	public static String LockFileOption = "css=td[id='lconn_files_action_lockfile_0_text']";
	public static String LockFileOption_ext = "css=td[id^='lconn_files_action_lockfile_']";
	public static String MoveToTrashOption = "css=td[id='lconn_files_comm_actions_deletefile_0_text']";
	public static String FolderTitleDropdownMenu = "css=div[role='button'][id^='lconn_files_action_title_more_']";
	public static String FolderBreadcrumbNewFolderOption = "css=table[role='menu'][id^='dijit_Menu_'] td[class='dijitReset dijitMenuItemLabel'][id^='lconn_files_action_createsubcollection_']";
	public static String FolderBreadcrumbAddFilesOption = "css=table[role='menu'][id^='dijit_Menu_'] td[class='dijitReset dijitMenuItemLabel'][id^='lconn_files_action_addfilestocollection_']";
	public static String FolderBreadcrumbMovetoOption = "css=table[role='menu'][id^='dijit_Menu_'] td[class='dijitReset dijitMenuItemLabel'][id^='lconn_files_action_movecollection_']";
	public static String FolderBreadcrumbShareOption = "css=table[role='menu'][id^='dijit_Menu_'] td[class='dijitReset dijitMenuItemLabel'][id^='lconn_files_action_sharecollection_']";
	public static String FolderBreadcrumbStopingFollowingOption = "css=table[role='menu'][id^='dijit_Menu_'] td[class='dijitReset dijitMenuItemLabel'][id^='lconn_files_action_togglefollowingfolder_']";
	public static String FolderBreadcrumbFollowOption = "css=table[role='menu'][id^='dijit_Menu_'] td[class='dijitReset dijitMenuItemLabel'][id^='lconn_files_action_togglefollowingfolder_']";
	public static String FolderBreadcrumbEditPropertiesOption = "css=table[role='menu'][id^='dijit_Menu_'] td[class='dijitReset dijitMenuItemLabel'][id^='lconn_files_action_editcollection_']";
	public static String FolderBreadcrumbDeleteOption = "css=table[role='menu'][id^='dijit_Menu_'] td[class='dijitReset dijitMenuItemLabel'][id^='lconn_files_action_deletecollection_']";
	public static String FolderBreadcrumbAddToMyDriveOption = "css=table[role='menu'][id^='dijit_Menu_'] td[class='dijitReset dijitMenuItemLabel'][id^='lconn_files_action_addcollectionto']";
	public static String CopyToCommunity = "css=td[id='lconn_files_action_copyfile_0_text']";
	public static String navCommunityFiles= "css=span[id^=navCommunityFiles]";
	public static String navCommunityFolders = "css=span[id^=navCommunityFolders]";
	public static String navCommunityTrash = "css=span[id^=navCommunityTrash]";
	public static String ComFolderTab = "css=a[id='folders_0_link']";
	public static String fileComment = "css=div[class='lotusPostDetails']";
	public static String fileUpdationTimestamp = "css=tr[dndelementtitle='PLACEHOLDER'] li.lotusFirst";
	public static String fileRenameMsg = "css=span[id^='lconnUpload'][id$='status_msg']";
	public static String filesMoreActionsBtn = "css=div[dojoattachpoint='streamNode'] a[title='More Actions']";
	public static String FileOverlayMoreActions = "css=span[id*='_DropDownButton_'][title='More Actions'] > span[class='dijitReset dijitInline dijitIcon dropdown-menu-icon']";
	public static String FileOverlayMoreActionsFollow = "css=td[class*='dijitMenuItemLabel']:contains(Follow)";
	public static String FileOverlayClose = "css=li[class*='ics-viewer-action-close'] > div > a";
	public static String FileOverlayDownload = "css=li[class*='ics-viewer-action-download'] > div > a";
	public static String FileOverlayLike = "css=li[class*='ics-viewer-action-like'] > div.unchecked > a";
	public static String FileOverlayUnlike = "css=li[class*='ics-viewer-action-like'] > div.checked > a";
	public static String FileOverlayCommentsTab = "css=li[id=comments]";
	public static String FileOverlayCommentInputBox = "css=iframe[class^='cke_wysiwyg_frame'][title='Comment text area']";
	public static String FileOverlayCommentPost = "css=li[class='ics-viewer-first'] a[class='save-button']";
	public static String fileOverlayImagePreview = "css=div[class='ics-viewer-image-preview']";
	public static String myfiles ="css=a#myfiles";
	public static String fileForThisCommunityMsg = "Files for This Community";
	public static String shareWithPeople = "css=input[value='people'][type='radio']";
	public static String PersonCommunityDropDown = "css=select[id='lconn_share_widget_MemberInput_0_searchSourceDropdown']";
	public static String ReaderEditorDropDown = "css=select[id='lconn_share_widget_MemberInput_0_roleDropdown']";
	public static String TypeHeadCommunity = "css=li[id='lconn_share_widget_MemberInput_0_communities_popup0']";
	public static String AllowOthersToShareFilesCheckBox = "css=input[id='lconn_files_widget_UploadFile_0_shareFilePropagate']";
	public static String shareFileDialogCommunityInputBox = "css=input[id='lconn_share_widget_MemberInput_0_communities']";
	public static String sharingTab = "css=a[id='share_link']";
	public static String shareFolderDialogPersonTypeahead = "css=li[id^='lconn_share_widget_MemberInput_'],span[class='bhcPeopleTypeAheadUserName']";
	public static String sharingTabLinks = "css=td a[class='lotusAction']";
	public static String sharingTabTable = "css=table[class='lotusVertTable']";
	public static String shareFolderDialogPersonInputField = "css=input[id^='lconn_share_widget_MemberInput']";
	public static String shareFolderDialogShareButton = "css=input[id='submit_button']";
	public static String myDrive = "css=h1 a[aria-label='My Drive']";
	public static String myDriveFolder = "xpath=//div[@id='menu_fileSync']/following-sibling::div[@id='menu_fileSync_childContainer']";
	public static String addFilesMenu = "css=td[id^='lconn_files_action_addfilestocollection_']:contains(Add Files...)";
	public static String addFileButton = "css=input[type=submit][value='Add Files']";
	public static String notSecureForm_accept = "css=button[id='proceed-button']";
	//File Viewers
	public static String previewButton = "css=button:contains(Preview)";
	public static String myFilename = "css=h4 a[title='PLACEHOLDER']";
	public static String sharingAddPeopleComm = "css=a[title='Add People or Communities']";
	public static String sharingtypeoption = "xpath=//label[text()='Member Type']/following-sibling::select";
	public static String sharingcommunityname = "xpath=//input[@title='Type to find PLACEHOLDER']";
	public static String sharingbutton = "css=div.actionContainer.actionButton > a[title='Share with this person']";
	public static String pickerMenu = "css=[id^=compactpicker_select]:not([disabled])";
	public static String copyLinkText="css=input[id='shareLinkInput']";
	public static String copyShareLink="css=input[data-dojo-attach-point='linkInput']";
	// MT
	public static String sharingTabInFiDO = "css=#share";
	public static String stopSharingExternallyLink = "css=div[data-dojo-attach-point='makeInternalContent'] a";
	public static String makeFileInternalPrompt = "css=div[class$='dijitFocused'] div[class='prompt-container']";
	public static String okOnPrompt = "css=#ok";
	public static String changeLink = "link=Change";
	public static String makeFolderInternalPrompt = "css=div[class$='dijitFocused']";
	public static String makeFolderInternal = "css=input[value='Make Internal']";
	public static String folderActionDropDown = "css=div[title='PLACEHOLDER folder action menu'] > img.lotusArrow.lotusDropDownSprite";
	public static String folderShareLink = "css=tbody.dijitReset > tr[aria-label='Share... ']";
	public static String folderShareType = "css=select[title=Type]";
	public static String FolderShareSubmitButton = "css=input#submit_button";
	public static String FolderSharePersonCommunityName = "css=input[title='PLACEHOLDER']";
	public static String FolderSharePersonSearchList = "css=ul > li[dojoattachpoint=resultsNode]";
	public static String FolderSharePersonCancel = "xpath=//input[@id='cancel_button'][@class='lotusFormButton']";
	public static String FolderSharesearchlinkDropdown = "xpath=//div/ul/li[text()='Person not listed? Use full search...']";
	public static String FolderLeftList = "css=div#menu_myfolders_childContainer > div > div > div > div[dndelementtitle=PLACEHOLDER]";
	// Component pack
	public static String recentView = "css=#recentview";
	public static String filterField = "css=input[title='Search'][placeholder^='Type'],input[title='Search'][placeholder^='Filter']";
	public static String recentLabel = "xpath=//div[text()='Recent']";
	public static String filesBelongingToLabel = "xpath=//div[text()='Files belonging to...']";
	public static String newButtonDropdown = "css=div[id^='lconn_files_action_createitem'] td[class$='dijitMenuItemLabel']";
	public static String recentHistoryView = "css=div[class='recentList recentListDisplay recentGridDisplay']";
	public static String recentHistoryPersonTitle = "css=.lconn_profileInfo a.lconn_title";
	public static String recentHistoryFileNames = "css=div[class='recentItems'] div[class*='recentItemTitle'] a[href*='files']";
	public static String recentHistoryFileCards = "css=div[class='recentItems']";
	public static String folderIcon = "css=div[class='itemColumn'] svg";
	public static String fileIcon = "css=div[class='itemColumn'] img";
	public static String searchAllContentBtn = "css=button[class='searchBtn lotusBtn']";
	public static String userProfileImage = "css=img[class='lconn_userImage']";
	public static String folderAboutLink = "css=#about_link";
	//Version Tab
	public static String versionsLink = "xpath=//a[contains(text(),'Versions')]";
	public static String uploadNewVersionLink = "xpath=//a[contains(text(),'Upload New Version...')]";
	public static String downloadVersionLink = "xpath=//span[@class='action download']//a[@title='Download this version']";
	public static String restoreVersionLink = "xpath=//span[@class='action restore']//a[@title='Restore this version']";
	public static String deleteVersionLink = "xpath=//span[@class='action delete']//a[@title='Delete this version']";
	public static String userDetailsArea = "css=div.ics-panel-entry.bidiAware.emptyContent.version.ics-viewer-last";
	//About Tab
	public static String aboutLink = "css=li[title='About']";
	public static String addDescriptionLink = "xpath=//a[contains(text(),'Add a description')]";
	public static String addDescriptionArea = "css=div textarea[id^='fileviewer']";
	public static String addDescriptionSaveBtn = "css=div.commentActions.descriptionBox > ul > li > a.save-button";
	public static String addTagLink = "xpath=//a[contains(text(),'Add tags')]";
	public static String addTagArea = "css=td.typeAheadTd > input[type=text]";
	public static String inputTag = "css=input[title='Tags:']";
	public static String addTagSaveBtn = "css=a[class='save-tag-button']";
	public static String likesTag = "xpath=//span[contains(text(),'Likes')]";
	public static String getLinks = "xpath=//a[contains(text(),'Get Links...')]";
	public static String linksToFile = "xpath=//label[contains(text(),'Link to file:')]";
	public static String linksToPreviousFile = "xpath=//label[contains(text(),'Link to preview file:')]";
	public static String linksToDownloadFile = "xpath=//label[contains(text(),'Link to download file:')]";
	public static String closeButton = "css=a#ok";
	public static String fileTOAlert = "css=div[role=alert] > div > span";
	public static String fileTOUserClose = "xpath=//a/img[@alt='Remove PLACEHOLDER']";
	public static String fileTOTagTooLongError = "xpath=//div[contains(text(),'is too long.')]";
	public static String fileTransferOwnershipTagHelpLink = "xpath=//a[contains(@widgetid , 'lconn_share_widget_HelpLauncher_')]";
	public static String fileTransferOwnershipDialogClose = "css=a.lotusDialogClose";
	public static String fileTransferOwnershipDialogTagHelpText = "xpath=//div[contains(@id,'lconn_share_widget_HelpLauncher_')][@class='lotusHelpHeader']";
	public static String fileTransferMessage = "xpath=//div/span[text()='PLACEHOLDER1 was successfully transferred to PLACEHOLDER2.']";
	public static String fileAddedtoFolderMessage = "css=img.lotusIcon.lotusIconMsgSuccess";
	public static String fileSharedwithMe = "xpath=//div/span[text()='Shared With Me']";
	public static String fileLockedMessage = "The file is now locked.";
	public static String fileUnlockedMessage = "The file is now unlocked.";
	public static String PinMessage = "You pinned this file.";
	public static String UnPinMessage = "You have unpinned this file.";
	public static String MenuItem_1 = "Download as PDF";
	public static String MenuItem_2 = "Stop Following";
	public static String MenuItem_3 = "Lock File";
	public static String MenuItem_4 = "Give Copy to Community...";
	public static String MenuItem_5 = "Transfer Ownership...";
	public static String MenuItem_6 = "Refresh";
	public static String MenuItem_7 = "Move to Trash";
	
	//File Basic Locators
	public static String fileMyDriveExpand = "css=a[title='Expand My Drive'][class*='lotusTwistyClosed']";
	public static String fileMyDriveCollapse = "css=a[title='Collapse My Drive'][class*='lotusTwistyOpen']";
	public static String fileFolderCollapse = "css=a[title='Collapse Folders'][class*='lotusTwistyOpen']";
	public static String fileFolderExpand = "css=a[title='See your folders'][class*='lotusTwistyClosed']";
	public static String fileMyDrive = "css=a[id='menu_fileSync_label']:contains(My Drive)";
	public static String fileFolderCreatedMsg = "css=div[class='lotusMessageBody'] span:contains(Successfully created )";
	public static String folderNavPanel = "css=div[class='lotusColLeft']";
	public static String folderNavClosePanel = "css=a[id='navigationView']";
	public static String fileRefineView = "css=a[title='Refine this view'][id='filterView']";
	public static String fileRefineViewOption = "css=span:contains(PLACEHOLDER)";
	public static String fileRefineViewLeftOption = "css=span[class='lotusLeft']";
	public static String fileRefineViewOptionDisabled = "css=span[class*='disabledFilter']:contains(PLACEHOLDER)";
	public static String fileRefineViewLeft = "css=a[class='lotusLeft']";
	public static String fileFolderList = "xpath=//div[starts-with(@id,'lconn_share_widget_FolderThumbnail_')]";
	public static String fileTags = "css=span[id='lconnTagCloudFilter_titleSpan']:contains(Tags)";
	public static String fileTagsCollapse = "css=a[id='lconnTagCloudFilter_expandLink'][title='Collapse the tags filter']";
	public static String fileDatestatus = "css=span[id*='_titleSpan']";
	public static String filePublicTagCollapse = "css=a[id='lconnTagCloudFilter_expandLink'][title='Collapse the public tags filter']";
	public static String filePublicTag = "css=span[id='lconnTagCloudFilter_titleSpan']:contains(Public Tags)";
	public static String filePFolderPanelIcon = "css=a[id='navigationView']";
	public static String filePinnedFile = "css=a[id='pinnedfiles']";
	public static String fileSharedViewExpand = "css=span[class='lotusLeft'][title*='I have shared with']:contains(Shared)";
	public static String fileCommunityFileLink = "css=a[id='communityFiles']";
	public static String filePublicFileLink = "css=a[id='public']";
	public static String filePublicTagsExpand = "css=a[id='lconnTagCloudFilter_expandLink'][class*='lotusTwistyOpen']";
	public static String fileTrashLink = "css=a[id='trash']";
	public static String fileFilterIconDisabled = "css=a[id='filterView'][class*='toolBarActionDisable']";
	
	//Language Selector
	public static String getSyncButton = "//button[@id='lotusSyncInstallButton']";
	public static String recent = "//div[@id='recentviewNav']//span[text()='Recent']";
	
	//CNX8UI
	public static String filesAndFoldersSecTopNav = "//div[@id='tertiary_level_nav']//span[text()='Files and Folders']";
	public static String communityFilesSecTopNav = "//div[@id='tertiary_level_nav']//span[text()='Community Files']";
	public static String publicFilesSecTopNav = "//div[@id='tertiary_level_nav']//span[text()='Public Files']";
	public static String trashSecTopNav = "//div[@id='tertiary_level_nav']//span[text()='Trash']";
	public static String leftNavigation = "//div[@style='display: block;']//div[@class='lotusBottomCorner']/div[@class='lotusInner']";
	public static String expandFiles = "#menu_filescnx8_expandLink";
	public static String expandFolders = "#menu_myfolders_expandLink";
	public static String fileChildTable = "#menu_filescnx8_childContainer";
	public static String folderChildTable = "#menu_myfolders_childContainer";
	public static String fileChildItems = "#menu_filescnx8_childContainer div[name='node'] div[name='title']>span";
	public static String folderChildItems = "#menu_myfolders_childContainer div[name='node'] div[name='title']>span";
	public static String myFiles = "//div[@id='menu_filesnavcnx8_childContainer']//div[@name='title']/span[text()='My Files']";
	public static String confirmationPopUp = "//h1[text()='Confirm']//ancestor::form";
	public static String downloadBulkFilesLink = "button[id^='lconn_files_action_downloadbulkfiles_'][aria-disabled='PLACEHOLDER']";
	public static String shareFilesLink = "button[id^='lconn_files_action_sharefiles_'][aria-disabled='PLACEHOLDER']";
	public static String addToBulkFilesLink = "button[id^='lconn_files_action_bulkaddtocollection_'][aria-disabled='PLACEHOLDER']";
	public static String addTagsLink = "button[id^='lconn_files_action_addtags_'][aria-disabled='PLACEHOLDER']";
	public static String transferFilesLink = "button[id^='lconn_files_action_transferfiles_'][aria-disabled='PLACEHOLDER']";
	public static String moveToTrashFilesLink = "button[id^='lconn_files_action_deletefiles_'][aria-disabled='PLACEHOLDER']";
	public static String selectAllCheckBox = "//input[@id='list_selectall']";
	public static String myFilesSubMenuLink = "//div[@name='title']/span[text()='My Files']";
	public static String pinnedFilesSubMenuLink = "//div[@name='title']/span[text()='Pinned Files']";
	public static String sharedwithmeSubMenuLink = "//div[@name='title']/span[text()='Shared With Me']";
	public static String emptyMessage = "//div[@id='emptyMsg']";
	public static String aboutLinkAtFooter = "//a[contains(text(),'About')]";
	public static String fileLinkAtAboutPage = "//a[contains(text(),'Files')]";
	public static String moveHereButton = "input[type=submit][value='Move Here']";
	public static String saveButton =  "input[type=submit][value='Save']";
	public static String successMessage = "//div[contains(@id,'controls_MessageBox')]//span[@data-dojo-attach-point='msgBody']";
	public static String localSearchPanelOnFiles =  "//input[@title='Search' and @placeholder ='Filter by typing the name of a person or recent file or folder' or @placeholder ='Type the name of a person to view their shared files.']";
	public static String recentLink =  "//span[contains(text(),'Recent')]";
	public static String folderActionItems = "//div[starts-with(@id,'lconn_files_action_title_more')]//table//tr";
	public static String newFolderActionMenu = "//div[starts-with(@id,'lconn_files_action_title_more')]//table//tr[@aria-label='New Folder... ']";
	public static String newFolderDialoguebox = "//input[@aria-invalid='true']/ancestor::form";
	public static String breadCrumb = "//div[@dojoattachpoint='breadcrumbShownNodes']//li";
	public static String gridView = "tbody tr td div a[aria-label='Grid View']";
	public static String breadCrumb_ParentNode = "//div[@dojoattachpoint='breadcrumbShownNodes']//li[1]//div[contains(@class,'lconnBreadcrumbitem')]";
	public static String breadCrumb_ChildNode = "//div[@dojoattachpoint='breadcrumbShownNodes']//li[2]//div[@class='lconnBreadcrumbitem lconnBreadcrumbnode']";

	private FilesUIConstants() {}

}
