package com.ibm.conn.auto.webui.constants;

import com.ibm.conn.auto.data.Data;

public final class HomepageUIConstants {

	public static final String mentionUserSelector = "css=div[id^='bhc_PeopleTypeAheadMenu_'][class='dijitReset dijitMenuItem lastOption dijitMenuItemSelected']";
	public static String profilePhoto  = "css=#hpUserPhoto a";
	public static String User_Navbar_AccountSettingsMenu = "css=span[id='logoutLabel'][aria-label*='Log in'], div[id*='usersMenu'][class*='user'][class*='navmenu']";
	public static String homepage = "css=#lotusBannerHomepage a";
	public static String HPLeftNavLink = "css=div ul li a:contains";
	public static String ActionRequired = HPLeftNavLink+"(Action Required)";
	public static String MyNotifications = HPLeftNavLink+"(My Notifications)";
	public static String Administration = HPLeftNavLink+"(Administration)";
	public static String AdministrationCnx8 = "div[id='tertiary_level_nav'] li.lconnHomepageAdmin a";
	public static String Mentions = HPLeftNavLink+"(Mentions)";
	public static String ImFollowing = HPLeftNavLink+"(I'm Following)";
	public static String HomepageImFollowing = "css=#imFollowing";
	public static String TabDescription = "css=#asDesc";
	public static String StatusUpdates = "css=#statusUpdates";
	public static String Discover = "css=#discover";
	public static String ImFollowingTab = "css=a[id='imFollowing']";
	public static String StatusUpdatesTab = "css=a[id='statusUpdates']";
	public static String DiscoverTab = "css=a[id='discover']";
	public static String AtMentionsTab = "css=a[id='atMentions']";
	public static String ForMeTab = "css=a[id='forme']";
	public static String FromMeTab = "css=a[id='fromme']";
	public static String ActionRequiredTab = "css=a[id='actionRequired']";
	public static String SavedTab = "css=a[id='saved']";
	public static String VisitorSavedTab = "css=div[aria-label='Activity Stream Header Menu'] li a[id='saved']";
	public static String Updates = "css=a[id='_myStream']:contains(Updates)";
	public static String AdministrationHomepageTitle = "//h1[contains(text(),'Home Page')]";
	public static String Saved = "css=div ul li a[id='_saved']:contains(Saved)";
	public static String MyPage = "css=li.lconnHomepageMyPage a";
	public static String MyPageCnx8 = "div[id='tertiary_level_nav'] li.lconnHomepageMyPage a";
	public static String GettingStarted = "link=Getting Started";
	public static String leftNavMenu = "css=div[id='homepageLeftNavigationMenu']";
	public static String WidgetsCustomize = "css=a#paletteLink";
	public static String WidgetsSettingIcon = "div[id='myPageCustomizer']";
	public static String WidgetAdded = "css=span[dojoattachpoint='itemAddedTextHolder']:contains(application added), p[dojoattachpoint='itemAddedTextHolder']:contains(application added)";
	public static String ClosePalette = "css=a#closePalette";
	public static String ViewActivityEntries = "css=a:contains('View new entries in your high priority activities')";
	public static String HelpFrameName = "HelpFrame";
	public static String HelpFrame_ContentFrameName = "ContentFrame";
	public static String HelpFrame_ContentFrame_ContentViewFrameName = "ContentViewFrame";
	public static String HelpIFrame = "css=iframe.topicVieverIFrame";
	public static String HelpPageTitle = "css=h1[class='title topictitle1']";
	public static String AddAnotherWidget = "css=a:contains(Add another widget), a:contains(Add another app)";
	public static String OpenSocialRadioButton = "css=input[id='isGadget']";
	public static String WidgetTitleText = "id=widgettitle";
	public static String WidgetUrlText = "id=widgeturl";
	public static String DisplayOnWidgetsPage = "id=widgettab_widget";
	public static String DisplayOnUpdatePage = "id=widgettab_update";
	public static String Save = "link=Save";
	public static String DisabledWidgetsList = "id=disabledWidgetsSelect";
	public static String EnabledWidgetsList = "id=enabledWidgetsSelect";
	public static String Enable = "link=Enable";
	public static String IFrame = "css=iframe[id*='__gadget_']";
	public static String ClickStatusUpdateLink = "css=*[class='lotusStatusInput']";
	public static String EnterStatusUpdate = "css=div[id='cke_1_contents']";
	public static String EnterMentionsStatusUpdate = "css=div[id^='mentionstextAreaNode_']";
	public static String Post = "css=div[class='lotusPostAction asLinkContainer']";
	public static String SaveStatusUpdate = "css=input[class='lotusFormButton']";
	public static String PostStatus = "css=a[class='ublogPost lotusPersonInactive']";
	public static String PostStatusUpdate = "css=a[class='ublogPost']";
	public static String EE_Header = "css=div.lotusWrapper div.lotusFlyoutHeader";
	public static String StartABlog = "css=div span a:contains(Start a Blog)";
	public static String BlogsNameField = "css=input[id='name']";
	public static String BlogsAddressObject = "css=input[id='handle']";
	public static String BlogsTags = "css=input[id='tagsAsString']";
	public static String BlogsDescription = "css=textarea[id='description']";
	public static String FilterBy = "css=span select[aria-describedby$='asFilterDescription'], span select[aria-labelledby$='asFilterDescription']";
	public static String FilterActivities = "Activities";
	public static String FilterBlogs = "Blogs";
	public static String FilterBookmarks = "Bookmarks";
	public static String FilterCommunities = "Communities";
	public static String FilterWikis = "Wikis";
	public static String FilterFiles = "Files";
	public static String FilterForums = "Forums";
	public static String FilterTags = "Tags";
	public static String FilterSU = "Status Updates";
	public static String FilterAll = "All";
	public static String FilterContacts = "Contacts";
	public static String FilterSurveys = "Surveys";
	public static String FilterEvents = "Events";
	public static String FilterForms = "Forms";
	public static String FilterDocs = "Docs";
	public static String FilterAllContent = "All Content";
	public static String FilterProfiles = "Profiles";
	public static String FilterSelectAFilter = "Select a filter";
	public static String RemoveSavedStory = "css=input.lotusFormButton[value='Remove']";
	public static String ActionRequiredBadge = "css=#lconn_homepage_as_badge_ActionRequiredBadge_0";
	public static String ActionRequired_HideSuccessMsg_NewsStoryRemoval = "css=div[id*='_MessageItem_']:contains('" + Data.SuccessfulDelFromActionRequiredList + "') > a[class='lotusDelete']";
	public static String Activities_Tab = "link=Activities";
	public static String Start_An_Activity = "css=div span a:contains(Start an Activity)";
	public static String Start_An_Activity_InputText_Name = "css=input#lconn_act_ActivityForm_0_titleInput";
	public static String Start_An_Activity_InputText_Tags = "css=input#lconn_act_ActivityForm_0tagz";
	public static String Start_An_Activity_Cancel = "css=div.lotusFormFooter input[dojoattachevent='onclick:cancel']";
	public static String Add_Entry_Cancel = "css=div.lotusFormFooter input[dojoattachevent='onclick:callCancel']";
	public static String Start_An_Activity_Textarea_Activity_Goals = "css=textarea#lconn_act_ActivityForm_0_descriptionInput";
	public static String Start_An_Activity_InputSelect_MemberType = "css=select[title='Member Type']";
	public static String Start_An_Activity_InputSelect_MemberRole = "css=select[title='Member Role']";
	public static String Start_An_Activity_InputText_Members_PeopleTypeAhead = "css=input#lconn_core_PeopleTypeAhead_0";
	public static String Start_An_Activity_Members_TypeaheadPromptList = "css=#lconn_core_PeopleTypeAhead_0_popup";
	public static String usersActivitySearchIdentifier = Start_An_Activity_Members_TypeaheadPromptList + "_searchDir";
	public static String selectedActivityUserIdentifier = "css=*[id$='lconn_core_PeopleTypeAhead_0_popup'] li:nth(1)";
	public static String ActivityHome_ExpandActivityDetails_TopActivity = "css=td[class^=lotusAlignRight]:nth(0) a";
	public static String ActivityOutline_More_ExpandDescription = "link=... [more]";
	public static String Members = "link=Members";
	public static String ChangeAccess = "css=a[title='Change Access']";
	public static String scChangeAccess = "//a[contains(text(),'(Change)')]";
	public static String CheckPublic = "css=input[id$='publicAccess']";
	public static String SaveAccessChange = "css=div.lotusDialogFooter input[value='Save']";
	public static String ActivityOutline = "link=Activity Outline";
	public static String AddToDo = "css=span.lotusBtn a:contains('Add To Do Item')";
	public static String ToDoMoreOptions = "css=a span[dojoattachpoint='moreOptionsText_AP']";
	public static String ToDo_InputText_Title = "css=input[id^=lconn_act_ToDoForm_][id$=title]:nth(0)";
	public static String ToDo_Assign_Person = "css=a:contains('Choose a person')";
	public static String ToDo_Assign_FilterBox = "css=#lconn_core_FilteringCheckbox_0FilterTextbox";
	public static String ToDo_Assign_CheckBox = "css=input[type='radio'][id^='lconn_core_FilteringCheckbox_']";
	public static String MarkPrivateToDo = "css=input#lconn_act_ToDoForm_0privateCheck";
	public static String EEPopupFrameIdentifer = "xpath=//*[contains(@name, '__gadget_gadget')]";
	public static String EECommentsTab = "css=a[role='tab']:contains(Comments)";
	public static String EEUsername = "css=span.vcard a.fn:contains";
	public static String EEUserPopupClose = "css=a.lotusPopupClose img";
	public static String EELike = "//div[@class='lotusChunk gadgetActions']//a[starts-with(@id,'TOGGLE')] | //a[starts-with(@id,'TOGGLE')]";
	public static String EELikeUndo = "css=a:contains(Unlike), a[id^='TOGGLE_com_ibm_social_ee_widget_Recommendation_']:contains(Unlike)";
	public static String EEReadmore = "css=a:contains(Read more ...)";
	public static String EEHistoryTab = "css=a[id='com_ibm_social_ee_gadget_BlogEntry_0_historyTabLink']";
	public static String EEFilesCommentsTab = "css=li[id$='_commentsTab'] a:contains(Comments)";
	public static String EEMentionsCommentField = "css=div[id^='mentionstextAreaNode_']";
	public static String EECommentField = "css=textarea[id^='com_ibm_social_ee_widget_Comments_']";
	public static String EECommentPost = "css=a[role='button']:contains(Post)";
	public static String EEFilesHistoryTab = "css=a:contains(Recent Updates)";
	public static String EERepliesTab = "css=a[role='tab']:contains(Replies)";
	public static String EE_ImagePreview = "css=div[id*='_imgPrev'] > div > a[id*='_image_previewLink'] > img";
	public static String OpenEEPostCommentButton = "css=div[class='lotusActions eeActions'] > ul[class*='lotusLeft'] > li[class='lotusFirst'] > a";
	public static String OpenEECancelCommentButton = "css=div[class='lotusActions eeActions'] > ul[class*='lotusLeft'] > li > a[class='keepFocus']";
	public static String Preview = "css=div.lotusChunk ul li a:contains(Preview)";
	public static String Download = "css=div.lotusChunk ul li a:contains(Download)";
	public static String FollowFileButton = "css=div.gadgetActions a:contains(Follow File)";
	public static String StopFollowFileButton = "css=div.gadgetActions a:contains(Stop Following)";
	public static String findOneBlogEntry_Comment = "css=a[id='com_ibm_social_ee_gadget_BlogEntry_0_commentsTabLink']:contains('Comments (1)')";
	public static String MyNotificationBadge = "css=span[id^='lconn_homepage_as_badge_MyNotificationsBadge_']";
	public static String MentionsBadge = "css=span[id^='lconn_homepage_as_badge_MentionsBadge_']";
	public static String NotificationCenter_Badge = "css=div[class^='icBanner-badge']";
	public static String postedEventTitle = "css=div.lotusPostContent div.lotusPostAction:contains(PLACEHOLDER)";
	public static String discoverTab = "css=a[id='discover']";
	public static String SaveThisLink = "css=div[class='lotusMeta lotusChunk'] > ul[class='lotusInlinelist lotusActions'] > li[class='lotusFirst'] > a:nth(0)";
	public static String MoreSavedLinkInactive = "css=div[aria-label*='PLACEHOLDER'] > div[class='lotusPostContent'] > div[class*='lotusMeta'] > ul > li > ul > li > a[title*='Saved']";
	public static String NewsStoryXLinkById = "css=li[id='PLACEHOLDER'] > div[class*='activityStreamNewsItemContainer'] > div[class='lotusPostContent'] > a";
	public static String NewsStoryElementById = "css=li[id='PLACEHOLDER']";
	public static String NewsStoryActiveLinksDivById = NewsStoryElementById + " > div[class*='activityStreamNewsItemContainer'] > div[class='lotusPostContent'] > div[class*='lotusMeta']";
	public static String NewsStoryMoreSaveThisLinkById = NewsStoryElementById + " > div[class*='activityStreamNewsItemContainer'] > div[class='lotusPostContent'] > div[class*='lotusMeta'] > ul > li[class='moreActions'] > ul > li[class*='savethisAction'] > a";
	public static String NewsStoryMoreLinkById = NewsStoryElementById + " > div[class*='activityStreamNewsItemContainer'] > div[class='lotusPostContent'] > div[class*='lotusMeta'] > ul > li[class='actionMoreLink'] > a";
	public static String NewsStorySaveThisLinkById = NewsStoryElementById + " > div[class*='activityStreamNewsItemContainer'] > div[class='lotusPostContent'] > div[class*='lotusMeta'] > ul > li[class*='savethisAction'] > a";
	public static String NewsStoryInnerDiv = "css=div[aria-label*='PLACEHOLDER']";
	public static String Entry_More_Link = NewsStoryInnerDiv + " > div[class='lotusPostContent'] > div[class='lotusMeta lotusChunk'] > ul > li[id*='actionMoreLink'] a";
	public static String Entry_Saved_Link = NewsStoryInnerDiv + " > div[class='lotusPostContent'] > div[class='lotusMeta lotusChunk'] > ul  li[class*='savethis'] > a[title*='Saved']:nth(0)";
	public static String Entry_SaveThis_Link = NewsStoryInnerDiv + " > div[class='lotusPostContent'] > div[class='lotusMeta lotusChunk'] > ul  li[class*='savethis'] > a";
	public static String StopFollowing_Link = NewsStoryInnerDiv + " > div[class='lotusPostContent'] > div[class='lotusMeta lotusChunk'] > ul > li[class*='stopfollowing'] > a";
	public static String IMFollowingEntry_Comment_Link = NewsStoryInnerDiv + " > div[class='lotusPostContent'] > div[class='lotusMeta lotusChunk'] > ul > li[class*='commentAction'] > a";
	public static String CommunityInvite_SaveThis_Link = NewsStoryInnerDiv + " > div[class='lotusPostContent'] > div[class='lotusMeta lotusChunk'] > ul > li[class*='savethis'] > a";
	public static String CommunityInvite_Decline_Link = NewsStoryInnerDiv + " > div[class='lotusPostContent'] > div[class='lotusMeta lotusChunk'] > ul > li[class*='declinethisinvitation'] > a";
	// My Notifications
	public static String CommunityInvite_Join_Link = NewsStoryInnerDiv + " > div[class='lotusPostContent'] > div[class='lotusMeta lotusChunk'] > ul > li[class*='jointhiscommunity'] > a";
	//Notification Center
	public static String NotificationCenterBtn = "css=img[class*='Notification'], div[id*='notificationsMenu_'] > div[class='navmenu-button'] > div[class='nav-icon']";
	public static String NotificationCenterFlyout = "css=div[id*='as_notification_NotificationsFlyout_']";
	public static String NotificationCenterDisplayed = "css=.icBanner-notif-center";
	public static String NotificationCenterHidden = "css=.icBanner-notif-center.lotusHidden";
	public static String NotificationCenterHeader = "css=.icBanner-popver-header";
	public static String NotificationCenterFooter = "css=a.icBanner-footer-link";
	public static String NotificationCenterProfilePic = "css=.icNotification-post-inner img.icNote-authorImg";
	public static String NotificationCenterTitleLink = "css=.icNote-title a";
	public static String NotificationCenterBlueDot = "css=span[data-dojo-attach-point='bluedot']";
	public static String NotificationCenterFooterDiv = "css=div.icBanner-popover-footer";
	public static String NotificationCenter_Tile = "css=div[id*='NotificationsItem'][aria-label*='PLACEHOLDER']";
	public static String NotificationCenter_BlueDot = NotificationCenter_Tile + " > div > div > div[class='icNote-message'] > span[class='bluedot']";
	public static String NotificationCenter_Tile_ProfilePic = "css=img[class*='authorImg']";
	//New Search Panel
	public static String SearchPanelOpenIcon = "css=div#searchNode.icSearchPaneButton";
	public static String SearchPanelTextBox = "css=input#dijit_form_TextBox_2,div[class='icSection icTopSection'] input";
	public static String SearchPanelAllContentLink = "css=a.icGlobalScope.icSelectedScope";
	public static String SearchPanelSearchIcon = "css=div#lconn_search_searchPanel_SearchBar_1.icSearchBar a.icSearchIcon";
	public static String SearchPanelSearchIcon_2 = "css=div[id='commonSearchControlContainer']>a";
	public static String SearchPanelSearchIconHomePage = "css=a[class='icSearchIcon'][title='Search']:first-child";
	public static String SearchedContentDropdownList = "//div[@class='pfDirectoryResults lconnSearchHighlight']//span[contains(text(),'PLACEHOLDER1')]/../../../..//a";
	public static String SearchedContentLoginMessage = "//div[@class='pfDirectoryResults']//div[@class='lconn_gray']";
	public static String SCExpectedLoginMessage = "Log in to see more results including Files, Wikis, Communities and more.";
	//File Details Dialog
	public static String fileDetailsBody = "css=div.fileBody:contains(PLACEHOLDER)";
	public static String fileDetailsTags_Element = fileDetailsBody + " > div.fileDetails > div.fileMeta > ul.inlineSepList > li.fileTags";
	public static String fileDetailsTags = fileDetailsTags_Element + ":contains(Tags: REPLACE_THIS)";
	public static String fileDetailsIcon = fileDetailsBody + " > a.fileIcon > img[title='PLACEHOLDER']";
	public static String fileDetailsAuthor = fileDetailsBody + " > div[class='fileDetails'] > div > ul > li[class='fileAuthor']:contains(REPLACE_THIS)";
	public static String toolTipCloseButton = "css=#close-tooltip";
	//Cloud only navbar selectors
	public static String communitynavbar ="css=#communitiesMenu_container";
	public static String morelink ="css=#servicesMenu_container";
	public static String activityundermoremenu = "css=a.activities";
	public static String activityinavbar ="css=.activities";
	public static String filesundermoremenu ="css=a.files";
	public static String filesinavbar ="css=.files";
	public static String meetingsundermoremenu ="css=a.joinmeeting";
	public static String meetingsinavbar = "css=.joinmeeting";
	public static String commentsInsideEvent = "css=div[class='lotusPostContent bidiAware ']";
	//My Profile Business card
	public static String userNamelink = "xpath=//a[@class='fn url lotusPerson bidiAware']";
	public static String userSurNamelink = "css=a[class='fn url lotusPerson bidiAware'] b:contains(PLACEHOLDER)";
	public static String bizCard = "css=#cardTable";
	public static String bizCardUsersName = "css=#cardTable div[class='lotusPersonInfo'] h2 span";
	public static String bizCardUserName = "css=div[class='lotusPersonInfo'] h2 span";
	public static String bizCardUserEmail = "css=div[class='lotusPersonInfo'] p>a";
	public static String bizCardProfileLink = "css=#cardTable a:contains(Profile)";
	public static String bizCardCommunitiesLink = "css=#cardTable a:contains(Communities)";
	public static String bizCardforumsLink = "css=#cardTable a:contains(Forums)";
	public static String bizCardBlogsLink = "css=#cardTable a:contains(Blogs)";
	public static String bizCardActivitiesLink = "css=#cardTable a:contains(Activities)";
	public static String bizCardFilesLink = "css=#cardTable a:contains(Files)";
	public static String bizCardBookmarksLink = "css=#cardTable a:contains(Bookmarks)";
	public static String bizCardWikisLink = "css=#cardTable a:contains(Wikis)";
	public static String bizCardMoreActionsLink = "xpath=//div[@class='lotusPersonActions']//a[contains(text(),'More Actions')]"; //"css=#cardTable a:contains(More Actions)";
	public static String bizCardInviteToMyNetwork= "xpath=//a[text()='Invite to My Network']";//"css=#cardTable a:contains(Invite to My Network)";
	public static String bizCardSendInvite = "a>*[data-mui-test='user--followIcon']";
	public static String bizCardRemoveInvite = "a *[id='Remove-From-Network']";
	public static String bizCardUserJobTitle = "p[class='title bidiAware']";
	public static String bizCardDisabledInvite = "a>*[data-mui-test='user--adminIcon']";
	public static String bizCardPhoneNumber = "p[class='tel']";
	public static String bizCardChatIcon = "li[class='lotusFirst']>a[id='javlinFooterActionChat']";
	public static String bizCardEmailIcon = "ul[class='lotusInlinelist'] a[title='Send Email']";
	public static String bizCardVerticalEllipsisIcon = "a[class='dropbtn']";
	public static String bizCardProfilePicture = "div[class='lotusPhoto photo']";
	public static String bizCardDownloadVcard = "//div[@class='dropdown-content show']/a[@title='Download vCard']";
	public static String bizCardExportVcardForm = "//form[@id='exportVcardDialogForm']";

	
	//div[@id="mouse-over-popover"]//div[@class="MuiGrid-root MuiGrid-container"]//span[@class="MuiIconButton-label"]/*[@data-mui-test="emailIcon"]
	//table[@id="cardTable"]
	public static String activityStreamNewsStory = "css=div[aria-label*='PLACEHOLDER']";
	public static String mentionedUserLinkInEvent = activityStreamNewsStory+" span[class='vcard'] a:contains('@')";
	public static String addAFilePopUp = "css=div[data-dojo-attach-point=containerNode]";
	public static String URLLink="css=body[class^='cke_editable'] a:contains('PLACEHOLDER')";
	// Video File Attached To Status Update CSS selectors
	private static String SU_VIDEOFILEATTACHMENT_ALL_COMPONENTS = NewsStoryInnerDiv + " > div[class='lotusPostContent'] > div[class*='lotusPostDetails'] > div[class='videoPreview'] > div";
	public static String SU_VIDEOFILEATTACHMENT_CONTENT_METADATA = SU_VIDEOFILEATTACHMENT_ALL_COMPONENTS + " > div[class='lconnPreviewContent'] > div[class='fileMeta']";
	public static String SU_VIDEOFILEATTACHMENT_CONTENT_TITLE = SU_VIDEOFILEATTACHMENT_ALL_COMPONENTS + " > div[class='lconnPreviewContent'] > div[class='lconnPreviewContentTitle']";
	public static String SU_VIDEOFILEATTACHMENT_THUMBNAIL = SU_VIDEOFILEATTACHMENT_ALL_COMPONENTS + " > div[class='lconnPreviewLeft'] > a[class*='lconnPreviewCenter']";

	public static String ShowPreviousComments = NewsStoryInnerDiv + " > ul > li > div > span > a[dojoattachpoint='showPreviousLink']";
	public static String CancelComment_Unique = NewsStoryInnerDiv + " > ul[id*='_InlineComments_'] > li[id*='_CommentInputCkeMentions_'] > form > div[class='lotusActions'] > ul[class*='lotusLeft'] > li > a[dojoattachpoint='commentCancelBtn']";
	public static String ShowMoreCommentContent_Unique = NewsStoryInnerDiv + " > ul > li[id*='InlineComment']:contains('REPLACE_THIS') > div > div[class='lotusPostContent'] > div[class='lotusPostDetails'] > div[dojoattachpoint='showMoreText'] > a";
	public static String ShowMoreSUContent_Unique = NewsStoryInnerDiv + " > div[class='lotusPostContent'] > div[class=''][dojoattachpoint='showMoreText'] > a";
	public static String SharedExternally_AddComments_WarningMessage = NewsStoryInnerDiv + " > ul > li[id*='SharedExternallyComments'] > div > div:contains('" + Data.VisitorModel_CommentWarningMsg  + "')";
	public static String SharedExternally_AddComments_WarningIcon = NewsStoryInnerDiv + " > ul > li[id*='SharedExternallyComments'] > div > img[class*='SharedExternal']";
	public static String SharedExternally_ActivityEntryLink = NewsStoryInnerDiv + " div[class*='lotusPostAction'] span[class^='bidiAware'] a[title='Open original item']";
	public static String SharedExternally_ExternalUserLink = NewsStoryInnerDiv + " > div[class='lotusPostContent'] > div[class*='lotusPostAction'] span[class='vcard']";
	public static String PostComment_Unique = NewsStoryInnerDiv + " > ul[id*='_InlineComments_'] > li[id*='_CommentInputCkeMentions_'] > form > div[class='lotusActions'] > ul[class*='lotusLeft'] > li[class='lotusFirst'] > a";
	public static String StatusCommentLink_Unique = NewsStoryInnerDiv + " > div[class='lotusPostContent'] > div[class*='lotusMeta'] > ul > li[class='commentAction'] > a";
	public static String NewsStoryAddMemberLink = NewsStoryInnerDiv + " > div[class='lotusPostContent'] > div[class*='lotusMeta'] > ul > li[class*='addmemberAction'] > a";
	public static String NewsStoryJoinThisCommunityLink = NewsStoryInnerDiv + " > div[class='lotusPostContent'] > div[class*='lotusMeta'] > ul > li[class*='jointhiscommunityAction'] > a";
	public static String NewsStoryTimeLink = NewsStoryInnerDiv + " > div[class='lotusPostContent'] > div[class*='lotusMeta'] > span > [class='timeago']";
	public static String DeleteSUCommentXIcon = NewsStoryInnerDiv + " > ul > li[id*='_InlineComment_'] > div:contains('REPLACE_THIS') > a[aria-label='Delete comment']";
	public static String NewsStoryInnerDiv_FileNewsStory = NewsStoryInnerDiv + "[aria-label*='REPLACE_THIS']";
	public static String NewsStoryInnerDiv_FileNewsStory_Image = "css=div[class='lotusPostContent'] > div[class*='lotusPostDetails'] > div[class='lotusPostObject'] > img[title='PLACEHOLDER']";
	public static String NewsStoryInnerDiv_FileNewsStory_Timestamp = "css=div[class='lotusPostContent'] > div[class*='lotusMeta'] > span > [class='timeago']";
	public static String NewsStoryHashTag_Outer = "css=div[class='lotusPostContent'] > div[class*='lotusPostAction'] > span[class*='bidiAware']:contains('PLACEHOLDER') > a[tag='REPLACE_THIS']";
	public static String NewsStoryHashTag_Comment = "css=div[class='lotusPostContent'] > div[class='lotusPostDetails'] > div:contains('PLACEHOLDER') > a[tag='REPLACE_THIS']";
	public static String NewsStoryHashTag_Inner_Or_Mentions = "css=div[class='lotusPostContent'] > div[class*='lotusPostAction'] > div[class*='activityStreamSummary'] > div[class*='lotusPostContent']:contains('PLACEHOLDER') > a[tag='REPLACE_THIS']";
	public static String DeleteStatusUpdateConfirm = "css=input.lotusFormButton[value='Delete']";
	public static String SavedView = "css=#saved";
	public static String ActionReqView = "css=#actionRequired";
	public static String My_Page = "link=My Page";
	public static String AtMentions = "css=a[id='_atMentions']";
	public static String scUpdates = "css=a[id='_myStream']";
	public static String scSaved = "css=#_saved";
	public static String tourWelcomePopupClose = "css=button[id='close-tooltip']";
	public static String AS_Widget_Actions_Menu = "css=div[class='lotusSectionHeader']:contains('PLACEHOLDER') > div > div > a[title='Actions']";
	public static String AS_Widget_Actions_Menu_Link = "css=table[id*='dijit_Menu_'] > tbody > tr[id*='dijit_MenuItem_'] > td[id*='dijit_MenuItem_'][id*='_text']:contains('PLACEHOLDER')";
	public static String genericWidgetId = "css=div[class='lotusWidget homepage-widget dojoDndItem']";
	public static String ClickForActions = "css=a[class^=lotusIcon]";
	public static String scMyNotifications = "css=#_myNotifications";
	public static String scActionRequired = "css=#_actionRequired";
	public static String scGettingStarted = "css=li.lconnHomepageGettingStarted > a";
	public static String welcomeToHclConTitle = "css=span[id='gettingStartedTitle']";
	public static String PostArea = "css=div#mentionstextAreaNode_0";
	public static String PostLink = "css=a.ublogPost";
	public static String HomepageMyNotifications = "css=#_myNotifications";
	public static String Sc_HomepageMyNotifications = "css=#myNotifications";
	public static String HomepageMyNotificationsAtMentionsArea = "css=#mentionstextAreaNode_0";
	public static String HomepageMyNotificationsFilterMenu = "css=span#com_ibm_social_as_filter_FilterMenu_0.asFilterMenu";
	public static String Sc_HomepageMyNotificationsFilterMenu = "css=#com_ibm_social_as_filter_FilterMenu_1";
	public static String HomepageMyNotificationsActivityStream = "css=#activityStreamHeader";
	public static String HomepageActivityStreamTitle = HomepageMyNotificationsActivityStream + " .shareSome-title";
	public static String HomepageMyContentPage = "css=a[title='Custom View']";
	public static String HomepageMyPageBookmarks = "css=.dojoDndItem[aria-label='Bookmarks']";
	public static String HomepageMyContentPageBlogs = "css=.dojoDndItem[aria-label='Blogs']";
	public static String HomepageMyContentPageMyFiles = "css=.dojoDndItem[aria-label='My Files']";
	public static String HomepageMyContentPageCommunities = "css=.dojoDndItem[aria-label='Communities']";
	public static String HomepageMyContentPageProfiles = "css=.dojoDndItem[aria-label='Profiles']";
	public static String HomepageMyContentPageLatestWikis = "css=.dojoDndItem[aria-label='Latest Wikis']";
	public static String HomepageNotficationsFilter = "css=span#com_ibm_social_as_filter_FilterMenu_1 select";
	public static String HomepageNotficationsFromMeTab = "link=From Me";
	public static String HomepageBannerPage = "css=#lotusBannerHomepage a";
	public static String HomepageSearchField = "css=#searchNodesearchInput .lotusText";
	public static String HomepageSearchButton = "css=.lotusSearchButton";
	public static String HomepageSearchResultsPage = "css=#contentContainer_results_View_CenterPaging .lotusFirst";
	public static String HomepageSearchResultsEmptyPage = "css=.lconnEmpty>span";
	public static String HomepageEmptySearchPage = "css=.lconnEmpty span";
	public static String AdvancedSearchFiltersSearch = "css=#filterComponents";
	public static String AdvancedSearchFieldSearch = "css=fieldset table";
	public static String AdvancedSearchKeywordsSearch = "css=#advancedQuery";
	public static String AdvancedSearchTagSearch = "css=#tagCatcher";
	public static String AdvancedSearchPeopleSearch = "css=#peopleCatcher";
	public static String SC_AdvancedSearchPeopleSearch = "css=#bhc_PeopleTypeAhead_0";
	public static String AdvancedSearchTitleSearch = "css=#titleQuery";
	public static String AdvancedSearchPageSearchButton = "css=.lotusBtnSpecial";
	public static String HomepageStatusUpdatesMentionsArea = "css=#mentionstextAreaNode_0";
	public static String MentionsTypeaheadSelection = "css=#mentionsTypeaheadNode_0_PersonMentionsType_popup0, div[aria-label='People TypeAhead Menu'], div[aria-label^='lconn_core_PeopleTypeAheadMenu_']";
	public static String MentionsTypeaheadMenuItem = "css=div[id*='_PeopleTypeAheadMenu_'][class*='dijitMenuItem'][role='option']";
	public static String MentionsTypeaheadMenuItemPhoto = "css=div[class*='bhcBizCardFloat'] > img[class='bhcBizCardImg']";
	public static String HomeIcon = "css=a[title='Home'], a[id='ics-scbanner-home']";
	public static String LikeUserLink = "css=ul[id='com_ibm_social_ee_widget_RecommendationPopup_0__recommendNames'] li[id^='com_ibm_social_ee_widget_RecommendationPopup_0__recommendNames__']";
	public static String Ckpt_MyNotifications = "css=a[id='_myNotifications']";
	public static String Ckpt_ActionRequired = "css=a[id='_actionRequired']";
	public static String Ckpt_Saved = "css=a[id='_saved']";
	public static String Ckpt_GettingStarted = "css=li.lconnHomepageGettingStarted > a";
	public static String Ckpt_Updates = "css=a[id='_myStream']";
	public static String UpdatesLink = "css=#myStreamView";
	public static String eventWidget = "css=div[title=Events]";
	public static String eventWidgetFrame = "css=iframe[title='Community Events']";
	public static String addToPersonalCalendar = "Add to Personal Calendar";
	public static String AddtoPersonalCalendarFrame = "css=iframe[title='Community Events'][id^='__gadget_gadget_']";
	public static String AddtoPersonalCalOkButton = "css=input[value=OK]";
	public static String eventWidgetPaging = "css=div#lconn_calendar_Paging_0 div[class=lotusLeft]";
	public static String eventWidgetPagingNextLink = "css=div#lconn_calendar_Paging_0 ul[class='lotusRight lotusInlinelist'] li[dojoattachpoint=nextLinkAP] a";
	public static String eventWidgetOpLink = "css=div.lotusInner div a img";
	public static String eventWidgetPagingPrevLink = "css=div#lconn_calendar_Paging_0 ul[class='lotusRight lotusInlinelist'] li[dojoattachpoint=previousLinkAP] a";
	public static String eventWidgetEditLink = "//table[@id='dijit_Menu_0']//td[text()='Edit']";
	public static String eventWidgetText = "Number of events to show:";
	public static String eventWidgetNumberSel = "css=select[aria-label='Number of events to show:']";
	public static String eventWidgetTypeSel = "css=select[aria-label='Show:']";
	public static String eventWidgetTypeOption1 = "All followed or attending events";
	public static String eventWidgetTypeOption2 = "Attending events";
	public static String eventWidgetTypeOption3 = "Followed events";
	public static String linksineventWidget = "css=div#instanceList tr";
	public static String eventLinkInEventWidget = "css=div#instanceList td[class='eventDiv'] a:contains('REPLACETHIS')";
	public static String eventInEventWidget = "css=td[class='eventDiv'] span:contains('REPLACETHIS')";
	public static String getWidgetActionsSelectors = "css=h2.ibmDndDragHandle div.lotusLeft a";
	public static String popupTable = "css=div[id^=popup] table";
	public static String activeDropdown = "css=div[id$=_dropdown] table[class~=dijitMenuSelected]";
	public static String atMentionTextArea = "css=div[id='mentionstextAreaNode_0']";
	public static String activityStreamNewsItems = "css=ul[id='asPermLinkAnchor'] li[id^='com_ibm_social_as_item_'], ul[id='activityStreamMain'] li[id^='com_ibm_social_as_item_']";
	public static String newsStories = "css=li[id^='com_ibm_social_as_item_NewsItem_']";
	public static String selectEntryLoadEE = "css=div[class='lotusPostIndicator'] > a[title='Show more details about this item'] > img";
	public static String typeAheadBox = "css=ul[id='mentionsTypeaheadNode_0_PersonMentionsType_popup']";
	public static String meetingsWidget = "css=div[id*='_container'] > div[class='lotusSectionHeader'] > div[class='lotusInner'] > h2:contains('Meetings')";
	public static String meetingsWidgetIframe = "css=iframe[title='Meetings']";
	public static String joinMeetingBtn = "css=#joinMtg";
	public static String hostMeetingBtn = "css=#hostMeeting";
	public static String eventsWidget = "css=div[id*='_container'] > div[class='lotusSectionHeader'] > div[class='lotusInner'] > h2:contains('Events')";
	public static String eventsWidgetIframe = "css=iframe[title='Community Events']";
	public static String eventsGadgetDiv = "css=#gadgetDiv";
	public static String recommendationsWidet = "css=div[id*='_container'] > div[class='lotusSectionHeader'] > div[class='lotusInner'] > h2:contains('Recommendations')";
	public static String recommendationsWidgetContent = "css=div[id^='lconn_sand_RecommendWidget'][id$='welcomeNode']";
	public static String recommendationsWidgetContentText = "css=div[id^='lconn_sand_RecommendWidget'][id$='welcomeNode']>span:contains('There are no current recommendations for you.')";
	public static String recommendationsWidgetContainer = "css=div[dojoattachpoint='recommendContainer'] table tbody";
	public static String MyNetwork = "My Network";
	public static String MyNetworkAndPeopleIFollow = "My Network and People I Follow";
	public static String FilterPeople = "People";
	public static String MyUpdates = "My Updates";
	public static String PeopleIFollow = "People I Follow";
	public static String StatusCommentLink = "css=div.activityStreamNewsItemContainer div.lotusPostContent div.lotusMeta ul.lotusInlinelist li a:nth(2)";
	public static String StatusCommentLinkCommon = "css= div[class*=lotusPost] div[class*=lotusPostContent] li[class='commentAction'] a:contains('Comment')";
	public static String StatusCommentTextArea = "css=[role='textbox'][placeholder='']";
	public static String URLPreview = "css=div[id^='lconn_core_widget_urlPreview_URLPreviewNode_']";
	public static String URLPreview_ThumbnailCheckbox = "css=input[id^='lconn_core_widget_urlPreview_URLPreviewNode_'][id$='_checkbox']";
	public static String URLPreview_Remove = "css=a[role='button'][aria-label='Remove URL Preview']";
	public static String NewsStoryNameLink = "css=div.lotusPostContent div.lotusPostAction span.vcard a.bidiAware";
	public static String EnterStatusUpdate_CR4 = "css=[role='textbox'][placeholder='What are you working on right now?']";
	public static String Refresh = "css=a.asHeaderLink";
	public static String StatusCommentLink_CR4 = "css=div.activityStreamNewsItemContainer div.lotusPostContent div.lotusMeta ul.lotusInlinelist li.lotusActions a:nth(2)";
	public static String StoryPermalink = "css=div.activityStreamNewsItemContainer div.lotusPostContent div.lotusMeta ul.lotusInlinelist li.lotusFirst span a";
	public static String StatusComment_AddAFile = "css=li.lotusFirst a.share-attachAction:nth(0)";
	public static String MyComputer = "css=div[class*='lconnPickerSourceToCheck'] > div[id*='CompactFilePicker'] > span:contains('My Computer')";
	public static String AddAFile_UploadedFileIcon = "css=div[class*='FileUpload'] > img[class*='FileUploadIcon']";
	public static String AddAFile_UploadedFileName = "css=div[class*='FileUploadLabel'] > div > a[class*='FilenameContainer']:contains('PLACEHOLDER')";
	public static String AddAFile_Tags_Input_Field = "css=input[id*='TagTypeAhead'][name*='uploadFileTaggerTypeAhead']";
	public static String Ok = "css=input[value='OK']";
	public static String MyFiles = "css=input[id$='_option_myfiles']";
	public static String MyFilesTab = "css=div[id*='lconn_files_widget'] > span:contains(Files)";
	public static String MyFilesTab_SelectFile_RadioButton = "css=div[class='checkbox'][title='PLACEHOLDER']";
	public static String Saved_CR4 = "css=a#_saved";
	public static String MyNotifications_CR4 = "css=a#_myNotifications";
	public static String SaveStatusUpdate_CR4 = "css=div.lotusPostContent div.lotusMeta ul.lotusInlinelist li.lotusActions a:nth(3)";
	public static String CommunitiesIFollow = "Communities";
	public static String PostComment = "link=Post";
	public static String atMentionsPluginTextArea = "css=div[id='cke_1_contents']";
	public static String EnterMentionsPluginUpdate = "css=div[id^='cke_editor1']";
	public static String StatusUpdateFrame = "css=iframe[class^='cke_wysiwyg_frame']";
	public static String StatusUpdateTextField = "css=body[class^='cke_editable']";
	public static String nameSearchList = "css=div[id^='lconn_core_PeopleTypeAheadMenu_'][class$='searchDirectory '],div[id='lconn_core_PeopleTypeAheadMenu_0_searchDir']";
	public static String NoResultFound = "css=div[id='lconn_core_PeopleTypeAheadMenu_0_resultsNode']";
	public static String StatusUpdatePost = "css=a[class='ublogPost']";
	public static String PostStatusOld = "css=a.ublogPost:contains('Post')";
	public static String URLPreview_EE = "css=.lconnPreviewContent";
	public static String selectFirstItemOnFileList = "css=input#lconn_share_widget_Stream_0_0";
	public static String SelectFirstFileFromFileList = "css=input[id*='lconn_share_widget_Node_0'][type='radio']";
	public static String URLPreview_Thumbnail_ChooseRight = "css=a.lconnPreviewImageChooseRight";
	public static String URLPreview_Thumbnail_ChooseLeft = "css=a.lconnPreviewImageChooseLeft";
	public static String URL_PREVIEW_UPDATE = "//div[contains(@aria-label,'PLACEHOLDER')]//div[contains(@aria-label,'URL Preview - REPLACE_THIS')]";
	public static String URL_PREVIEW_COMMENT = "//div[contains(@aria-label,'USER commented')]//div[contains(@aria-label,'REPLACE_THIS')]";
	public static String URL_PREVIEW_BOARDMESSAGE = "//div[contains(@aria-label,'USER posted')]//div[contains(@aria-label,'REPLACE_THIS')]";
	public static String URLPreview_Thumbnail = "css=div[class='lconnPreviewLeft'] > a[class='lconnPreviewCenter'] > img[aria-label*='PLACEHOLDER']";
	public static String Thumbnail_IBM = "IBM";
	public static String Thumbnail_SkyNews = "Sky News";
	public static String AttachAFile = "css=div.lotusActions ul.lotusInlinelist li.lotusFirst a:contains('Add a File')";
	public static String GenericEEFrame = "css=div[id*=gadget_]>div[id*='gadget-site']>iframe[title='Connections'][id^='__gadget_gadget']";
	public static String SharedExternally_Icon_EE = "css=span[id*='_sharedExternally'] > img[class*='SharedExternal'], span[id*='_SharedExternally_'] > img[class*='SharedExternal']";
	public static String SharedExternally_Icon_FileOverlay = "css=img[title='Shared externally']";
	public static String SharedExternally_Message_EE = "css=span[id*='_sharedExternally'] > span:contains('Shared externally'), span[id*='_SharedExternally_'] > span:contains('Shared externally')";
	public static String SharedExternally_AddComments_WarningIcon_EE = "css=div[class*='lconnSharedExternal'] > img[class*='SharedExternal']";
	public static String SharedExternally_AddComments_WarningIcon_FileOverlay = "css=img[title='" + Data.VisitorModel_CommentWarningMsg + "']";
	public static String SharedExternally_Warning = "css=span[id^='com_ibm_social_as_item_SharedExternally']";
	public static String MentionsWarningMsg = "The following people cannot view this message because they cannot see public updates";
	public static String externalOrgA = "external_users_orga";
	public static String OrgA = "orga";
	public static String OrgB = "orgb";
	public static String Visitor_HomepageIcon = "css=a#gettingStartedVisitorHomepageIcon.gettingStartedVisitorHomepageIcon";
	public static String Visitor_CommunitiesIcon = "css=a#gettingStartedVisitorCommIcon.gettingStartedVisitorCommIcon";
	public static String Visitor_CommunitiesLinkMT = "css=#lotusBannerCommunitiesExternal";
	public static String Visitor_FilesIcon = "css=a#gettingStartedVisitorFilesIcon.gettingStartedVisitorFilesIcon";
	public static String Visitor_FilesLinkMT = "css=#lotusBannerFilesExternal";
	public static String Visitor_HomepageLink = "css=a#gettingStartedVisitorLinkHomepage";
	public static String Visitor_CommunitiesLink = "css=a#gettingStartedVisitorLinkComm";
	public static String Visitor_FilesLink = "css=a#gettingStartedVisitorLinkFiles";
	public static String Visitor_MyNotificationsLink = "css=#gettingStartedVisitorOtherViews > a:nth-child(1)";
	public static String Visitor_ActionRequiredLink = "css=a.gettingStartedVisitorLink:nth-child(2)";
	public static String Visitor_EventsMT = "css=div[class='lotusSectionHeader'] h2:contains(Events)";
	public static String Visitor_RecommendationsMT = "css=div[class='lotusSectionHeader'] h2:contains(Recommendations)";
	public static String HelpFooterLink = "css=div[class='lotusFooter'] > ul > li > a:contains(Help)";
	public static String HelpHeaderLink = "#headerHelpLink";
	public static String HomepageWelcomeText = "h1[class*='welcomePage']";		
	public static String Typeahead_StatusUpdate = "css=div[id^='mentionsTypeaheadNode_0_PersonMentionsType_popup']";
	public static String Typeahead_StatusUpdate_Comment = "css=ul[id^='mentionsTypeaheadNode_'][id$='_PersonMentionsType_popup']";
	public static String UpdatesTabContainer = "css=#com_ibm_social_as_filter_FilterContainer_0 > span:nth-child(1)";
	public static String AS_SearchOpen = "css=.otherActivityStream14-asSearchMag14";
	public static String AS_SearchTextBox = "css=#dijit_form_TextBox_0";
	public static String AS_SearchTextArea = "css=#widget_dijit_form_TextBox_0";
	public static String AS_SearchClose = "css=img.otherActivityStream14.otherActivityStream14-asCloseHover14";
	public static String AS_SearchFind = "css=input.otherActivityStream12.otherActivityStream12-asSearchDark12.icStream-searchSubmit";
	public static String AS_SearchOpenElement = "css=a#asSearchMenuOption";
	public static String StatusUpdatesLink = "link=Status Updates";
	public static String ShowMore = "css=a.streamMore";
	public static String SU_TextArea = "css=[role='textbox'][placeholder='What do you want to share?']";
	public static String ShowMoreSUContent = "css=.lotusPostContent > div:nth-child(2) > a:nth-child(2)";
	public static String ShowMoreCommentContent = "css=.lotusPostDetails > div:nth-child(3) > a:nth-child(2)";
	public static String ClearStatusUpdate = "link=Clear";
	public static String CancelComment = "link=Cancel";
	public static String ManageTags = "css=span.lotusLeft.placeholderHeaderRightSub a";
	public static String TagTextBox = "css=input[id='tagTypeAhead']";
	public static String AddTagBtn = "css=button.lotusBtn.addButton.lotusBtnSpecial";
	public static String AddTagDoneBtn = "css=input.lotusFormButton.submit";
	public static String EEHistoryComment = "css=div.lotusPost.eeCommentContent div.lotusPostAction";
	public static String EEHeading = "css=div.lotusHeadingChunk.eeHeading h1.lotusHeading a";
	public static String EETags = "css=li.lotusFirst.lotusTags";
	public static String EEStatus = "css=div.lotusStatus[id$='_status']";
	public static String EELikeCount = "css=a.lotusLikeCount div.lotusLikeText";
	public static String HomepageMyNotificationsNewTab = "IBM Connections Home Page - My Notifications";
	public static String FileThumbnailContainer = "css=a[title='Play NAME_EXTENSION']";
	public static String RepostAction = "css=li.repostAction a";
	public static String RepostAction_EE = "css=div[class='lotusFlyoutInner'] > div[class*='lotusChunk'] > ul > li > a:contains('Repost')";
	public static String RepostIcon = "css=div[class='lotusPostContent']:contains('PLACEHOLDER') > div[class*='lotusPostAction'] > span[class*='bidiAware'] > span[class='repostIcon'] > img";
	public static String leftNavWikiPageTitleCSSSelector = "css=div[id='sideNav'] > div[class^='lotusNavTree'] > div[id*='WikisNavTree'] > div[id*='_NavigationTreeNode_'] > div[class*='TreeContainer'] > div[id*='_NavigationTreeNode_'] > div > span > a[title*='PLACEHOLDER']";
	public static String URL_PREVIEW_BEFORE_SU_POST_THUMBNAIL_IMAGE = "css=div[class*='lconnPreviewLeft'] > a[class='lconnPreviewCenter']";
	// URL Preview CSS selectors - URL Preview selectors for the URL Preview widget in the EE
	public static String URLPreview_EE_All = "css=div[class='lconnPreview'][aria-label*='PLACEHOLDER']";
	public static String URLPreview_EE_ThumbnailImage = URLPreview_EE_All + " > div[class='lconnPreviewLeft'] > a[class='lconnPreviewCenter']";
	private static String SavedLinkInactive_CommonPath = "div[aria-label*='PLACEHOLDER'] > div[class='lotusPostContent'] > div[class*='lotusMeta'] > ul > li";
	public static String SavedLinkInactive = "css=" + SavedLinkInactive_CommonPath + " > a[title*='Saved']," +  SavedLinkInactive_CommonPath + "[class='moreActions'] > ul > li > a[title*='Saved']";
	private static String SharedExternally_Common = " > div[class='lotusPostContent'] > div[class*='lotusPostAction'] > span[id*='_SharedExternally_']"; // Set to private as this CSS selector does not actually point to any particular usable element
	public static String SharedExternally_Message = NewsStoryInnerDiv + SharedExternally_Common + " > span:contains('Shared externally')";
	public static String SharedExternally_Icon = NewsStoryInnerDiv + SharedExternally_Common + " > img[class*='SharedExternal']";
	// URL Preview CSS selectors - private CSS selectors which use common / re-usable paths that are used in the more specific selectors, below
	private static String URL_PREVIEW_STATUS_UPDATE_BEFORE_POST = "div[aria-label='What do you want to share?'] > div[aria-label*='PLACEHOLDER']";
	private static String URL_PREVIEW_COMMUNITY_STATUS_UPDATE_BEFORE_POST = "div[aria-label='Share a message with the community'] > div[aria-label*='PLACEHOLDER']";
	private static String URL_PREVIEW_BOARD_MESSAGE_BEFORE_POST = "div[aria-label='Write a message on this profile'] > div[aria-label*='PLACEHOLDER']";
	// URL Preview CSS selectors - URL Preview selectors for the URL Preview widget which appears before a status update / global sharebox message / board message is posted
	public static String URL_PREVIEW_BEFORE_SU_POST = "css=" + URL_PREVIEW_STATUS_UPDATE_BEFORE_POST + ", " + URL_PREVIEW_COMMUNITY_STATUS_UPDATE_BEFORE_POST + ", " + URL_PREVIEW_BOARD_MESSAGE_BEFORE_POST;
	private static String URL_PREVIEW_CSS_PATH_TO_THUMBNAIL_CHECKBOX = " > div[class*='lconnPreviewFooter'] > div[class='lconnPreviewImageChooseToggle'] > input[id*='_checkbox']";
	public static String URLPreview_ThumbnailCheckbox_Unique = "css=" + URL_PREVIEW_STATUS_UPDATE_BEFORE_POST + URL_PREVIEW_CSS_PATH_TO_THUMBNAIL_CHECKBOX + ", "
																		+ URL_PREVIEW_COMMUNITY_STATUS_UPDATE_BEFORE_POST + URL_PREVIEW_CSS_PATH_TO_THUMBNAIL_CHECKBOX + ", "
																		+ URL_PREVIEW_BOARD_MESSAGE_BEFORE_POST + URL_PREVIEW_CSS_PATH_TO_THUMBNAIL_CHECKBOX;
	private static String URL_PREVIEW_CSS_PATH_TO_VIDEO_PLAYING = " > a[aria-label*='Video area']";
	// URL Preview CSS selectors - URL Preview selectors for the URL Preview widget which contains a video which has been activated / is playing
	public static String URL_PREVIEW_BEFORE_SU_POST_VIDEO_PLAYING = "css=" + URL_PREVIEW_STATUS_UPDATE_BEFORE_POST + URL_PREVIEW_CSS_PATH_TO_VIDEO_PLAYING + ", " + URL_PREVIEW_COMMUNITY_STATUS_UPDATE_BEFORE_POST + URL_PREVIEW_CSS_PATH_TO_VIDEO_PLAYING + ", " + URL_PREVIEW_BOARD_MESSAGE_BEFORE_POST + URL_PREVIEW_CSS_PATH_TO_VIDEO_PLAYING;
	private static String URL_PREVIEW_CSS_PATH_TO_TOGGLE_RIGHT = " > div[class*='lconnPreviewFooter'] > div[class='lconnPreviewImageChoose'] > a[class='lconnPreviewImageChooseRight']";
	public static String URLPreview_Thumbnail_ChooseRight_Unique = "css=" + URL_PREVIEW_STATUS_UPDATE_BEFORE_POST + URL_PREVIEW_CSS_PATH_TO_TOGGLE_RIGHT + ", " + URL_PREVIEW_COMMUNITY_STATUS_UPDATE_BEFORE_POST + URL_PREVIEW_CSS_PATH_TO_TOGGLE_RIGHT + ", " + URL_PREVIEW_BOARD_MESSAGE_BEFORE_POST + URL_PREVIEW_CSS_PATH_TO_TOGGLE_RIGHT;
	private static String URL_PREVIEW_CSS_PATH_TO_TOGGLE_LEFT = " > div[class*='lconnPreviewFooter'] > div[class='lconnPreviewImageChoose'] > a[class='lconnPreviewImageChooseLeft']";
	public static String URLPreview_Thumbnail_ChooseLeft_Unique = "css=" + URL_PREVIEW_STATUS_UPDATE_BEFORE_POST + URL_PREVIEW_CSS_PATH_TO_TOGGLE_LEFT + ", " + URL_PREVIEW_COMMUNITY_STATUS_UPDATE_BEFORE_POST + URL_PREVIEW_CSS_PATH_TO_TOGGLE_LEFT + ", " + URL_PREVIEW_BOARD_MESSAGE_BEFORE_POST + URL_PREVIEW_CSS_PATH_TO_TOGGLE_LEFT;

	// URL Preview CSS selectors - URL Preview selectors for the URL Preview widget as it appears in the AS (ie. after it is posted)
	public static String URL_PREVIEW_NEWS_FEED = NewsStoryInnerDiv + " > div[class='lotusPostContent'] > div[aria-label*='REPLACE_THIS']";
	public static String URL_PREVIEW_NEWS_FEED_VIDEO_PLAYING = URL_PREVIEW_NEWS_FEED + URL_PREVIEW_CSS_PATH_TO_VIDEO_PLAYING;
	public static String URL_PREVIEW_NEWS_FEED_THUMBNAIL_IMAGE = URL_PREVIEW_NEWS_FEED + " > div[class='lconnPreviewLeft'] > a[class='lconnPreviewCenter']";


	public static String likePostOnDiscover= "//span[contains(text(),'PLACEHOLDER1')]/../..//a[@class='lotusLikeAction'][text()='PLACEHOLDER2']";
	public static String rePostOnDiscover= "//span[contains(text(),'PLACEHOLDER1')]/../..//li[@class='repostAction']/a";
	public static String deleteDiscoverPost="//span[contains(text(),'PLACEHOLDER1')]/../..//a[@class='lotusDelete ']";
	public static String deleteModal="//div[@class='lotusDialogFooter']/input[@class='lotusFormButton submit']";
	public static String actionMoreLink="//span[contains(text(),'PLACEHOLDER1')]/../..//li[@class='actionMoreLink']/a";
	public static String savePost="//span[contains(text(),'PLACEHOLDER1')]/../..//li[@class='moreActions']//li[@class='savethisAction']/a";
	public static String savePostSuccessful="//span[contains(text(),'PLACEHOLDER1')]/../..//li[@class='moreActions']//li[@class='savethisAction activityStreamActionInactive']/a";
	public static String commentOnDiscoverPost="//span[contains(text(),'PLACEHOLDER1')]/../..//li[@class='commentAction']/a";
	public static String discoverComment_iFrame="//span[contains(text(),'PLACEHOLDER1')]/../../..//iframe";
	public static String discoverCommentBody="//body[@aria-label='Add a comment']";
	public static String discoverCommentPost="//span[contains(text(),'PLACEHOLDER1')]/../../..//strong[text()='Post']";
    public static String discoverCommentText="//span[contains(text(),'PLACEHOLDER1')]/../../..//li[@class='lotusCommentItem ']//*[contains(@class,'asLinkContainer ')]";
    public static String postedMentionMessageOnDiscover = "//div[@class='lotusPostAction asLinkContainer']//span[@class='vcard']/a[contains(text(),'PLACEHOLDER1')]/../../../span[contains(text(),'PLACEHOLDER2')]";
    public static String discoverLatestUpdateFilterButton= "span[class='lotusRight'] button[title='Filter content']";
    public static String discoverLatestUpdateSelectedFilter="//div[@id='custom_stream_content_filter']//span[@class='MuiChip-label']";
	public static String discoverLatestUpdateFilterValue = "//div[@id='menu-filter']//li[text()='PLACEHOLDER']";

    public static String linkInpostContents="//div[@class='lotusPostContent']//a[text()='PLACEHOLDER1']";
    public static String postContents="//div[@class='lotusPostContent'][contains(string(),'PLACEHOLDER1')][contains(string(),'PLACEHOLDER2')]";

    public static String likePostOnLatestUpdates= "//div[@class='lotusPostContent'][contains(string(),' PLACEHOLDER1')]/../..//a[@class='lotusLikeAction'][text()='PLACEHOLDER2']";
    public static String rePostOnLatestUpdates= "//div[@class='lotusPostContent'][contains(string(),' PLACEHOLDER1')]/../..//li[@class='repostAction']/a";
    public static String deleteLatestUpdatesPost="//div[@class='lotusPostContent'][contains(string(),' PLACEHOLDER1')]/../..//a[@class='lotusDelete ']";
    public static String actionMoreLinkLatestUpdates="//div[@class='lotusPostContent'][contains(string(),' PLACEHOLDER1')]/../..//li[@class='actionMoreLink']/a";
    public static String savePostLatestUpdates="//div[@class='lotusPostContent'][contains(string(),' PLACEHOLDER1')]/../..//li[@class='moreActions']//li[@class='savethisAction']/a";
    public static String savePostSuccessfulLatestUpdates="//div[@class='lotusPostContent'][contains(string(),' PLACEHOLDER1')]/../..//li[@class='moreActions']//li[@class='savethisAction activityStreamActionInactive']/a";
    public static String commentOnLatestUpdatesPost="//div[@class='lotusPostContent'][contains(string(),' PLACEHOLDER1')]/../..//li[@class='commentAction']/a";
    public static String latestUpdatesComment_iFrame="//div[@class='lotusPostContent'][contains(string(),' PLACEHOLDER1')]/../../..//iframe";
    public static String latestUpdatesCommentBody="//body[@aria-label='Add a comment']";
    public static String latestUpdatesCommentPost="//div[@class='lotusPostContent'][contains(string(),' PLACEHOLDER1')]/../../..//strong[text()='Post']";
    public static String latestUpdatesCommentText="//div[@class='lotusPostContent'][contains(string(),' PLACEHOLDER1')]/../../..//li[@class='lotusCommentItem ']//*[contains(@class,'asLinkContainer ')]";
    public static String personalFilterBtn="//*[@id='custom_stream_personal_filter']//button";
    public static String latestUpdatesImFollowingFilter="//span[@class='MuiButton-label']//span[@class='selectedFilterLabel']";
    public static String latestUpdatesMyNotificationsFilter="//*[@id='menu-filter']//span[text()='My Notifications']";
    public static String latestUpdatesMyNotificationsFilterCount="//*[@id='menu-filter']//span[text()='My Notifications']/..//span[@class='MuiBadge-root notificationBadge']/span";
    public static String latestUpdatesActionRequiredFilter="//*[@id='menu-filter']//span[text()='Action Required']";
    public static String latestUpdatesActionRequiredFilterCount="//*[@id='menu-filter']//span[text()='Action Required']/..//span[@class='MuiBadge-root notificationBadge']/span";
    public static String inviteEEIFrame = "//iframe[@title='Connections']";
    public static String acceptButtonIFrame = "//button[@class='lotusBtn ee_ni_accept ee_ni_button']";
    public static String successMessageOnIframe= "//span[@class='ee_ni_successMsg']";
    public static String repostConfirmation ="//div[@class='repostMessage']";
    public static String secondaryNavigation = "//div[@id='tertiary_level_nav']";
	//Admin Banner
	public static String AdminBanner = "div[id='top-navigation-banner']";
	public static String AdminBannerText = "//p[contains(text(),'PLACEHOLDER')]";
	// Top Updates
	public static String topUpdatesPage = "div[id='top-updates']";
	public static String topUpdatesFilterBar = "div[class='cnx8-filterbar-root']>div[id='ic-web-filterbar']";
	//public static String topUpdatesShareBox="//div[@class='ic-sharebox-container']//div[@class='DraftEditor-editorContainer']";
	public static String topUpdatesShareBox = "//div[@class='ic-sharebox-container']//div[@class='DraftEditor-editorContainer']//div[@class='public-DraftStyleDefault-block public-DraftStyleDefault-ltr']";
	public static String topUpdatesTypeAheadList = "//div[@class='ui-typeahead-container']//div[@title='PLACEHOLDER']";
	public static String topUpdatesPost = "//div[@class='post-btn']";
	//public static String topUpdatesCategoriesDropdown = "//div[@class='MuiInputBase-root MuiInput-root MuiInput-underline categories-select']";
	public static String topUpdatesCategoriesDropdown = "//button[@class='MuiButtonBase-root MuiButton-root MuiButton-text categories-btn']";
	public static String topUpdatesCategoriesMentions = "//li[contains(text(), 'Mentions')]";
	public static String topUpdatesMentionsPost = "//a[contains(text(), 'PLACEHOLDER1')]/../../..//div[contains(text(), 'PLACEHOLDER2')]";
	public static String topUpdatesCategoriesResponses = "//li[contains(text(), 'Responses')]";
	public static String topUpdatesLike = "//a[contains(text(), 'PLACEHOLDER1')]/../../..//div[contains(text(), 'PLACEHOLDER2')]/../..//button[@title='Like']";
	public static String topUpdatesUnlike = "//a[contains(text(), 'PLACEHOLDER1')]/../../..//div[contains(text(), 'PLACEHOLDER2')]/../..//button[@title='Unlike']";   
	public static String topUpdatesComment = "//a[contains(text(), 'PLACEHOLDER1')]/../../../../../..//div[contains(text(), 'PLACEHOLDER2')]/../..//button[@class='ic-icon-comment']";
	public static String topUpdatesCommentBox = "//div[@class='ic-comment-textarea']";
	public static String topUpdatesCommentText = "//div[@class='ic-comment-entry']//div[contains(text(), 'PLACEHOLDER')]";
	public static String topUpdatesCommentPost = "//div[@class='ic-comment-form-post-btn btn-active']";
	public static String topUpdatesLink = "div[id='tertiary_level_nav']>li[id='topUpdatesView']>a[id='_topUpdates']";
	public static String topUpdatesFilterIcon = "button[id='filterIconCNX8']";
	public static String filterbarTypeaheadContainer = "div[class='filterbarTypeaheadContainer']>div[id='ic-web-filterbar-ta']";
	public static String topUpdatesFilterSearchBox = "div[class='searchContainer']>div>div[class='searchBox']";
	public static String filterContentList = "div[class='ui-typeahead-primary ui-typeahead-ellipsis']";
	public static String filterTextClearIcon = "div[class='closeIconClass']>div[class='ic-web-filter-options ic-web-close']";
	public static String filterContentHeader = "div[id='ic-web-filterbar-ta-header']";
	public static String filterIconToClickToApplyFilter = "div[class='searchContainer']>div>button[class='MuiButtonBase-root MuiIconButton-root searchIcon']";
	public static String filterChipsLables = "div[class='MuiChip-root MuiChip-deletable']>span[class='MuiChip-label']";
	public static String filterChipsDeleteIcons = "div[class='MuiChip-root MuiChip-deletable']>svg[class='MuiSvgIcon-root MuiChip-deleteIcon']";
	public static String filteredArticleTitles= "//div[@class='ic-article-body']//a[@class='ic-title'][contains(text(), 'PLACEHOLDER')]";
	public static String latestUpdatesCategoriesMentionsFilter = "//span[contains(text(),'Mentions')]";
	public static String latestUpdatesCategoriesSavedFilter = "//span[contains(text(),'Saved')]";
	public static String ActionRequiredBadgeNew = "//button[@title='Filter stream']//span[@class='MuiBadge-root notificationBadge']//span[@class='MuiBadge-badge MuiBadge-anchorOriginTopRightRectangle MuiBadge-colorPrimary']";
	public static String fileInNewsStoryPreviewlink = "//a[contains(@title,'Preview this file in a new window.')]";


	//Navigation Bar
	public static String navigationBarText = "//span[contains(text(),'PLACEHOLDER')]";
	public static String topNaviagtionLogoPosition = "//div[@class='right-area top-navigation-area']//div[@id='top-navigation-image']";
	public static String topNaviagtionSearchBarPosition = "//div[@class='left-area top-navigation-area']//div[@id='search-wrapper']";
	public static String topNaviagtionTextPosition = "//div[@class='center-area top-navigation-area']//h1[@id='top-navigation-text']";
	public static String topNaviagtionActionPosition = "//div[@class='left-area top-navigation-area']//div[@id='actions-wrapper']";
	public static String cnx8CustomStyles = "//div[@id='custom-styles']/style[@id='cnx-custom-styles-wrapper']";
	public static String navBarLanguageSelectorDropdown = "//div[@id='language-switcher-wrapper']//a[@id='headerLanguageSelectorMenu']";
	public static String navBarEntryHomepageText = "//div[@id='side-navigation']//li[@id='homepage']//span[contains(text(), 'PLACEHOLDER')]";
	public static String navBarEntryCommunityText = "//div[@id='side-navigation']//li[@id='communities']//span[contains(text(), 'PLACEHOLDER')]";
	public static String navBarEntryPeopleText = "//div[@id='side-navigation']//li[@id='people']//span[contains(text(), 'PLACEHOLDER')]";

	

	//Language Selector
	public static String lsDropdown = "//a[@id='headerLanguageSelectorMenu']";

	public static String topNaviagtionLogoLeftPosition = "//div[@class='left-area top-navigation-area']//div[@id='top-navigation-image']";
	public static String topNaviagtionSearchBarRightPosition = "//div[@class='right-area top-navigation-area']//div[@id='search-wrapper']";
	public static String topNaviagtionTextLeftPosition = "//div[@class='left-area top-navigation-area']//h1[@id='top-navigation-text']";
	public static String topNaviagtionActionCenterPosition = "//div[@class='center-area top-navigation-area']//div[@id='actions-wrapper']";
	public static String tags = "//a[@class='bidiAware lotusF1']";


	//Test Case Updates for ExtendedBVT
	public static String addMemberLink = "css=a:contains(Add members)";
	
	public static String wrapperStyleHomepage = "//div[@dojoattachpoint='wrapper']";
	
	private HomepageUIConstants() {}

}
