package com.ibm.conn.auto.webui.constants;

public final class ProfilesUIConstants {


	/** Start of selectors section*/
	public static String MyProfile = "xpath=//a[@id='aProfileHeader_MyProfile'] | //a[text()='My Profile']";
	public static String MyICProfileCloud = "css=input[id='editProfileButton']";
	public static String PostStatus = "css=div ul li a[aria-label='Post'],li[class='lotusFirst'] a[class^='ublogPost']:contains(Post)";
	public static String UpdatesTextBox = "css=div[id^='mentionstextAreaNode'][placeholder='What do you want to share?'], body.cke_editable span:contains('What do you want to share?')";
	public static String UpdatesFrameName = "__gadget_newstarget_0";
	public static String UpdatesFrameTitle = "Updates";
	public static String UpdatesStatusFrame = "css=iframe[title='What do you want to share?']";
	public static String EditProfileBuilding = "css=input[id='bldgId']";
	public static String EditProfileFloor = "css=input[id='floor']";
	public static String EditProfileOffice = "css=input[id='officeName']";
	public static String EditIpTelephoneNumber = "css=input[id='ipTelephoneNumber']";
	public static String EditProfileMobileNo = "css=input[id='mobileNumber']";
	public static String EditPagerNo = "css=input[id='pagerNumber']";
	public static String EditAlternateEmail = "css=input[id='groupwareEmail']";
	public static String EditBlogURL = "css=input[id='blogUrl']";
	public static String EditJobResponsibility = "css=input[id='jobResp']";
	public static String ProfilesSearchForUser = "css=input[name='commonSearchControlDivsearchInput_textbox']";
	public static String ProfileSearch = "css=input[dojoattachpoint='onclick:submitForm']";
	public static String ProfilesTagTypeAhead = "css=input[id='socialTagName']";
	public static String ProfilesAddTag = "css=form span a#addTagButtonId[title='Add tag(s) to this profile']";
	public static String ProfilesAddLink = "css=div a#addLinkLinkRollButton";
	public static String ProfilesAddLinkName = "css=input[id='name']";
	public static String ProfilesAddLinkLinkname = "css=input[id='url']";
	public static String DeleteLink = "css=img[alt='Remove the link from your links section.']";
	public static String Show100PerPage = "css=.pagerLink_:contains(100)";
	public static String SendInvite = "css=input[value='Send Invitation']";
	public static String InvitationFollow = "css=input#lconn_profiles_invite_InvitePanel_0_invitation_follow";
	public static String NetworkRemove = "css=button#btn_actn__personCardRemoveFromNetwork";
	public static String InvitedMessage = " has been invited to your network contact list.";
	public static String AcceptedMessage = " has been added to your network contact list.";
	public static String Unfollow = "css=button#btn_actn__label_following_unfollow";
	public static String ProfilesTextArea = "css=[role='textbox'][placeholder='Write a message on this profile']";
	public static String FollowPerson= "css=button#btn_actn__label_following_follow.lotusBtn";
	public static String Invite_OnPrem = "css=button[id='btn_actn__personCardAddAsMyColleagues']";
	public static String AcceptInvite_OnPrem = "css=button#btn_actn__personCardAcceptInv";
	public static String Network_Invite_Form = "css=form#lconn_profiles_invite_InvitePanel_0_networkInviteForm";
	public static String iconSelectorDelete = " a[class^='iconRemove'][title='Remove contact']";
	public static String iconSelectorDeleteNew = " a[class^='iconDelete'][title^='Remove']";
	public static String iconSelectorEdit = " a[class^='iconEdit'][title^='Edit']";
	public static String contactSelector = "css=div[class='ccMember']:contains(";
	public static String contactBox = "css=div[class='ccMember']";
	public static String AddNewContactButton = "css=a[title='Add a new contact. ']";
	public static String informationMessage = "css=div[class='lotusMessageBody']";
	public static String ContactDetailsLink = "link=Details";
	public static String ContactDetailsTextboxBase = "css=input[class='lotusText']";
	public static String ContactCreationSuccessful="Successfully created the following contact: ";
	public static String ContactTitleField = "css=input[name='prefix']";
	public static String ContactFirstNameField = "css=input[name='firstName']";
	public static String ContactMiddleNameField = "css=input[name='middleName']";
	public static String ContactLastNameField = "css=input[name='lastName']";
	public static String ContactSuffixNameField = "css=input[name='suffix']";
	public static String ContactJobTitleField = "css=input[title='Title']";
	public static String ContactOrganizationField = "css=input[title='Organization']";
	public static String ContactEmailField = "css=input[title='name@example.com']";
	public static String ContactTelephoneField = "css=input[title='+x (xxx) xxx-xxxx']";
	public static String ContactAddressField = "css=textarea[title='Enter an address']";
	public static String ContactAddressStreetField = "css=textarea[name='street']";
	public static String ContactCustomInfoField = "css=input[title='Custom information']";
	public static String ContactNotes = "css=div[class='scNotesList'] tr[id$='_tr']";
	public static String ContactInitialNotesField = "css=textarea[class='lotusText lotusInactive'][title='']";
	public static String ContactEditNotesField = "css=textarea[class='editNoteTextArea']";
	public static String ContactUpdateBtn = "css=a:contains(Update)";
	public static String RelatedTagsSearchTypeAhead = "css=input[id='lconnTagWidgetcommonTagsTypeAhead']";
	public static String RelatedTagsSearchButton = "css=input[class='lotusSearchButton'][title='Search']";
	public static String SaveContactButton = "css=input[value='Save'], button[title='Save']";
	public static String ConfirmDeleteContactButton = "css=input[class^='lotusFormButton'][class$='submit']";
	public static String CancelDeleteContactButton = "css=input[class^='lotusFormButton'][class$='cancel']";
	public static String OKButton = "css=input[class='lotusFormButton submit'][value='OK']";
	public static String AddContactButton = "css=a[class='iconAdd scActionIcon'][title^='Add']";
	public static String AddContactButton2 = "css=td:contains('Create Contact')";
	public static String EditMyProfileBtn = "css=input[id='editProfileButton']";
	public static String profileJobTitle = "css=input[id='UserJobtitle'],input[id='jobResp']";
	public static String profileUserTele = "css=input[id='UserTelephone'],input[id='telephoneNumber']";
	public static String profileUserMobile = "css=input[id='UserMobilephone'],input[id='mobileNumber']";
	public static String profileUserFax = "css=input[id='UserFax'],input[id='faxNumber']";
	public static String profileUserAddress = "css=textarea[id='primaryAddressTextarea'],textarea[id='address1']";
	public static String profileUserWebsite = "css=input[id='UserWebsite']";
	public static String profileUserSave = "css=button[id='profileSaveButton1']";
	public static String profileUserCancel = "css=button:contains(Cancel), input[value='Cancel'][class='lotusBtn']";
	public static String RecentUpdates = "css=#news_tab";
	public static String ContactInfo = "css=#info_tab";
	public static String AboutMe = "css=#about_tab";
	public static String People = "css=a[id='networkMenu_btn']:contains(People), a[aria-label='Profiles'],div[id='networkMenu_container']:contains(People)";
	public static String MyContactsMenuItem = "css=a[role='menuitem']:contains(My Contacts)";
	public static String MyProfileMenuItem = "css=b>a[role='menuitem']:contains(My Profile)";
	public static String PeopleText = "People";
	public static String SaveCloseBtn = "css=div[id='ulEditProfileContactInfoActionButtons'] [value='Save and Close']";
	public static String confirmMsg = "css=div.lotusMessageBody:contains('uccessfully')";
	public static String errorMsg = "css=img.lotusIconMsgError";
	public static String  editMsg = "was saved successfully";
	public static String button_Add = "css=td:contains('Create Contact')";
	public static String button_Save = "css=div.lotusDialogFooter input[value='Save']";
	public static String link_SelectAll = "css=div[class='lotusRight lconnSelectAllContainer'] a:contains('All')";
	public static String button_BulkRemove = "css=div[class='scActionsBar lotusRight'] a[title='Remove contact']";
	public static String button_OK = "css=div.lotusDialogFooter input[value='OK']";
	public static String inviteToMyNetwork = "css=input#inputProfileActionAddColleague.lotusBtn";
	public static String acceptToMyNetwork  = "css=input#profileView_acceptInvitationButton.lotusBtn";
	public static String megaMenuProfiles = "css=#lotusBannerProfiles > a";
	public static String megaMenuProfilesMyNetwork = "css=a>strong:contains(My Network)";
	public static String megaMenuProfilesEditMyProfile = "css=a:contains(Edit My Profile)";
	public static String ActionsForMyLinksMenu = "css=a[id='widgetActionsMenulinkRoll']";
	public static String AddLinkSaveButton = "css=input[class='lotusFormButton'][type='submit'][value='Save']";
	public static String AddLinkCancelButton = "css=button:contains(Cancel), input[value='Cancel'][class='lotusFormButton'][dojoattachevent='onclick:cancelAddLink']";
	public static String MyLinksIBM = "css=a[class='lotusLeft'][href='http://www.ibm.com/privacy/us/en/']";
	public static String CloseWelcomeSection = "css=img[alt='Close welcome section']";
	public static String removeProfilePhotoReg = "css=a[data-dojo-attach-point='lnkRemove'][data-dojo-attach-event='onclick: clear']:contains(remove)";
	public static String saveProfileChangesReg = "css=button[id='profileSaveButton'][onclick^='saveChanges']";
	public static String changeLinkMyProfileReg = "css=div[data-dojo-attach-point='spnEdit'] a[title='Upload a Photo']:contains(change)";
	public static String uploadButtonReg = "xpath=//input[@id='fileUpload']";
	public static String ChooseAFileBtn = "css=	input[id='photoUploadFileSelector']";
	public static String uploadButtonReg2 = "css=input[class='lotusBtn'][data-dojo-attach-event='onclick: upload']";
	public static String defaultImageReg = "css=img[id='llprfPhotoView'][src$='/NoPhotoPerson64_1.40.25.png']";
	public static String profileIconMainMenuReg = "css=img[class='lotusArrow lotusDropDownSprite navbar_li_img_css']";
	public static String photoUploadButtonReg = "xpath=//input[@class='lotusBtn'][@type='button'][@title='Choose Photo']";
	public static String photoUploadButtonTypeInReg = "xpath=//input[@class='lotusOffScreen'][@name='PhotoName'][@accept='image/*']";
	public static String selectOKPhotoUploadReg = "css=input[type='button'][class='lotusFormButton submit'][value='OK']";
	public static String defaultImageContactReg = "css=div[class='lotusPhoto'] img[src^='/mycontacts/'][src$='/images/photo.png']";
	public static String MyNetwork = "css=li#liProfileHeader_MyNetwork a#aProfileHeader_MyNetwork";
	public static String LeftNavInvitations = "css=li#liInvites a#inivtesMenuA";
	public static String LeftNavContacts = "css=li#liColleagues a#aColleagues";
	public static String LeftNavFollowing = "css=li#liFollowing a#aFollowing";
	public static String InvitationMessage = "css=textarea#lconn_profiles_invite_InvitePanel_0_invitation_text";
	public static String editButton = "css=a[class='scEditButton']";
	public static String InviterUserNames = "css=table[class='lotusTable'] h4";
	public static String myProfileReg = "css=a[href*='/contacts/profiles/view/'][role='menuitem']:contains(My Profile)";
	public static String editProfileReg ="css=span[id='editChanges'] button[id='editProfileButton']";
	public static String TypeHeadTagName = "css=div[id^='socialTagName_popup'][role='option']";
	public static String ProfilesTagInputField = "input[id='socialTagName']";
	public static String TypeHeadTagDropDown = "css=div[id='socialTagName_dropdown']";
	public static String tagCloud = "css=a[id^='tagCloudActionBt']";
	public static String tagList = "css=a[id^='tagListActionBt']";
	public static String contactNameOrderDropdown="css=span[class^='dijitReset dijitInline']";
	public static String contactNameOrderSelections = "css=tr[id^='dijit_MenuItem_'] td[id^='dijit_MenuItem_'][id$='_text']";
	public static String TagsActionMenu = "css=a[id='widgetActionsMenusocialTags']";
	public static String HelpTaggingProfilesOpen = "css=a[class='active'][title='Tagging profiles']";
	public static String HelpTagFrame = "css=frame[name='HelpFrame']";
	public static String HelpNavFrame = "css=frame[name='NavFrame']";
	public static String HelpViewsFrame = "css=frame[name='ViewsFrame']";
	public static String HelpTOCIframe = "css=iframe[name='toc']";
	public static String HelpTOCViewframe = "css=frame[name='tocViewFrame']";
	public static String TagCreatorPopup = "css=div[class^='lotusCommentBubbleBody']";
	public static String MyNetworkMenuItem = "css=a[role='menuitem']:contains(My Network)";
	public static String MyOrgDirectoryMenuItem = "css=a[role='menuitem']:contains(Directory)";
	public static String PeopleImage = "css=img[class='lotusBannerIcon lconnSprite iconsComponents16-Profiles lotusBannerIcon-hybridTheme']";
	public static String UserPhotoNavbar = "css=img[class='scnotes_quirks']";
	public static String MyProfileMenuNav = "css=td[class='lotusNowrap lotusLastCell'] a:contains(My Profile)";
	public static String DownloadSeupMenuNav = "css=td[class='lotusNowrap lotusLastCell'] a:contains(Downloads and Setup)";
	public static String InviteToMyNetworkDailog = "//h1[@class=\"lotusHeading\"][text()='Invite to My Network']";
	public static String AlsoFollowCheckBox = "css=input[id$='_invitation_follow'][type='checkbox']";
	public static String InvitationMsgField = "css=textarea[name='invitation_text']";
	public static String InvitationTagsField = "css=input[id$='_invitation_tags']";
	public static String NewNetworkInvitation = "css=div[id='friendsSection'] a:contains('new invitation')";
	public static String ProfileVcard = "css=div.vcard.lotusHeading.lotusLeft";
	public static String ConnectionIndicator = "css=div#connectionIndicator";
	public static String DirectorySearch = "css=input[id='dijit_form_TextBox_0']";
	public static String Usetagslink = "link=use tags";
	public static String ProfileTaghelpPage = "css = a[class='active'][title='Understanding profile tags']";
	public static String FooterResultBox = "css=span[dojoattachpoint='allResults']";
	public static String ContentFrame = "css=frame[name='ContentFrame']";
	public static String ContentViewFrame = "css=frame[name='ContentViewFrame']";
	public static String HelpbannerClose = "css=a[id='_profilesViewWelcome_closeLink']";
	public static String DirectorySearchResultWidgets = "css=div[id^='com_ibm_social_personcard_widget_PersonWidget_']";
	public static String TagsYouAddedList = "css=div#tagsYouAddedList_div";
	public static String TagsListTags = "css=div#tagsListTags_div";
	public static String feedlink = "css=a[class='lotusFeed lotusAction']";
	public static String homelink = "css=div ul li a[aria-label='Home (This link opens a new window)']";
	public static String TermsofUselink = "link=Terms of Use";
	public static String privacylink = "link=Privacy";
	public static String systemstatuslink = "link=System Status";
	public static String contactuslink = "link=Contact Us";
	public static String whatsnewlink = "link=What's New";
	public static String thingsInCommonWidgetMenu = "css=a[id='widgetActionsMenusand_thingsInCommon']";
	public static String networkViewAllLink = "css=a[id='recent-friends-viewall']";
	public static String networkSection = "css=div[id='friendsSection'][class='lotusWidget2']";
	public static String recentupdatetypefield = "css=span span:contains[What do you want to share?]";
	public static String RecentupdateComment_iFrame = "css=iframe.cke_wysiwyg_frame[title='What do you want to share?']";
	public static String ActionsforRecentupdates = "css=a[id='tabsWidget1_widgetId_moreActionsLink']:contains(Actions for: Recent Updates)";
	public static String actionsForNetworkMenu = "css=a[id='widgetActionsMenufriends']";
	public static String post = "link=Post";
	public static String clear = "link=Clear";
	public static String addfile ="link=Add a File";
	public static String closemessage = "css=a[class^='lotusDelete'][title='Close message']";
	public static String showmoredetails = "css=a[alt='Show more details about this item'] > img";
	public static String updateTextboxwrite = "css=body.cke_editable";
	public static String successMsgclose = "css=div.wipeNode > div.lotusMessage2.lotusSuccess > a.lotusDelete > img[alt='Close message']";
	public static String postContentarea = "css=div[class='lotusPostContent']";
	public static String EEtextbox = "css=div[id^='mentionstextAreaNode_']";
	public static String profilesEEframe = "css=iframe[id^='__gadget'][title='Connections']";
	public static String EECommentPostlink = "css=a[role='button']:contains(Post)";
	public static String EEdialog = "css=div[class='lotusFlyoutInner']";
	public static String addfilePopup = "css=h1.lotusHeading";
	public static String recentupdatesFilterbyoption = "css=span[class='lotusLeft placeholderHeaderRight']:contains(Filter By)[value='communities']";
	public static String recentupdatesFilterby = "css=select[id='com_ibm_social_as_filter_FilterMenu_0_filterHolderNode']";
	public static String RecentUpdateattachmentFile = "css=span[dojoattachpoint='fileAttachmentDetailsNode'] span";
	public static String RecentUpdateFileIcon = "css=img[class^='lconnSprite lconnSprite-iconAttachment']";
	public static String RecentUpdateFileInput = "css=input[id*='_contents_contents'][type='file'][class='lotusOffScreen']";
	public static String DownloadVCardButton = "css=button[id='btn_actn__personCardDownloadVCard']";
	public static String ExportVcardDialog = "css=form[id='exportVcardDialogForm'][class='lotusDialog lotusForm']";
	public static String InternationalizedRadioButton = "css=input.lotusCheckbox[value='UTF-8']";
	public static String WesternEuropeanRadioButton = "css=input.lotusCheckbox[value='ISO-8859-1']";
	public static String JapaneseRadioButton = "css=input.lotusCheckbox[value='Cp943c']";
	public static String VcardDailogDownloadButton = "Download";
	public static String ShareaFileButton = "css=button#btn_actn__personCardShareFile";
	public static String ShowSharedWithMe = "link=Shared with me";
	public static String MoreActionButton = "css=button[id^='moreActionsBtn_lconn_profiles_actionBar_ActionBar_']";
	public static String AddContactRecordMenuItem = "css=tr[id^='dijit_MenuItem_'][title='Add Contact Record'], button#btn_actn__personCardAddContactRecord";
	public static String ViewContactRecordMenuItem = "css=tr[id^='dijit_MenuItem_'][title='View Contact Record'], button#btn_actn__personCardViewContactRecord";
	public static String DownloadVCardMenuItem = "css=tr[id^='dijit_MenuItem_'][title='Download vCard'], button#btn_actn__personCardDownloadVCard";
	public static String ChatButton = "css=button#btn_actn__personCardChat";
	public static String businessCardWindow = "css=div.personMenu, div#cardDiv";
	public static String networkfriendscontainer = "css=div#recent-friends-container a[class='fn lotusPerson hasHover url']";
	public static String networkUserDeleteIcon = "css=img[class^='iconDelete'][src='/connections/resources/web/com.ibm.lconn.core.styles.oneui3/images/blank.gif?etag=201510141300']";
	public static String userDeleteIcon = "css=a[class='iconDelete scActionIcon'][title='Remove contact']";
	public static String networkRightSide = "css=div[id='profilePaneRight']";
	public static String networkDeleteOkButton = "css=input[class='lotusFormButton submit'][type='button'][value='OK']";
	public static String DirectoryTab = "css=div[id='tertiary_level_nav'] a[id='aProfileHeader_Directory']";
	public static String WelcomePage = "css=div[class='lotusWelcomeBox']";
	public static String BackgroundTab = "css=#backgroundInfo_TabItem, [id='backgroundInfo_TabItem']";
	public static String BackgroundInfoContent = "css=#_backgroundInfo_profileDetails_widget_container";
	public static String ProfilePhoto = "css=#imgProfilePhoto";
	public static String PhotoPencilIcon = "css=#aEditProfilePhoto img";
	public static String EditPhotoTab = "css=#editTabPhoto";
	public static String ChooseAFileButton = "css=#photoUploadFileSelectorButton";
	public static String RemoveImage = "css=input[name='removeButton']";
	public static String SaveAndCloseBtn = "css=input[value='Save and Close']";
	public static String PhotoUploadDesc = "css=#photoUploadDesc";
	public static String PhotoUploadFileSelector = "css=input#photoUploadFileSelector[type='file'][name='photo']";
	public static String RecentUpdatesTab = "css=a[class='_linkHolder lotusLeft']:contains(Recent Updates)";
	public static String ContactInfoTab = "css=a[class='_linkHolder lotusLeft']:contains(Contact Information)";
	public static String BusinessCardDetails = "css=div#businessCardDetails";
	public static String ContactInfoDetails = "css=div#contactInfo";
	public static String BusinessCardContent = "css=div#businessCardContent";
	public static String SendEmailButton = "css=button#btn_actn__personCardSendEMail";
	public static String AssistantTypeAHead = "css=div[id^='secretaryUid.displayName_popup'][class='dijitMenuItem']";
	public static String EditAssistant = "css=input[id='secretaryUid.displayName']";
	public static String TimeZoneDropDown = "css=select#timezone";
	public static String anotheruserUpdatesTextBox = "css=div[id^='mentionstextAreaNode'][placeholder='What do you want to share?'], body.cke_editable span:contains('Write a message on this profile')";
	public static String atmention = "css=a:contains(@)";
	public static String usertypeahead = "css=div[id^='bhc_PeopleTypeAheadMenu_0'] span.bhcPeopleTypeAheadUserName";
	public static String EditBackgroundTab = "css=#editTabAboutMe a";
	public static String Filestab = "css=#filesReader_TabItem > a._linkHolder.lotusLeft";
	public static String sharedviewall = "css=#filesWithMeFeedContentContainer > div.lotusChunk > a.lotusAction";
	public static String FilesSharedWithMe = "link=Files Shared With Me";
	public static String MyFiles = "id=afilesMultiFeedReaderTab";
	public static String MyFilesviewall = "css=#filesFeedContentContainer > div.lotusChunk > a.lotusAction";
	public static String atmentionusers = "css=div[id='businessCardDetails']";
	public static String Background = "css=a[class='_linkHolder lotusLeft']:contains(Background)";
	public static String Viewalllink = "css=#filesByUserFeedContentContainer > div.lotusChunk > a.lotusAction";
	public static String DYKwidget = "css=span[id='sand_DYKId']:contains(Do You Know)";
	public static String ActionsforDoyouknow = "css=a[id='widgetActionsMenusand_DYK']";
	public static String Invitetoconnect = "css=button.lotusFormButton";
	public static String DYKuser = "css=a[class^='fn lotusPerson']";
	public static String StreamButtonPrev = "css=a[title='Show previous person']";
	public static String StreamButtonNext = "css=a[title='Show next person']";
	public static String DoyouknowUserremove = "link=Remove";
	public static String DoyouknowUserBizcard = "css=a[class='menu_drop_icon'][role='button']";
	public static String Orgdirdefaultsearch = "css=span[id='commonSearchControlDivsearchOpt']";
	public static String Directorycontact = "css=td[id^='dijit_MenuItem_']:contains(My Contacts)";
	public static String Directory = "css=td[id^='dijit_MenuItem_']:contains(Directory)";
	public static String Organizations = "css=td[id^='dijit_MenuItem_']:contains(Organizations)";
	public static String Guests = "css=td[id^='dijit_MenuItem_']:contains(Guests)";
	public static String AllContent = "css=td[id^='dijit_MenuItem_']:contains(All Content)";
	public static String Advanced = "css=td[id^='dijit_MenuItem_']:contains(Advanced)";
	public static String BusinessCardWindow = "css=div.personMenu, div#cardDiv";
	public static String BusinessCardShowLessMenu = "css=img#slimTwisty";
	public static String MyFilesRadioButton = "css=input[id^='lconn_files_widget_CompactFilePicker_'][id$='_option_myfiles']";
	public static String FirstOrgTag = "//div[@id='lotusTagCloud']/div/ul/li/a";
	public static String Findtaglink = "link=Find a Tag";
	public static String ActionsforOrgTags = "css=a[id='widgetActionsMenucommonTags']:contains(Actions for: Organization Tags)";
	public static String Orgtags = "css=span[id='commonTagsId']:contains(Organization Tags)";
	public static String PersonInfo = "css=div[class='lotusPersonInfo']";
	public static String HomelinkonPrem = "link=Home";
	public static String HelplinkonPrem = "link=Help";
	public static String IBMSupportForumslink  = "link=IBM Support Forums";
	public static String BookmarkingTools = "link=Bookmarking Tools";
	public static String ServerMetrics = "link=Server Metrics";
	public static String SubmitFeedback = "link=Submit Feedback";
	public static String IBMConnectionsonibm = "link=IBM Connections on ibm.com";
	public static String Aboutlink = "link=About";
	public static String AcceptButton = "css=button[title='Accept'][type='button']";
	public static String IgnoreButton = "css=button[title='Ignore'][type='button']";
	public static String ProfileByName = "css=a[aria-label='Search in Profiles by Name']";
	public static String ProfileByKeyword = "css=td[id^='dijit_MenuItem_']:contains('Profiles by Keyword')";
	public static String ProfilesBanner = "css=li[id='lotusBannerProfiles']";
	public static String UserMenu = "css=#headerUserName > img.lotusArrow.lotusDropDownSprite";
	public static String EditImageIcon = "css=a[title='Edit profile photo']";
	public static String ICAutoDirectory = "css=span[id='commonSearchControlDivsearchOpt']";
	public static String mouseOverScript = "if(document.createEvent){var evObj = document.createEvent('MouseEvents');evObj.initEvent('mouseover',true, false); arguments[0].dispatchEvent(evObj);} else if(document.createEventObject) { arguments[0].fireEvent('onmouseover');}";
	public static String AddcommentEEtextbox = "css=iframe[title='Add a comment']";
	public static String VideoCallButton = "css=button#btn_actn__personCardVideoCall";
	public static String BasicInfoPhoneCallLink = "css=div#businessCardDetails>span[data-phone-type='telephone']>a, div#businessCardDetails>span[data-phone-type='mobile']>a";
	public static String ContactInfoPhoneCallLink = "css=div#contactInfo span[data-phone-type='telephone']>a, div#contactInfo span[data-phone-type='mobile']>a";
	public static String ProfileSametimeStatus = "css=span#awarenessArea";
	public static String RankMyContentCheckBox = "css=input[aria-label='Rank my content higher']";
	//MT
	public static String NetworkLeftNavMenu = "css=div[id='profilesNavMenu']>ul>li";
	public static String NetworkLeftNav = "css=#profilesNavMenu";
	public static String pageSubTitle = "css=#pageSubTitle";
	public static String backGroundDescription = "css=[id='_backgroundInfo_profileDetails_widget_container']";
	public static String jobTitle = "css=#businessCardDetails strong[class='bidiAware']";
	public static String officeNumber = "//div[@id='_contactInfo_profileDetails_widget_container']//table//th[contains(text(),'Office number:')]//following-sibling::td";
	public static String mobileNumber = "//div[@id='_contactInfo_profileDetails_widget_container']//table//th[contains(text(),'Mobile number:')]//following-sibling::td";
	public static String stopFollowingLink = "css=a:contains('Stop Following')";
	public static String getTagsFromProfile = "css=#tagCloud div[class^='lotusTagCloud'] ul[role='list'] li a";
	public static String getListOfFollowingUsers = "css=#follow_mainContentTable tr div[role='article'] a";
	public static String linkInaboutMe = "css=div#_backgroundInfo_profileDetails_widget_container > p:nth-of-type(2)>a";
	public static String linkInBackground = "css=div#_backgroundInfo_profileDetails_widget_container > p:nth-of-type(5)>a";

	//cnx8
	public static String ShareFileButtonCnx8 = "//td[text()='Share a File']";
	public static String newInvitaionText = "#friends_count";
	public static String followingPageSubTitle = "//h1[@id='pageSubTitle'][contains(text(),'Following')]";
	public static String followersPageSubTitle = "//h1[@id='pageSubTitle'][contains(text(),'Contacts Following ')]";
	public static String removFromMyNetworkBtn = "//div[@id='frinds_removeFriendsDiv']//a[text()='Remove from My Network']";
	public static String removeBtn = "a[dojoattachpoint='DYKMainRemovePerson']";
	public static String doyouknowActions = "//a[@id='widgetActionsMenusand_DYK'][@aria-label='Actions for: People you may know']";
	public static String InviteToMyNetworkDailogueBox = "//div[starts-with(@widgetid,'lconn_profiles_invite_InvitePanel')]";
	public static String PYMKwidget = "#sand_DYKSection";
	public static String Followers = "li#liFollowers a#aFollowers";
	public static String directoryFullSearch = "//div//a[text()='Display full search options']";
	public static String hideFullSearchLink = "#divAdvancedSearchHideFull";
	public static String directoryFullSearchOptions = "#tableAdvancedSearchFields tr td.lotusFormLabel label";
	public static String fullSearchOptionDisName = "#tableAdvancedSearchFields input[name='displayName']";
	public static String button_Search = "table input[value='Search']";
	public static String directoryFullsearchResult = "//span[@class='vcard']//a";
	public static String profileSearchResultHeader = "//div[@id='searchInfo']";
	public static String PYMKUser = "div[class='vcard'] a[class^='fn lotusPerson']";
	public static String stopFollowingLinkNew = "//*[text()='Stop Following']";
	public static String stopFollowingIcon = "//button[@id=\"btn_actn__label_following_unfollow\"]/img";
	public static String LeftNavFollowers = "li#liFollowers a#aFollowers";
	public static String floorLabel = "label[for='floor']";
	public static String sortBy = "//span[text()='Sort by:']";
	public static String relevance = "//ul[@class='lotusInlinelist']//li[text()='Relevance']";
	public static String displayName = "//ul[@class='lotusInlinelist']//a[text()='Display name']";
	public static String familyName = "//ul[@class='lotusInlinelist']//a[text()='Family name']";
	public static String pagination = "div[class*='lotusPaging'] ul[class='lotusLeft lotusInlinelist']";
	public static String resultPerPage = "div[class='cnx8-ui-pull-to-center']";
	public static String resultPerPageDropdown = "//select[starts-with(@id,'pager_')]";
	public static String lastPageIcon = "div[class='cnx8-ui-pagination cnx8-ui-pagination-last']";
	public static String firstPageIcon = "div[class='cnx8-ui-pagination cnx8-ui-pagination-first']";
	public static String nextPageIcon = "div[class='cnx8-ui-pagination cnx8-ui-pagination-next']";
	public static String prePageIcon = "div[class='cnx8-ui-pagination cnx8-ui-pagination-prev']";
	public static String pullCenter = "ul[class='lotusInlinelist cnx8-ui-pull-to-center'] li";
	public static String searchResult = "div[class='cnx8ui-result-item-grid']";
	public static String ActionsforPeopleoyouknow = "widgetActionsMenusand_DYK";
	public static String peopleoyouknowLodingText = "div[dojoattachpoint='DYKLoading']";
	public static String removedFromNetworkMsg = "//div[starts-with(@id,'com_ibm_oneui_controls_MessageBox')]//span[text()='Network contact(s) removed.']";
	
	//Settings
	public static String notificationsPreferences = "//h1[@id='page_heading']";
	public static String sendEmailsText = "//table[@class='prefTable']//span[text()='Send emails to this address:']";
	public static String receiveNotificationsTxt = "//label[text()='Receive notifications from other people by email']";
	public static String receiveNotificationsCheckBox = "//input[@id='directNotifications']";
	public static String emailLanguageText = "//label[text()='Email language:']";
	public static String emailLanguageSelector = "//span[@id='NewsLanguageSelector']";
	public static String labelBrowserNotification = "//th[@id='livePreview']";
	public static String labelMentionsInBrowserNotification = "//div[@class='lotusFormBody responsesNotifications']//table[1]//span[@id='label_mentions']";
	public static String labelResponsesToMyInBrowserNotification =  "//div[@class='lotusFormBody responsesNotifications']//table[1]//span[@class='responsesDataBodyText']";
	public static String mentionsSwitch = "input[name='chkLivePreviewMentions']";
	public static String responsesToMySwitch = "input[name='chkLivePreviewNotifications']";
	public static String emailNotifications = "//span[@id='component_header']";
	public static String labelHowOftenDoIWantToBeNotified = "//span[text()='How often do I want to be notified about:']";
	public static String labelMentionsInEmailNotifications = "//div[@class='lotusFormBody responsesNotifications']//table[2]//span[@id='label_mentions']";
	public static String labelResponsesToMyInEmailNotifications = "//div[@class='lotusFormBody responsesNotifications']//table[2]//span[@class='responsesDataBodyText']";
	public static String restoreDefaultsBtn = "input[value='Restore Defaults']";
	public static String saveBtn = "input[value='Save']";
	public static String cancelBtn = "input[value='Cancel']";
		
	//CNX8UI new development
	public static String resultperpageDropwdown = "//div[@id='dropdown-selection']";
	public static String threeDotsActionIcon ="//button[starts-with(@id,'moreActionsBtn_lconn_profiles_actionBar_ActionBar')]";
	public static String anotherUserProfActionMenu = "//table[contains(@class,'dijitMenuActive')]//tr";
	public static String anotherUserProfActionMenuTable = "//table[contains(@class,'dijitMenuActive')]";
	public static String chatIconOnProfile = "#btn_actn__personCardChat";
	public static String ellipsisIcon = "//a[@class='dropbtn']";
	public static String closeButtonForMsg = "//span[contains(text(),'removed from your')]/ancestor::div[starts-with(@id,'com_ibm_oneui_controls_MessageBox')]//a[@class='lotusDelete']";
	public static String downloadBtnVcard = "#vcardDlgSubmit";
	public static String cancelBtnVcard = "#exportVcardDialogForm input[value='Cancel']";
	public static String profileName = "//a[@class='fn url lotusPerson bidiAware cnx8ui-bizcard-name']";
	public static String profileEmail = "//a[@class='bidiAware cnx8ui-bizcard-email']";
	public static String profileLocalTimeTitle = "//span[contains(text(),'Local Time:')]";
	public static String profileTime = "//span[@id='time']";
	public static String settingsLink = "//a[@id='aliProfileHeader_Settings']";
	public static String defaultHomepagePageHeading = "//h1[@id='page_heading']";
	public static String defaultHomepagePageTopUpdatesRadioBtn = "//span[contains(text(),'Top Updates')]";
	public static String defaultHomepagePageLatestUpdatesRadioBtn = "//span[contains(text(),'Latest Updates')]";
	public static String defaultHomepagePageDiscoverRadioBtn = "//span[contains(text(),'Discover')]";
	public static String defaultHomepagePageMyPageRadioBtn = "//span[contains(text(),'My Page')]";
	public static String editProfileUserCancel = "#ulEditProfileContactInfoActionButtons input[value='Cancel']";
	public static String settingsTab = "//div[@id='tertiary_level_nav']//*[text()='Settings']";
	public static String topNavSelectedItem = "div[id='tertiary_level_nav'] li[class$='lotusSelected']";
	public static String topNavPageRadioBtn = "//div[@class='def-hp-form-container']//span[contains(text(),'PLACEHOLDER')]";
	public static String defaultHomepageLinkAtSettings = "//span[contains(text(),'Default Homepage')]";
	public static String emailNotificationsLinkAtSettings = "//span[contains(text(),'Email Notifications')]";
	public static String applicationAccessLinkAtSettings = "//span[contains(text(),'Application Access')]";
	public static String globalizationLinkAtSettings = "//span[contains(text(),'Globalization')]";
	public static String secondaryLeftNavSettingPage = "//a[@class='lotusTab']/span";	
	public static String aboutmeBackground = "//span[@id='description.uilabel']";
	public static String backgroundTitle = "//span[@id='experience.uilabel']";
	public static String richTextEditorAtaboutmeBackground = "//body[@class='cke_editable cke_editable_themed cke_contents_ltr cke_show_borders']";
	public static String iframeInsideRichText = "//iframe[@class='cke_wysiwyg_frame cke_reset']";
	public static String photoTabEditProfile = "//a[@id='aEditTabPhoto']";
	public static String uploadNewImageText = "//label[@class='audioUploadFileSelector']";
	public static String pronunciationTabEditProfile = "//a[@id='aEditTabPronounciation']";
	public static String uploadAudioFilePronunciationTab = "//label[contains(text(),'Upload an audio file:')]";
	public static String allPeopleLink = "//a[@id='aColleagues']";
	public static String allPeoplePageSubTitle = "//p[contains(text(),'No network contacts are associated with this profi')]";
	public static String userImageUnderNetworkSection = "//div[@id='friendsSection']//div[@class='lotusLeft lotusNetworkPerson']";
	public static String orgnizationTagsSection = "#commonTagsSection";
	public static String inviteToConnectIcon = "#btn_actn__personCardAddAsMyColleagues";
	public static String directorSearchBox = "//div[starts-with(@id,'lconn_profiles_directory_SearchBoxWidget')]//input[contains(@title,'Enter a name, email address')]";
	public static String globalizationHeaderText = "//h1[text()='Globalization Settings']";
	public static String globalizationCalendarLabel = "//label[text()='Calendar:']";
	public static String globalizationCalendarDropdown = "//select[contains(@id ,'calendar')]";
	public static String globalizationCheckboxToEnableBidircetionalTxt = "//input[contains(@id ,'checkbox')]";
	public static String globalizationCheckboxLabel = "//label[text()='Enable bidirectional text ']";
	public static String globalizationdirectionOfUserGenTxt = "//label[text()='Direction of user-generated text: ']";
	public static String globalizationdirectionOfUserGenTxtDropdown = "//select[contains(@id,'direction')]";
	public static String paginationCountOnMyNetwork = "//ul[@class='lotusInlinelist cnx8-ui-pull-to-center']";
	public static String inviteToMyNetworkIcon = "btn_actn__personCardAddAsMyColleagues";
	public static String followIcon = "btn_actn__label_following_follow";
	public static String unFollowIcon = "btn_actn__label.following.following";
	public static String stopFollowingOnThreeDots = "//table[contains(@class,'dijitMenuTable')]//td[starts-with(@id,'dijit_MenuItem') and text()='Stop Following']";
	public static String networkContactIcon = "btn_actn__personCardInNetwork";
	public static String acceptInvitationIcon = "btn_actn__personCardAcceptInv";
	public static String reportToChainActionMenu = "widgetActionsMenureportStructure";
	

	private ProfilesUIConstants() {}
}
