package com.ibm.lconn.automation.framework.services.blogs.nodes;

import org.apache.abdera.model.Entry;

import com.ibm.lconn.automation.framework.services.common.nodes.LCEntry;

/**
 * MediaLink object contains the elements that make up a media link entry.
 * 
 * The content of this object is always generated by the server, 
 * this class is for read only use of media links.
 * 
 * @author Piyush Agarwal - pagarwal@us.ibm.com
 */
public class MediaLink extends LCEntry {
	
	public MediaLink(Entry entry) {
		super(entry);
	}
}
