--
-- Dumping data for table `table_rotate`
--

INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-activities","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-announcements","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-authentication","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `outcome` (`outcome`), KEY `reason` (`reason`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-blogs","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-bss","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-communities","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-company_administration","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-contacts","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `reason` VARCHAR(50), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `reason` (`reason`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-files","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-forms","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-forums","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-inotes","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `outcome` (`outcome`), KEY `reason` (`reason`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-meetings","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-profiles","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-sametime","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-surveys","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-theming","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-wikis","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");

--
-- Dumping data for table `logconfig`
--

INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("2","activities","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/ACTIVITIES.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("3","announcements","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/ANNOUNCEMENT.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("4","authentication","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/AUTH.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("5","blogs","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/BLOGS.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("6","bss","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/BSS.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("7","communities","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/COMMUNITIES.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("8","company_administration","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/COMPANY.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("9","contacts","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/CONTACT.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("10","files","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/FILES2.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("11","forms","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/FORMS.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("12","forums","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/FORUMS.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("13","inotes","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/INOTES.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("14","meetings","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/MEETINGS.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("15","profiles","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/PROFILE.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("16","sametime","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/SAMETIME.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("17","surveys","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/FEB.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("18","theming","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/THEME.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("19","wikis","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/WIKIS.txt","0","0","1","1","1");
