--
-- Table structure for table `collabservsvt2accesslog01`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog01` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog02`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog02` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog03`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog03` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog04`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog04` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog05`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog05` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog06`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog06` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog07`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog07` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog08`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog08` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog09`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog09` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog10`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog10` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog11`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog11` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog12`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog12` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog13`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog13` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog14`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog14` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog15`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog15` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog16`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog16` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog17`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog17` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog18`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog18` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog19`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog19` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog20`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog20` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog21`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog21` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog22`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog22` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog23`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog23` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog24`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog24` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog25`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog25` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog26`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog26` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog27`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog27` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog28`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog28` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog29`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog29` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog30`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog30` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `collabservsvt2accesslog31`
--

CREATE TABLE IF NOT EXISTS `collabservsvt2accesslog31` (
  `cached_response` VARCHAR(2000),
  `client_ip` VARCHAR(20),
  `connection_status` VARCHAR(1),
  `customer_id` BIGINT(15),
  `jsession_id` VARCHAR(150),
  `ltpa_token` VARCHAR(1000),
  `proxy_node` CHAR(50),
  `query_string` VARCHAR(2000),
  `remote_host` VARCHAR(20),
  `remote_logname` VARCHAR(100),
  `remote_user` VARCHAR(100),
  `request_date` DATE,
  `request_method` VARCHAR(10),
  `request_protocol` VARCHAR(20),
  `request_referer` VARCHAR(1000),
  `request_time` TIME,
  `response_size` INT(10) UNSIGNED,
  `response_time` BIGINT(14) UNSIGNED,
  `server_port` INT(8) UNSIGNED,
  `status_code` SMALLINT(3) UNSIGNED,
  `subscriber_id` BIGINT(15),
  `url_path` VARCHAR(300),
  `user_agent` VARCHAR(500),
  `x_forwarded_for` VARCHAR(100),
  KEY `cached_response` (`cached_response`),
  KEY `client_ip` (`client_ip`),
  KEY `connection_status` (`connection_status`),
  KEY `customer_id` (`customer_id`),
  KEY `jsession_id` (`jsession_id`),
  KEY `ltpa_token` (`ltpa_token`),
  KEY `proxy_node` (`proxy_node`),
  KEY `query_string` (`query_string`),
  KEY `remote_host` (`remote_host`),
  KEY `remote_logname` (`remote_logname`),
  KEY `remote_user` (`remote_user`),
  KEY `request_date` (`request_date`),
  KEY `request_method` (`request_method`),
  KEY `request_protocol` (`request_protocol`),
  KEY `request_referer` (`request_referer`),
  KEY `request_time` (`request_time`),
  KEY `response_size` (`response_size`),
  KEY `response_time` (`response_time`),
  KEY `server_port` (`server_port`),
  KEY `status_code` (`status_code`),
  KEY `subscriber_id` (`subscriber_id`),
  KEY `url_path` (`url_path`),
  KEY `user_agent` (`user_agent`),
  KEY `x_forwarded_for` (`x_forwarded_for`)
);

--
-- Table structure for table `table_rotate`
--

CREATE TABLE IF NOT EXISTS `table_rotate` (
  `id` SMALLINT(5) UNSIGNED AUTO_INCREMENT,
  `name` VARCHAR(100),
  `suffix` VARCHAR(20),
  `design` VARCHAR(2048),
  `history` SMALLINT(5) UNSIGNED,
  `enabled` TINYINT(1),
  PRIMARY KEY (`id`)
) ;

--
-- Table structure for table `logconfig`
--

CREATE TABLE IF NOT EXISTS `logconfig` (
  `id` SMALLINT(5) UNSIGNED AUTO_INCREMENT,
  `table_id` SMALLINT(5) UNSIGNED,
  `application` CHAR(50),
  `hostname` CHAR(50),
  `type` VARCHAR(50),
  `logfile` VARCHAR(256),
  `lasteof` BIGINT(20) UNSIGNED,
  `pid` BIGINT(20) UNSIGNED,
  `process` TINYINT(1),
  `production` TINYINT(1),
  `enabled` TINYINT(1),
  PRIMARY KEY (`id`),
  FOREIGN KEY (`table_id`) REFERENCES `table_rotate`(`id`)
) ;

--
-- Dumping data for table `table_rotate`
--

INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("collabservsvt2accesslog","dd","`cached_response` VARCHAR(2000), `client_ip` VARCHAR(20), `connection_status` VARCHAR(1), `customer_id` BIGINT(15), `jsession_id` VARCHAR(150), `ltpa_token` VARCHAR(1000), `proxy_node` CHAR(50), `query_string` VARCHAR(2000), `remote_host` VARCHAR(20), `remote_logname` VARCHAR(100), `remote_user` VARCHAR(100), `request_date` DATE, `request_method` VARCHAR(10), `request_protocol` VARCHAR(20), `request_referer` VARCHAR(1000), `request_time` TIME, `response_size` INT(10) UNSIGNED, `response_time` BIGINT(14) UNSIGNED, `server_port` INT(8) UNSIGNED, `status_code` SMALLINT(3) UNSIGNED, `subscriber_id` BIGINT(15), `url_path` VARCHAR(300), `user_agent` VARCHAR(500), `x_forwarded_for` VARCHAR(100), KEY `cached_response` (`cached_response`), KEY `client_ip` (`client_ip`), KEY `connection_status` (`connection_status`), KEY `customer_id` (`customer_id`), KEY `jsession_id` (`jsession_id`), KEY `ltpa_token` (`ltpa_token`), KEY `proxy_node` (`proxy_node`), KEY `query_string` (`query_string`), KEY `remote_host` (`remote_host`), KEY `remote_logname` (`remote_logname`), KEY `remote_user` (`remote_user`), KEY `request_date` (`request_date`), KEY `request_method` (`request_method`), KEY `request_protocol` (`request_protocol`), KEY `request_referer` (`request_referer`), KEY `request_time` (`request_time`), KEY `response_size` (`response_size`), KEY `response_time` (`response_time`), KEY `server_port` (`server_port`), KEY `status_code` (`status_code`), KEY `subscriber_id` (`subscriber_id`), KEY `url_path` (`url_path`), KEY `user_agent` (`user_agent`), KEY `x_forwarded_for` (`x_forwarded_for`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-activities","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-announcements","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-authentication","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `outcome` (`outcome`), KEY `reason` (`reason`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-blogs","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-bss","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-communities","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-company_administration","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-contacts","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `reason` VARCHAR(50), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `reason` (`reason`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-files","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-forms","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-forums","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-inotes","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `outcome` (`outcome`), KEY `reason` (`reason`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-meetings","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-profiles","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-sametime","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-surveys","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-theming","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");
INSERT INTO `table_rotate` (`name`, `suffix`, `design`, `history`, `enabled`) VALUES ("journals-wikis","","`date` DATE, `time` TIME, `subject_email` VARCHAR(250), `subject_subscriber_id` VARCHAR(50), `subject_customer_id` VARCHAR(50), `action` VARCHAR(50), `object_type` VARCHAR(100), `object_id` VARCHAR(50), `object_name` VARCHAR(500), `object_customer_id` VARCHAR(50), `target_type` VARCHAR(100), `target_id` VARCHAR(50), `target_name` VARCHAR(500), `target_customer_id` VARCHAR(50), `outcome` VARCHAR(50), `reason` VARCHAR(50), `extra` VARCHAR(500), KEY `date` (`date`), KEY `time` (`time`), KEY `subject_email` (`subject_email`), KEY `subject_subscriber_id` (`subject_subscriber_id`), KEY `subject_customer_id` (`subject_customer_id`), KEY `action` (`action`), KEY `object_type` (`object_type`), KEY `object_id` (`object_id`), KEY `object_name` (`object_name`), KEY `object_customer_id` (`object_customer_id`), KEY `target_type` (`target_type`), KEY `target_id` (`target_id`), KEY `target_name` (`target_name`), KEY `target_customer_id` (`target_customer_id`), KEY `outcome` (`outcome`), KEY `reason` (`reason`), KEY `extra` (`extra`)","30","1");

--
-- Dumping data for table `logconfig`
--

INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("1","collabservsvt2","rp1a.bht6.swg.usma.ibm.com","access_log_collabservsvt2","/logs/rp1a.bht6.swg.usma.ibm.com/apps_collabservsvt2_access_log","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("1","collabservsvt2","rp1b.bht6.swg.usma.ibm.com","access_log_collabservsvt2","/logs/rp1b.bht6.swg.usma.ibm.com/apps_collabservsvt2_access_log","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("2","activities","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/ACTIVITIES.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("3","announcements","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/ANNOUNCEMENT.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("4","authentication","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/AUTH.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("5","blogs","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/BLOGS.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("6","bss","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/BSS.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("7","communities","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/COMMUNITIES.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("8","company_administration","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/COMPANY.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("9","contacts","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/CONTACT.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("10","files","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/FILES2.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("11","forms","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/FORMS.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("12","forums","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/FORUMS.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("13","inotes","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/INOTES.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("14","meetings","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/MEETINGS.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("15","profiles","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/PROFILE.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("16","sametime","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/SAMETIME.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("17","surveys","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/FEB.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("18","theming","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/THEME.txt","0","0","1","1","1");
INSERT INTO `logconfig` (`table_id`,`application`,`hostname`,`type`,`logfile`,`lasteof`,`pid`,`process`,`production`,`enabled`) VALUES ("19","wikis","ftp.collabservsvt2.swg.usma.ibm.com","journals","/logs/journals/WIKIS.txt","0","0","1","1","1");
