

/*xml string constants*/

var activityTemplate = '<xml><block type="tools_login" x="88" y="4"><title name="URL">lc30linux3.swg.usma.ibm.com</title><title name="UNAME">ajones3</title><title name="PWORD">jones3</title><statement name="action"><block type="activity_activity" inline="false"><mutation items="2"></mutation><title name="TITLE">BBQ</title><title name="CONTENT">Let\'s have a BBQ!</title><title name="DATE">8/15/12</title><title name="TAGS">food bbq</title><title name="VIS">false</title><statement name="action"><block type="activity_section"><title name="TITLE">food</title><statement name="action"><block type="activity_entry"><title name="TITLE">What should we eat?</title><title name="CONTENT">What kind of food should we have?</title><title name="TAGS">food</title><title name="VIS">false</title><statement name="action"><block type="tools_login"><title name="URL">lc30linux3.swg.usma.ibm.com</title><title name="UNAME">ajones2</title><title name="PWORD">jones2</title><statement name="action"><block type="activity_reply"><title name="TITLE">bringing</title><title name="CONTENT">I can bring chips!</title><title name="VIS">false</title><statement name="action"><block type="tools_login"><title name="URL">lc30linux3.swg.usma.ibm.com</title><title name="UNAME">ajones3</title><title name="PWORD">jones3</title><statement name="action"><block type="activity_reply"><title name="TITLE">bringing</title><title name="CONTENT">Great!</title><title name="VIS">false</title></block></statement></block></statement></block></statement></block></statement><next><block type="activity_todo"><title name="TITLE">Bring hamburgers</title><title name="CONTENT">Someone needs to volunteer to bring hamburgers</title><title name="TAGS">food</title><title name="VIS">false</title></block></next></block></statement><next><block type="activity_section"><title name="TITLE">games</title><statement name="action"><block type="activity_entry"><title name="TITLE">What should we play?</title><title name="CONTENT">What kind of games should we play at the BBQ</title><title name="TAGS">games</title><title name="VIS">false</title></block></statement></block></next></block></statement><value name="MEM0"><block type="activity_amy_member"><title name="NUM">2</title></block></value><value name="MEM1"><block type="activity_member"><title name="EMAIL">ajones4@janet.iris.com</title></block></value></block></statement></block></xml>';
var blogTemplate = '<xml><block type="tools_login" x="-487" y="-352"><title name="URL">lc30linux3.swg.usma.ibm.com</title><title name="UNAME">ajones102</title><title name="PWORD">jones102</title><statement name="action"><block type="blog_blog"><title name="TITLE">my blog</title><title name="HANDLE">amysawesomeblog</title><title name="SUM">this is my blog</title><title name="TAG">blog test</title><title name="NUM">5</title><title name="COM">true</title><title name="MOD">false</title><statement name="action"><block type="blog_entry"><title name="TITLE">awesome entry</title><title name="CONTENT">this is my first blog entry!</title><title name="TAG">entry</title><title name="NUM">5</title><title name="COM">true</title><statement name="action"><block type="tools_login"><title name="URL">lc30linux3.swg.usma.ibm.com</title><title name="UNAME">ajones101</title><title name="PWORD">jones101</title><statement name="action"><block type="blog_comment"><title name="CONTENT">Hi amy!  it\'s so cool that you have a blog!</title></block></statement><next><block type="tools_login"><title name="URL">lc30linux3.swg.usma.ibm.com</title><title name="UNAME">ajones103</title><title name="PWORD">jones103</title><statement name="action"><block type="blog_comment"><title name="CONTENT">Amy! I\'m so proud of you!</title></block></statement></block></next></block></statement></block></statement></block></statement></block></xml>';
var forumTemplate = '<xml><block type="tools_login" x="-120" y="-30"><title name="URL">lc30linux3.swg.usma.ibm.com</title><title name="UNAME">ajones3</title><title name="PWORD">jones3</title><statement name="action"><block type="forum_forum"><title name="TITLE">tech support</title><title name="CONTENT">A forum for providing technical support</title><statement name="action"><block type="forum_topic"><title name="TITLE">Please read before posting</title><title name="CONTENT">Please comply with the rules of the forum and do not repost earlier topics</title><title name="PIN">true</title><title name="LOK">true</title><title name="Q">false</title><title name="A">false</title><next><block type="tools_login"><title name="URL">lc30linux3.swg.usma.ibm.com</title><title name="UNAME">ajones4</title><title name="PWORD">jones4</title><statement name="action"><block type="forum_topic"><title name="TITLE">How do I change my screensaver</title><title name="CONTENT">I haven\'t been able to change my screen saver.</title><title name="PIN">false</title><title name="LOK">false</title><title name="Q">true</title><title name="A">false</title><statement name="action"><block type="tools_login"><title name="URL">lc30linux3.swg.usma.ibm.com</title><title name="UNAME">ajones3</title><title name="PWORD">jones3</title><statement name="action"><block type="forum_reply"><title name="TITLE">response</title><title name="CONTENT">Please consult your user manual</title><title name="A">true</title></block></statement></block></statement></block></statement><next><block type="tools_login"><title name="URL">lc30linux3.swg.usma.ibm.com</title><title name="UNAME">ajones5</title><title name="PWORD">jones5</title><statement name="action"><block type="forum_topic"><title name="TITLE">How do I shut off my computer?</title><title name="CONTENT">I can\'t turn it off</title><title name="PIN">false</title><title name="LOK">false</title><title name="Q">true</title><title name="A">false</title><statement name="action"><block type="tools_login"><title name="URL">lc30linux3.swg.usma.ibm.com</title><title name="UNAME">ajones3</title><title name="PWORD">jones3</title><statement name="action"><block type="tools_loop"><title name="START">5</title><title name="NUM">20</title><title name="INC">1</title><statement name="action"><block type="forum_reply"><title name="TITLE">response</title><title name="CONTENT">Please consult your user manual</title><title name="A">false</title></block></statement></block></statement></block></statement></block></statement></block></next></block></next></block></statement></block></statement></block></xml>';
var wikiTemplate = '<xml><block type="tools_login" x="-143" y="-361"><title name="URL">lc30linux3.swg.usma.ibm.com</title><title name="UNAME">ajones2</title><title name="PWORD">jones2</title><statement name="action"><block type="wiki_wiki" inline="false"><mutation items="2"></mutation><title name="TITLE">datapop wiki</title><title name="SUM">How to use the new datapop tool</title><title name="TAGS">datapop</title><title name="VIS">false</title><statement name="action"><block type="wiki_page"><title name="TITLE">Using templates</title><title name="CONTENT">click the import template button</title><title name="TAG">template</title><next><block type="tools_login"><title name="URL">lc30linux3.swg.usma.ibm.com</title><title name="UNAME">ajones3</title><title name="PWORD">jones3</title><statement name="action"><block type="wiki_page"><title name="TITLE">Adding members</title><title name="CONTENT">click the blue plus button</title><title name="TAG">member</title></block></statement><next><block type="tools_loop"><title name="START">1</title><title name="NUM">5</title><title name="INC">1</title><statement name="action"><block type="wiki_page"><title name="TITLE">looping</title><title name="CONTENT">add a loop block</title><title name="TAG">loop</title></block></statement></block></next></block></next></block></statement><value name="MEM0"><block type="wiki_amy_member"><title name="NUM">1</title><title name="ROLE">editor</title></block></value><value name="MEM1"><block type="wiki_member"><title name="EMAIL">amy jones3</title><title name="ROLE">editor</title></block></value></block></statement></block></xml>';
var communityTemplate = '<xml><block type="tools_login" x="-30" y="17"><title name="URL">lc30linux3.swg.usma.ibm.com</title><title name="UNAME">ajones11</title><title name="PWORD">jones11</title><statement name="action"><block type="community_community" inline="false"><mutation items="2"></mutation><title name="TITLE">Amy Community</title><title name="SUM">A community for people named amy</title><title name="TAGS">amy</title><title name="VIS">public</title><statement name="action"><block type="bookmark_bookmark"><title name="TITLE">This is a great site about the name Amy</title><title name="CONTENT">This is awesome</title><title name="TAG">wiki amy</title><title name="LINK">http://en.wikipedia.org/wiki/Amy</title><next><block type="tools_login"><title name="URL">lc30linux3.swg.usma.ibm.com</title><title name="UNAME">ajones9</title><title name="PWORD">jones9</title><statement name="action"><block type="forum_topic"><title name="TITLE">Amy</title><title name="CONTENT">How awesome is the name Amy?</title><title name="PIN">false</title><title name="LOK">false</title><title name="Q">true</title><title name="A">false</title><statement name="action"><block type="tools_login"><title name="URL">lc30linux3.swg.usma.ibm.com</title><title name="UNAME">ajones5</title><title name="PWORD">jones5</title><statement name="action"><block type="forum_reply"><title name="TITLE">Answer</title><title name="CONTENT">So awesome!</title><title name="A">true</title></block></statement></block></statement></block></statement></block></next></block></statement><value name="MEM0"><block type="community_amy_member"><title name="NUM">10</title></block></value><value name="MEM1"><block type="community_member"><title name="EMAIL">amy jones12</title></block></value></block></statement></block></xml>';


var templateList = new Array();
templateList[0] = activityTemplate;
templateList[1] = blogTemplate;
templateList[2] = forumTemplate;
templateList[3] = wikiTemplate;
templateList[4] = communityTemplate;


function setUpTemplateSelect()
{
document.getElementById("templateSelect").innerHTML = ''+
'<select id="templateSelectBox" size="1">'+
  '<option >Activity Template</option>'+
  '<option >Blog Template</option>'+
  '<option >Forum Template</option>'+
  '<option >Wiki Template</option>'+
  '<option >Community Template</option>'+
'</select>';
}

function loadSelectedTemplate()
{
	var index = document.getElementById("templateSelectBox").selectedIndex;
	console.log("template index: " + index);
	loadTemplate(templateList[index]);
}

function loadTemplate(code)
{
	var xml = Blockly.Xml.textToDom(code);
	Blockly.Xml.domToWorkspace(Blockly.mainWorkspace, xml);
}



